// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../../internal/core/report/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../../internal/core/storage/models.js";

/**
 * Type aliases
 */
export const ReportStatus = report$0.ReportStatus;

/**
 * Type aliases
 * @typedef {report$0.ReportStatus} ReportStatus
 */

/**
 * Type aliases
 */
export const StorageRecordingConfig = storage$0.RecordingConfig;

/**
 * Type aliases
 * @typedef {storage$0.RecordingConfig} StorageRecordingConfig
 */

/**
 * Type aliases
 */
export const StorageRecordingStatus = storage$0.RecordingStatus;

/**
 * Type aliases
 * @typedef {storage$0.RecordingStatus} StorageRecordingStatus
 */
