// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConfig(arg1, arg2) {
  return window['go']['backend']['App']['ApplyConfig'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['backend']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['App']['DeleteProfile'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['backend']['App']['Disconnect'](arg1);
}

export function GetProfiles() {
  return window['go']['backend']['App']['GetProfiles']();
}

export function GetRecordingStatus() {
  return window['go']['backend']['App']['GetRecordingStatus']();
}

export function GetStatus(arg1) {
  return window['go']['backend']['App']['GetStatus'](arg1);
}

export function PickDirectory() {
  return window['go']['backend']['App']['PickDirectory']();
}

export function StartAcquisition(arg1) {
  return window['go']['backend']['App']['StartAcquisition'](arg1);
}

export function StartRecording(arg1, arg2) {
  return window['go']['backend']['App']['StartRecording'](arg1, arg2);
}

export function StopAcquisition(arg1) {
  return window['go']['backend']['App']['StopAcquisition'](arg1);
}

export function StopRecording() {
  return window['go']['backend']['App']['StopRecording']();
}

export function UpsertProfile(arg1) {
  return window['go']['backend']['App']['UpsertProfile'](arg1);
}
