// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function MotionConnect(arg1:string):Promise<void>;

export function MotionDefinePosition(arg1:string,arg2:string,arg3:number):Promise<void>;

export function MotionDeleteProfile(arg1:string):Promise<void>;

export function MotionDisconnect(arg1:string):Promise<void>;

export function MotionEmergencyStop(arg1:string):Promise<void>;

export function MotionGetProfiles():Promise<string>;

export function MotionGetStatus():Promise<string>;

export function MotionHome(arg1:string,arg2:string):Promise<void>;

export function MotionJog(arg1:string,arg2:string,arg3:number):Promise<void>;

export function MotionMoveBy(arg1:string,arg2:string,arg3:number):Promise<void>;

export function MotionMoveTo(arg1:string,arg2:string,arg3:number):Promise<void>;

export function MotionResetEmergencyStop(arg1:string):Promise<void>;

export function MotionStop(arg1:string,arg2:string):Promise<void>;

export function MotionUpsertProfile(arg1:core.MotionControllerProfile):Promise<void>;
