// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MotionConnect(arg1) {
  return window['go']['backend']['App']['MotionConnect'](arg1);
}

export function MotionDefinePosition(arg1, arg2, arg3) {
  return window['go']['backend']['App']['MotionDefinePosition'](arg1, arg2, arg3);
}

export function MotionDeleteProfile(arg1) {
  return window['go']['backend']['App']['MotionDeleteProfile'](arg1);
}

export function MotionDisconnect(arg1) {
  return window['go']['backend']['App']['MotionDisconnect'](arg1);
}

export function MotionEmergencyStop(arg1) {
  return window['go']['backend']['App']['MotionEmergencyStop'](arg1);
}

export function MotionGetProfiles() {
  return window['go']['backend']['App']['MotionGetProfiles']();
}

export function MotionGetStatus() {
  return window['go']['backend']['App']['MotionGetStatus']();
}

export function MotionHome(arg1, arg2) {
  return window['go']['backend']['App']['MotionHome'](arg1, arg2);
}

export function MotionJog(arg1, arg2, arg3) {
  return window['go']['backend']['App']['MotionJog'](arg1, arg2, arg3);
}

export function MotionMoveBy(arg1, arg2, arg3) {
  return window['go']['backend']['App']['MotionMoveBy'](arg1, arg2, arg3);
}

export function MotionMoveTo(arg1, arg2, arg3) {
  return window['go']['backend']['App']['MotionMoveTo'](arg1, arg2, arg3);
}

export function MotionResetEmergencyStop(arg1) {
  return window['go']['backend']['App']['MotionResetEmergencyStop'](arg1);
}

export function MotionStop(arg1, arg2) {
  return window['go']['backend']['App']['MotionStop'](arg1, arg2);
}

export function MotionUpsertProfile(arg1) {
  return window['go']['backend']['App']['MotionUpsertProfile'](arg1);
}
