// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function BatchCalculate(datas: $models.InterpolationInput[]): $CancellablePromise<$models.BatchCalculateResponse> {
    return $Call.ByID(2753499237, datas).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Calculate(input: $models.InterpolationInput): $CancellablePromise<$models.CalculateResponse> {
    return $Call.ByID(2871826531, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMachRange(): $CancellablePromise<$models.MachRangeResponse> {
    return $Call.ByID(1141492255).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPrbFiles(): $CancellablePromise<$models.PrbFileInfo[]> {
    return $Call.ByID(2882545116).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ImportCsvData(): $CancellablePromise<$models.ImportCsvDataResponse> {
    return $Call.ByID(2962451808).then(($result: any) => {
        return $$createType5($result);
    });
}

export function IsPrbLoaded(): $CancellablePromise<boolean> {
    return $Call.ByID(3634641882);
}

export function LoadPrbFiles(): $CancellablePromise<$models.LoadPrbResponse> {
    return $Call.ByID(2125259382).then(($result: any) => {
        return $$createType6($result);
    });
}

export function OpenHelpDoc(): $CancellablePromise<void> {
    return $Call.ByID(1956278660);
}

// Private type creation functions
const $$createType0 = $models.BatchCalculateResponse.createFrom;
const $$createType1 = $models.CalculateResponse.createFrom;
const $$createType2 = $models.MachRangeResponse.createFrom;
const $$createType3 = $models.PrbFileInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ImportCsvDataResponse.createFrom;
const $$createType6 = $models.LoadPrbResponse.createFrom;
