// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BatchCalculateResponse {
    "success": boolean;
    "error"?: string;
    "data"?: (InterpolationResult | null)[];

    /** Creates a new BatchCalculateResponse instance. */
    constructor($$source: Partial<BatchCalculateResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchCalculateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchCalculateResponse {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new BatchCalculateResponse($$parsedSource as Partial<BatchCalculateResponse>);
    }
}

export class CalculateResponse {
    "success": boolean;
    "error"?: string;
    "data"?: InterpolationResult | null;

    /** Creates a new CalculateResponse instance. */
    constructor($$source: Partial<CalculateResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalculateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CalculateResponse {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new CalculateResponse($$parsedSource as Partial<CalculateResponse>);
    }
}

export class ImportCsvDataResponse {
    "success": boolean;
    "error"?: string;
    "data"?: InterpolationInput[];

    /** Creates a new ImportCsvDataResponse instance. */
    constructor($$source: Partial<ImportCsvDataResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportCsvDataResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportCsvDataResponse {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ImportCsvDataResponse($$parsedSource as Partial<ImportCsvDataResponse>);
    }
}

export class InterpolationInput {
    "P1": number;
    "P2": number;
    "P3": number;
    "Patm": number;
    "Tatm": number;
    "pressureMode": string;

    /** Creates a new InterpolationInput instance. */
    constructor($$source: Partial<InterpolationInput> = {}) {
        if (!("P1" in $$source)) {
            this["P1"] = 0;
        }
        if (!("P2" in $$source)) {
            this["P2"] = 0;
        }
        if (!("P3" in $$source)) {
            this["P3"] = 0;
        }
        if (!("Patm" in $$source)) {
            this["Patm"] = 0;
        }
        if (!("Tatm" in $$source)) {
            this["Tatm"] = 0;
        }
        if (!("pressureMode" in $$source)) {
            this["pressureMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterpolationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): InterpolationInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterpolationInput($$parsedSource as Partial<InterpolationInput>);
    }
}

export class InterpolationResult {
    "alpha": number;
    "machNumber": number;
    "P0": number;
    "Ps": number;
    "iterationCount": number;
    "isValid": boolean;
    "warning"?: string;

    /** Creates a new InterpolationResult instance. */
    constructor($$source: Partial<InterpolationResult> = {}) {
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("machNumber" in $$source)) {
            this["machNumber"] = 0;
        }
        if (!("P0" in $$source)) {
            this["P0"] = 0;
        }
        if (!("Ps" in $$source)) {
            this["Ps"] = 0;
        }
        if (!("iterationCount" in $$source)) {
            this["iterationCount"] = 0;
        }
        if (!("isValid" in $$source)) {
            this["isValid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterpolationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InterpolationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InterpolationResult($$parsedSource as Partial<InterpolationResult>);
    }
}

export class LoadPrbResponse {
    "success": boolean;
    "error"?: string;
    "data"?: LoadPrbResult | null;

    /** Creates a new LoadPrbResponse instance. */
    constructor($$source: Partial<LoadPrbResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadPrbResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadPrbResponse {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new LoadPrbResponse($$parsedSource as Partial<LoadPrbResponse>);
    }
}

export class LoadPrbResult {
    "files": PrbFileInfo[];
    "machRange": number[];
    "warnings": string[];

    /** Creates a new LoadPrbResult instance. */
    constructor($$source: Partial<LoadPrbResult> = {}) {
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("machRange" in $$source)) {
            this["machRange"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadPrbResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadPrbResult {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        if ("machRange" in $$parsedSource) {
            $$parsedSource["machRange"] = $$createField1_0($$parsedSource["machRange"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new LoadPrbResult($$parsedSource as Partial<LoadPrbResult>);
    }
}

export class MachRangeResponse {
    "success": boolean;
    "error"?: string;
    "data"?: number[];

    /** Creates a new MachRangeResponse instance. */
    constructor($$source: Partial<MachRangeResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MachRangeResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MachRangeResponse {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new MachRangeResponse($$parsedSource as Partial<MachRangeResponse>);
    }
}

export class PrbFileInfo {
    "filePath": string;
    "fileName": string;
    "machNumber": number;
    "validRange": PrbValidRange;

    /** Creates a new PrbFileInfo instance. */
    constructor($$source: Partial<PrbFileInfo> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("machNumber" in $$source)) {
            this["machNumber"] = 0;
        }
        if (!("validRange" in $$source)) {
            this["validRange"] = (new PrbValidRange());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrbFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PrbFileInfo {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("validRange" in $$parsedSource) {
            $$parsedSource["validRange"] = $$createField3_0($$parsedSource["validRange"]);
        }
        return new PrbFileInfo($$parsedSource as Partial<PrbFileInfo>);
    }
}

export class PrbValidRange {
    "alphaMin": number;
    "alphaMax": number;
    "machMin": number;
    "machMax": number;

    /** Creates a new PrbValidRange instance. */
    constructor($$source: Partial<PrbValidRange> = {}) {
        if (!("alphaMin" in $$source)) {
            this["alphaMin"] = 0;
        }
        if (!("alphaMax" in $$source)) {
            this["alphaMax"] = 0;
        }
        if (!("machMin" in $$source)) {
            this["machMin"] = 0;
        }
        if (!("machMax" in $$source)) {
            this["machMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrbValidRange instance from a string or object.
     */
    static createFrom($$source: any = {}): PrbValidRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrbValidRange($$parsedSource as Partial<PrbValidRange>);
    }
}

// Private type creation functions
const $$createType0 = InterpolationResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = InterpolationInput.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = LoadPrbResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = PrbFileInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = PrbValidRange.createFrom;
