// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class RecordingStatus {
    /**
     * Creates a new RecordingStatus instance.
     * @param {Partial<RecordingStatus>} [$$source = {}] - The source object to create the RecordingStatus.
     */
    constructor($$source = {}) {
        if (!("recording" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["recording"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["outputDir"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecordingStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingStatus(/** @type {Partial<RecordingStatus>} */($$parsedSource));
    }
}
