// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChannelConfig {
    /**
     * Creates a new ChannelConfig instance.
     * @param {Partial<ChannelConfig>} [$$source = {}] - The source object to create the ChannelConfig.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("unit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }
        if (!("precision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["precision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rangeMin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rangeMax"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["tareOffset"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelConfig(/** @type {Partial<ChannelConfig>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Connection = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ConnectionDisconnected: "Disconnected",
    ConnectionConnected: "Connected",
    ConnectionAcquiring: "Acquiring",
    ConnectionError: "Error",
};

export class DaqT1603HardwareConfig {
    /**
     * Creates a new DaqT1603HardwareConfig instance.
     * @param {Partial<DaqT1603HardwareConfig>} [$$source = {}] - The source object to create the DaqT1603HardwareConfig.
     */
    constructor($$source = {}) {
        if (!("thermocoupleTypes" in $$source)) {
            /**
             * 16 chars, one per channel
             * @member
             * @type {string}
             */
            this["thermocoupleTypes"] = "";
        }
        if (!("channelMask" in $$source)) {
            /**
             * hex 0000-FFFF
             * @member
             * @type {string}
             */
            this["channelMask"] = "";
        }
        if (!("samplingRate" in $$source)) {
            /**
             * Hz
             * @member
             * @type {number}
             */
            this["samplingRate"] = 0;
        }
        if (!("binaryFormat" in $$source)) {
            /**
             * true=float32 LE, false=ASCII text
             * @member
             * @type {boolean}
             */
            this["binaryFormat"] = false;
        }
        if (!("averageCount" in $$source)) {
            /**
             * 1-100
             * @member
             * @type {number}
             */
            this["averageCount"] = 0;
        }
        if (!("triggerMode" in $$source)) {
            /**
             * 0=software, 2=hardware
             * @member
             * @type {number}
             */
            this["triggerMode"] = 0;
        }
        if (!("triggerEdge" in $$source)) {
            /**
             * 0=rising, 1=falling, 2=change
             * @member
             * @type {number}
             */
            this["triggerEdge"] = 0;
        }
        if (!("triggerCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["triggerCount"] = 0;
        }
        if (!("showTimestamp" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showTimestamp"] = false;
        }
        if (!("showSequence" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showSequence"] = false;
        }
        if (!("openCircuitCheck" in $$source)) {
            /**
             * hex mask
             * @member
             * @type {string}
             */
            this["openCircuitCheck"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DaqT1603HardwareConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DaqT1603HardwareConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DaqT1603HardwareConfig(/** @type {Partial<DaqT1603HardwareConfig>} */($$parsedSource));
    }
}

export class DataPayload {
    /**
     * Creates a new DataPayload instance.
     * @param {Partial<DataPayload>} [$$source = {}] - The source object to create the DataPayload.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 设备帧内时间戳（毫秒），仅 DAQ-P-1604 开启设备时间戳时有效
             * @member
             * @type {number | undefined}
             */
            this["deviceTimestamp"] = undefined;
        }
        if (!("channels" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["channels"] = [];
        }
        if (!("channelIndices" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["channelIndices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataPayload}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField3_0($$parsedSource["channels"]);
        }
        if ("channelIndices" in $$parsedSource) {
            $$parsedSource["channelIndices"] = $$createField4_0($$parsedSource["channelIndices"]);
        }
        return new DataPayload(/** @type {Partial<DataPayload>} */($$parsedSource));
    }
}

/**
 * Profile 设备配置档案
 * 注意：硬件特定的默认值生成已迁移到 adapters/config 包，
 * core 层只保留类型定义，不包含基础设施知识
 */
export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {Type}
             */
            this["type"] = Type.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["transport"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serialPort"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["baudRate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["autoConnect"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["macAddress"] = undefined;
        }
        if (!("samplingRate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["samplingRate"] = 0;
        }
        if (!("channels" in $$source)) {
            /**
             * @member
             * @type {ChannelConfig[]}
             */
            this["channels"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["daqP1604UseDeviceTimestamp"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DaqT1603HardwareConfig | undefined}
             */
            this["daqT1603Config"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType3;
        const $$createField13_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField11_0($$parsedSource["channels"]);
        }
        if ("daqT1603Config" in $$parsedSource) {
            $$parsedSource["daqT1603Config"] = $$createField13_0($$parsedSource["daqT1603Config"]);
        }
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

export class ScanResult {
    /**
     * Creates a new ScanResult instance.
     * @param {Partial<ScanResult>} [$$source = {}] - The source object to create the ScanResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {Type}
             */
            this["type"] = Type.$zero;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["macAddress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["serialNumber"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["firmwareVersion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["model"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["subnetMask"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["gateway"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ipMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["tcpConnected"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["ipAssigned"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult(/** @type {Partial<ScanResult>} */($$parsedSource));
    }
}

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {Type}
             */
            this["type"] = Type.$zero;
        }
        if (!("connection" in $$source)) {
            /**
             * @member
             * @type {Connection}
             */
            this["connection"] = Connection.$zero;
        }
        if (!("acquiring" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["acquiring"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Type = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DeviceSimulated: "SIMULATED",
    DeviceDAQP1604: "DAQ-P-1604",
    DeviceDaqT1603: "DAQ-T-1603",
    DeviceDAQP1604Pre: "DAQ-P-1604Pre",
    DeviceWTNPXI: "WTN_PXI",
    DeviceDSA3217: "DSA3217",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ChannelConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = DaqT1603HardwareConfig.createFrom;
