// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails 应用的主结构体
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../../services/api-go/internal/adapters/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as calibration$0 from "../../../services/api-go/internal/core/calibration/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../../../services/api-go/internal/core/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as motion$0 from "../../../services/api-go/internal/core/motion/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../../../services/api-go/internal/core/report/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../../../services/api-go/internal/core/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../../../services/api-go/pkg/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as usecase$0 from "../../../services/api-go/pkg/usecase/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function CalibrationCollect() {
    return $Call.ByID(1263729613).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<[types$0.CalibrationStatus, boolean]>}
 */
export function CalibrationGetResult(taskID) {
    return $Call.ByID(1069794330, taskID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function CalibrationPause() {
    return $Call.ByID(303414833).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function CalibrationResume() {
    return $Call.ByID(2873409142).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} taskID
 * @param {string} savePath
 * @returns {$CancellablePromise<$models.FileResponse>}
 */
export function CalibrationSaveCsv(taskID, savePath) {
    return $Call.ByID(3285892140, taskID, savePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * CalibrationStart 启动校准任务。
 * 
 * 参数使用 pkg/types 暴露的 CalibrationConfigDTO（adapters/config 层 DTO 的公共别名），
 * 而非直接用 core 的 calibration.Config。原因：Wails v3 运行时用 encoding/json 把前端
 * JS 对象反序列化进方法参数，而前端发送的探针通道是嵌套 channel 格式，core 层禁止自带
 * UnmarshalJSON（零容忍约束）。DTO 用普通 struct tag 同时接收扁平与嵌套两种 shape，
 * ToCore 再转换为 core 层的 calibration.Config。
 * backend 是独立 Go module，不能直接 import internal/adapters/config（Go internal 规则），
 * 故通过 pkg/types 的类型别名 facade 访问 DTO。
 * @param {types$0.CalibrationConfigDTO} dto
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function CalibrationStart(dto) {
    return $Call.ByID(1191713363, dto).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<types$0.CalibrationStatus>}
 */
export function CalibrationStatus() {
    return $Call.ByID(1679554403).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function CalibrationStop() {
    return $Call.ByID(1820335137).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function ConfigLoad(key) {
    return $Call.ByID(4036805801, key).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} key
 * @param {string} configJSON
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function ConfigSave(key, configJSON) {
    return $Call.ByID(3616860424, key, configJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceConnect(id) {
    return $Call.ByID(467684417, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceDeleteProfile(id) {
    return $Call.ByID(3041094335, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceDisconnect(id) {
    return $Call.ByID(4073046387, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<[types$0.DeviceDataPayload, boolean]>}
 */
export function DeviceGetLatestData(deviceID) {
    return $Call.ByID(2960982356, deviceID).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType4($result[0]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<types$0.DeviceProfile[]>}
 */
export function DeviceGetProfiles() {
    return $Call.ByID(3176966537).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function DeviceGetPublishRate() {
    return $Call.ByID(4242821940);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<[types$0.DeviceStatus, boolean]>}
 */
export function DeviceGetStatus(id) {
    return $Call.ByID(505357305, id).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType7($result[0]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<types$0.DeviceScanResult[]>}
 */
export function DeviceScanDevices() {
    return $Call.ByID(2121538939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {number} hz
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceSetPublishRate(hz) {
    return $Call.ByID(2224503720, hz).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceStartAcquisition(id) {
    return $Call.ByID(1400011690, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceStopAcquisition(id) {
    return $Call.ByID(2818062620, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeviceSubscribeStream 前端调用此方法来订阅/取消订阅某个设备的采集数据流
 * @param {string} deviceID
 * @param {boolean} subscribe
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceSubscribeStream(deviceID, subscribe) {
    return $Call.ByID(2983701763, deviceID, subscribe).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {types$0.DeviceProfile} profile
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function DeviceUpsertProfile(profile) {
    return $Call.ByID(143177095, profile).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetStartupMode 获取当前应用启动模式
 * 返回 "normal"（主窗口）或 "motion"（运动控制器独立窗口）
 * @returns {$CancellablePromise<string>}
 */
export function GetStartupMode() {
    return $Call.ByID(2226262397);
}

/**
 * GetVersion 获取版本信息
 * @returns {$CancellablePromise<$models.VersionInfo>}
 */
export function GetVersion() {
    return $Call.ByID(3296880891).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionConnect(id) {
    return $Call.ByID(2510366129, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} position
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionDefinePosition(id, axis, position) {
    return $Call.ByID(497334069, id, axis, position).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionDeleteProfile(id) {
    return $Call.ByID(873705263, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionDisconnect(id) {
    return $Call.ByID(1903075, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionEmergencyStop(id) {
    return $Call.ByID(1066284354, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function MotionGetProfiles() {
    return $Call.ByID(2161921305);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function MotionGetStatus() {
    return $Call.ByID(1912023177);
}

/**
 * @param {string} id
 * @param {string} axis
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionHome(id, axis) {
    return $Call.ByID(1675669398, id, axis).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} velocity
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionJog(id, axis, velocity) {
    return $Call.ByID(410413035, id, axis, velocity).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} delta
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionMoveBy(id, axis, delta) {
    return $Call.ByID(1714497865, id, axis, delta).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} position
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionMoveTo(id, axis, position) {
    return $Call.ByID(1481288485, id, axis, position).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionResetEmergencyStop(id) {
    return $Call.ByID(2617554069, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @param {string} axis
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionStop(id, axis) {
    return $Call.ByID(879336269, id, axis).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {types$0.MotionControllerProfile} profile
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function MotionUpsertProfile(profile) {
    return $Call.ByID(3674031671, profile).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * OpenMotionWindow 启动运动控制器独立窗口（独立进程）
 * 通过重新启动当前可执行文件并传入 --motion-only 参数实现真正的独立窗口
 * 使用互斥锁防止重复启动
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function OpenMotionWindow() {
    return $Call.ByID(1226492473).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PickDirectory 选择目录对话框
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory() {
    return $Call.ByID(1466965977);
}

/**
 * @param {string} title
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string>}
 */
export function PickFile(title, filters) {
    return $Call.ByID(2802102684, title, filters);
}

/**
 * @param {string} title
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string[]>}
 */
export function PickFiles(title, filters) {
    return $Call.ByID(3680770877, title, filters).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * PickSaveFile 保存文件对话框，返回用户选择的完整文件路径。
 * title 为对话框标题，defaultFilename 为默认文件名，filters 为文件扩展名过滤。
 * @param {string} title
 * @param {string} defaultFilename
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string>}
 */
export function PickSaveFile(title, defaultFilename, filters) {
    return $Call.ByID(4198979769, title, defaultFilename, filters);
}

/**
 * @returns {$CancellablePromise<usecase$0.ReportStatus>}
 */
export function ReportGetStatus() {
    return $Call.ByID(2294408909).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * ResolvePath 将相对路径解析为绝对路径
 * @param {string} p
 * @returns {$CancellablePromise<string>}
 */
export function ResolvePath(p) {
    return $Call.ByID(1607542154, p);
}

/**
 * SetParentPID 仅 ModeMotion 子进程使用：在 Wails Run 之前把父进程 PID 注入。
 * Startup 时启动 watchdog 协程，发现父进程不存在则触发自杀，
 * 解决任务管理器强杀父进程导致子进程成为孤儿的问题。
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function SetParentPID(pid) {
    return $Call.ByID(3324065922, pid);
}

/**
 * @returns {$CancellablePromise<usecase$0.StorageRecordingStatus>}
 */
export function StorageGetStatus() {
    return $Call.ByID(2686181578).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} outputDir
 * @param {string} filePrefix
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function StorageStartRecording(outputDir, filePrefix) {
    return $Call.ByID(3910835915, outputDir, filePrefix).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.GenericResponse>}
 */
export function StorageStopRecording() {
    return $Call.ByID(3573275583).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.GenericResponse.createFrom;
const $$createType1 = calibration$0.Status.createFrom;
const $$createType2 = $models.FileResponse.createFrom;
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = device$0.DataPayload.createFrom;
const $$createType5 = device$0.Profile.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = device$0.Status.createFrom;
const $$createType8 = device$0.ScanResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.VersionInfo.createFrom;
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = report$0.ReportStatus.createFrom;
const $$createType13 = storage$0.RecordingStatus.createFrom;
