// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../../../../shared.local/device-sdk/go/motion/core/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MotionConnect(id) {
    return $Call.ByID(1576153243, id);
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} position
 * @returns {$CancellablePromise<void>}
 */
export function MotionDefinePosition(id, axis, position) {
    return $Call.ByID(2662841399, id, axis, position);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MotionDeleteProfile(id) {
    return $Call.ByID(419122225, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MotionDisconnect(id) {
    return $Call.ByID(2513300797, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MotionEmergencyStop(id) {
    return $Call.ByID(1610424016, id);
}

/**
 * MotionGetProfiles 保留为 Wails 绑定兼容。
 * 实际数据也可通过 HTTP API (http://localhost:16888/api/motion/profiles) 获取。
 * @returns {$CancellablePromise<string>}
 */
export function MotionGetProfiles() {
    return $Call.ByID(522504723);
}

/**
 * MotionGetStatus 保留为 Wails 绑定兼容。
 * 实际数据也可通过 HTTP API (http://localhost:16888/api/motion/status) 获取。
 * @returns {$CancellablePromise<string>}
 */
export function MotionGetStatus() {
    return $Call.ByID(283444131);
}

/**
 * @param {string} id
 * @param {string} axis
 * @returns {$CancellablePromise<void>}
 */
export function MotionHome(id, axis) {
    return $Call.ByID(3306724060, id, axis);
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} velocity
 * @returns {$CancellablePromise<void>}
 */
export function MotionJog(id, axis, velocity) {
    return $Call.ByID(369619085, id, axis, velocity);
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} delta
 * @returns {$CancellablePromise<void>}
 */
export function MotionMoveBy(id, axis, delta) {
    return $Call.ByID(1269546151, id, axis, delta);
}

/**
 * @param {string} id
 * @param {string} axis
 * @param {number} position
 * @returns {$CancellablePromise<void>}
 */
export function MotionMoveTo(id, axis, position) {
    return $Call.ByID(969814675, id, axis, position);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function MotionResetEmergencyStop(id) {
    return $Call.ByID(405946503, id);
}

/**
 * @param {string} id
 * @param {string} axis
 * @returns {$CancellablePromise<void>}
 */
export function MotionStop(id, axis) {
    return $Call.ByID(3790960975, id, axis);
}

/**
 * @param {core$0.MotionControllerProfile} profile
 * @returns {$CancellablePromise<void>}
 */
export function MotionUpsertProfile(profile) {
    return $Call.ByID(1435748521, profile);
}
