// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileFilter {
    /**
     * Creates a new FileFilter instance.
     * @param {Partial<FileFilter>} [$$source = {}] - The source object to create the FileFilter.
     */
    constructor($$source = {}) {
        if (!("DisplayName" in $$source)) {
            /**
             * Filter information EG: "Image Files (*.jpg, *.png)"
             * @member
             * @type {string}
             */
            this["DisplayName"] = "";
        }
        if (!("Pattern" in $$source)) {
            /**
             * semicolon separated list of extensions, EG: "*.jpg;*.png"
             * @member
             * @type {string}
             */
            this["Pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilter(/** @type {Partial<FileFilter>} */($$parsedSource));
    }
}
