// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchCalculate(arg1) {
  return window['go']['backend']['App']['BatchCalculate'](arg1);
}

export function Calculate(arg1) {
  return window['go']['backend']['App']['Calculate'](arg1);
}

export function GetMachRange() {
  return window['go']['backend']['App']['GetMachRange']();
}

export function GetPrbFiles() {
  return window['go']['backend']['App']['GetPrbFiles']();
}

export function ImportCsvData() {
  return window['go']['backend']['App']['ImportCsvData']();
}

export function IsPrbLoaded() {
  return window['go']['backend']['App']['IsPrbLoaded']();
}

export function LoadPrbFiles() {
  return window['go']['backend']['App']['LoadPrbFiles']();
}

export function OpenHelpDoc() {
  return window['go']['backend']['App']['OpenHelpDoc']();
}
