// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App Wails 后端应用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyConfig 应用设备配置
 */
export function ApplyConfig(id: string, cfg: core$0.P1604Config): $CancellablePromise<void> {
    return $Call.ByID(1103525981, id, cfg);
}

/**
 * Connect 连接设备
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(1874137165, id);
}

/**
 * DeleteProfile 删除设备配置
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3821717283, id);
}

/**
 * Disconnect 断开设备
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(1820062543, id);
}

/**
 * EmitDeviceState 发送设备状态变更事件到前端
 */
export function EmitDeviceState(id: string, state: core$0.DeviceState): $CancellablePromise<void> {
    return $Call.ByID(3055282493, id, state);
}

/**
 * EmitLog 发送日志事件
 */
export function EmitLog(entry: $models.LogEvent): $CancellablePromise<void> {
    return $Call.ByID(2095923884, entry);
}

/**
 * GetLatestSnapshot 获取指定设备的最新快照（前端 500ms 轮询调用）
 * 替代原有的 daq:payload Event.Emit，避免 Wails v3 Event.Emit 触发
 * WebView2 同步 ExecuteScript 调用导致的 GUI 线程阻塞和 Eval errors。
 */
export function GetLatestSnapshot(id: string): $CancellablePromise<[core$0.PressureSnapshot, boolean]> {
    return $Call.ByID(309705564, id).then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    });
}

/**
 * GetLatestSnapshots 批量获取所有设备的最新快照（减少前端轮询次数）
 */
export function GetLatestSnapshots(): $CancellablePromise<{ [key: string]: core$0.PressureSnapshot }> {
    return $Call.ByID(1045801725).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLogFileState 获取日志文件写入状态
 */
export function GetLogFileState(): $CancellablePromise<$models.LogFileState> {
    return $Call.ByID(3149353174).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetProfiles 获取所有设备配置
 */
export function GetProfiles(): $CancellablePromise<core$0.PressureProfile[]> {
    return $Call.ByID(3630054453).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetRecordingStatus 获取录制状态
 */
export function GetRecordingStatus(): $CancellablePromise<core$0.RecordingSession> {
    return $Call.ByID(83586696).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetStatus 获取设备状态
 */
export function GetStatus(id: string): $CancellablePromise<[core$0.DeviceState, boolean]> {
    return $Call.ByID(787649133, id).then(($result: any) => {
        $result[0] = $$createType6($result[0]);
        return $result;
    });
}

/**
 * PickDirectory 选择目录对话框
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(2399822983);
}

/**
 * ScanDevices 扫描设备
 */
export function ScanDevices(): $CancellablePromise<core$0.ScanResult[]> {
    return $Call.ByID(394973111).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * StartAcquisition 启动采集
 */
export function StartAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(1774163878, id);
}

/**
 * StartLogFile 开始将日志写入文件
 */
export function StartLogFile(outputDir: string, prefix: string): $CancellablePromise<void> {
    return $Call.ByID(2635563173, outputDir, prefix);
}

/**
 * StartRecording 开始录制
 */
export function StartRecording(outputDir: string, filePrefix: string): $CancellablePromise<void> {
    return $Call.ByID(2702497030, outputDir, filePrefix);
}

/**
 * StartRecordingWithConfig 开始录制（带完整滚动与停止条件配置）
 */
export function StartRecordingWithConfig(outputDir: string, filePrefix: string, rotation: core$0.FileRotation, stopCond: core$0.StopConditions): $CancellablePromise<void> {
    return $Call.ByID(4084016268, outputDir, filePrefix, rotation, stopCond);
}

/**
 * StopAcquisition 停止采集
 */
export function StopAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(497632576, id);
}

/**
 * StopLogFile 停止日志文件写入
 */
export function StopLogFile(): $CancellablePromise<void> {
    return $Call.ByID(3132261939);
}

/**
 * StopRecording 停止录制
 */
export function StopRecording(): $CancellablePromise<void> {
    return $Call.ByID(1653520);
}

/**
 * UpsertProfile 保存设备配置
 */
export function UpsertProfile(profile: core$0.PressureProfile): $CancellablePromise<void> {
    return $Call.ByID(3103337011, profile);
}

// Private type creation functions
const $$createType0 = core$0.PressureSnapshot.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $models.LogFileState.createFrom;
const $$createType3 = core$0.PressureProfile.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = core$0.RecordingSession.createFrom;
const $$createType6 = core$0.DeviceState.createFrom;
const $$createType7 = core$0.ScanResult.createFrom;
const $$createType8 = $Create.Array($$createType7);
