// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogEvent 日志事件
 */
export class LogEvent {
    "level": string;
    "category": string;
    "deviceId"?: string;
    "source": string;
    "message": string;
    "detail"?: string;
    "timestamp": number;

    /** Creates a new LogEvent instance. */
    constructor($$source: Partial<LogEvent> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEvent($$parsedSource as Partial<LogEvent>);
    }
}

/**
 * LogFileState 日志文件写入状态
 */
export class LogFileState {
    "active": boolean;
    "outputDir"?: string;

    /** Creates a new LogFileState instance. */
    constructor($$source: Partial<LogFileState> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFileState instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFileState($$parsedSource as Partial<LogFileState>);
    }
}
