// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ChannelConfig 通道配置
 */
export class ChannelConfig {
    "index": number;
    "name": string;
    "enabled": boolean;
    "unit": string;
    "color": string;
    "precision": number;
    "rangeMin"?: number;
    "rangeMax"?: number;

    /** Creates a new ChannelConfig instance. */
    constructor($$source: Partial<ChannelConfig> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("precision" in $$source)) {
            this["precision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelConfig($$parsedSource as Partial<ChannelConfig>);
    }
}

/**
 * DeviceState 设备运行状态
 */
export class DeviceState {
    "profile": PressureProfile;
    "status": DeviceStatus;
    "statusText": string;
    "error": string;
    "connectedAt": number;
    "acquiringAt": number;
    "samplingRate": number;

    /** Creates a new DeviceState instance. */
    constructor($$source: Partial<DeviceState> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = (new PressureProfile());
        }
        if (!("status" in $$source)) {
            this["status"] = DeviceStatus.$zero;
        }
        if (!("statusText" in $$source)) {
            this["statusText"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("connectedAt" in $$source)) {
            this["connectedAt"] = 0;
        }
        if (!("acquiringAt" in $$source)) {
            this["acquiringAt"] = 0;
        }
        if (!("samplingRate" in $$source)) {
            this["samplingRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceState {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        return new DeviceState($$parsedSource as Partial<DeviceState>);
    }
}

/**
 * DeviceStatus 设备连接状态
 */
export enum DeviceStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusDisconnected = 0,
    StatusConnected = 1,
    StatusAcquiring = 2,
    StatusError = 3,
};

/**
 * P1604Config DAQ-P-1604 设备硬件配置
 */
export class P1604Config {
    /**
     * 采样周期（毫秒），最小 10ms，由采样频率换算得出
     */
    "samplingRate": number;

    /**
     * 压力单位：psi, Pa, kPa, MPa, kgf/cm²
     */
    "unit": string;

    /**
     * 启动时自动连接
     */
    "autoConnect": boolean;

    /**
     * 全局默认显示精度（小数位数 0-6），单通道精度未设置时回退到此值
     */
    "precision": number;

    /** Creates a new P1604Config instance. */
    constructor($$source: Partial<P1604Config> = {}) {
        if (!("samplingRate" in $$source)) {
            this["samplingRate"] = 0;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("autoConnect" in $$source)) {
            this["autoConnect"] = false;
        }
        if (!("precision" in $$source)) {
            this["precision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new P1604Config instance from a string or object.
     */
    static createFrom($$source: any = {}): P1604Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new P1604Config($$parsedSource as Partial<P1604Config>);
    }
}

/**
 * PressureProfile 压力采集设备配置档案
 */
export class PressureProfile {
    "id": string;
    "name": string;
    "address": string;
    "port": number;
    "samplingRate": number;
    "channels": ChannelConfig[];
    "p1604Config": P1604Config;
    "createdAt"?: number;

    /** Creates a new PressureProfile instance. */
    constructor($$source: Partial<PressureProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("samplingRate" in $$source)) {
            this["samplingRate"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("p1604Config" in $$source)) {
            this["p1604Config"] = (new P1604Config());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PressureProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): PressureProfile {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField5_0($$parsedSource["channels"]);
        }
        if ("p1604Config" in $$parsedSource) {
            $$parsedSource["p1604Config"] = $$createField6_0($$parsedSource["p1604Config"]);
        }
        return new PressureProfile($$parsedSource as Partial<PressureProfile>);
    }
}

/**
 * RecordingSession 录制会话信息
 */
export class RecordingSession {
    "id": string;
    "outputDir": string;
    "filePrefix": string;
    "startTimeMs": number;
    "snapshotCount": number;
    "status": RecordingStatus;

    /** Creates a new RecordingSession instance. */
    constructor($$source: Partial<RecordingSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("filePrefix" in $$source)) {
            this["filePrefix"] = "";
        }
        if (!("startTimeMs" in $$source)) {
            this["startTimeMs"] = 0;
        }
        if (!("snapshotCount" in $$source)) {
            this["snapshotCount"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = RecordingStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingSession instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingSession($$parsedSource as Partial<RecordingSession>);
    }
}

/**
 * RecordingStatus 录制状态
 */
export enum RecordingStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    RecordingIdle = 0,
    RecordingActive = 1,
};

/**
 * ScanResult 设备扫描结果
 */
export class ScanResult {
    "id": string;
    "name": string;
    "address": string;
    "port": number;
    "macAddress"?: string;
    "serialNumber"?: string;
    "firmwareVersion"?: string;

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

// Private type creation functions
const $$createType0 = PressureProfile.createFrom;
const $$createType1 = ChannelConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = P1604Config.createFrom;
