// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as calibration$0 from "../../core/calibration/models.js";

/**
 * CalibrationConfigDTO 是校准配置在框架边界（HTTP / Wails）的传输对象。
 * 
 * 为什么需要 DTO：
 * core 层禁止做字节级 I/O（见 CLAUDE.md 零容忍约束），因此 calibration.Config
 * 不再自带 UnmarshalJSON。但前端 ProbeChannelConfig 使用嵌套结构
 * { channel: { deviceId, channelIndex } }，而后端/旧调用方使用扁平结构
 * { deviceId, channelIndex }。DTO 用普通 struct tag 同时声明两种字段，
 * 让 encoding/json 的默认解码器就能同时接收两种 shape，无需自定义 UnmarshalJSON。
 * 
 * ProbeChannelDTO 同时携带：
 *   - 扁平字段 DeviceID/ChannelIndex（兼容旧后端 shape）
 *   - 嵌套字段 Channel *calibration.ChannelRef（兼容前端 shape）
 * 
 * 在 ToCore 中，若 Channel 非空则用嵌套值覆盖扁平值，与原 ProbeChannel.UnmarshalJSON 语义一致。
 */
export class CalibrationConfigDTO {
    /**
     * Creates a new CalibrationConfigDTO instance.
     * @param {Partial<CalibrationConfigDTO>} [$$source = {}] - The source object to create the CalibrationConfigDTO.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("channels" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["channels"] = [];
        }
        if (!("pressurePoints" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["pressurePoints"] = [];
        }
        if (!("averageSamples" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["averageSamples"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProbeChannelDTO[] | undefined}
             */
            this["probeChannels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {calibration$0.CalPoint[] | undefined}
             */
            this["points"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["samplesPerPoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["dwellTimeMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stopOnError"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["savePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {calibration$0.MotionAxisConfig[] | undefined}
             */
            this["motionAxes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {calibration$0.SphereTankGateConfig | null | undefined}
             */
            this["sphereTankGate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {calibration$0.AcquisitionSamplingConfig | null | undefined}
             */
            this["acquisitionSampling"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {calibration$0.TotalTemperatureConfig | null | undefined}
             */
            this["totalTemperatureConfig"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalibrationConfigDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalibrationConfigDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        const $$createField13_0 = $$createType7;
        const $$createField14_0 = $$createType9;
        const $$createField15_0 = $$createType11;
        const $$createField16_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField3_0($$parsedSource["channels"]);
        }
        if ("pressurePoints" in $$parsedSource) {
            $$parsedSource["pressurePoints"] = $$createField4_0($$parsedSource["pressurePoints"]);
        }
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField6_0($$parsedSource["probeChannels"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField7_0($$parsedSource["points"]);
        }
        if ("motionAxes" in $$parsedSource) {
            $$parsedSource["motionAxes"] = $$createField13_0($$parsedSource["motionAxes"]);
        }
        if ("sphereTankGate" in $$parsedSource) {
            $$parsedSource["sphereTankGate"] = $$createField14_0($$parsedSource["sphereTankGate"]);
        }
        if ("acquisitionSampling" in $$parsedSource) {
            $$parsedSource["acquisitionSampling"] = $$createField15_0($$parsedSource["acquisitionSampling"]);
        }
        if ("totalTemperatureConfig" in $$parsedSource) {
            $$parsedSource["totalTemperatureConfig"] = $$createField16_0($$parsedSource["totalTemperatureConfig"]);
        }
        return new CalibrationConfigDTO(/** @type {Partial<CalibrationConfigDTO>} */($$parsedSource));
    }
}

/**
 * ProbeChannelDTO 是探针通道在框架边界的传输对象，同时支持扁平与嵌套两种 JSON shape。
 */
export class ProbeChannelDTO {
    /**
     * Creates a new ProbeChannelDTO instance.
     * @param {Partial<ProbeChannelDTO>} [$$source = {}] - The source object to create the ProbeChannelDTO.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("channelIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["channelIndex"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {calibration$0.ChannelRef | null | undefined}
             */
            this["channel"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeChannelDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeChannelDTO}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channel" in $$parsedSource) {
            $$parsedSource["channel"] = $$createField5_0($$parsedSource["channel"]);
        }
        return new ProbeChannelDTO(/** @type {Partial<ProbeChannelDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = ProbeChannelDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = calibration$0.CalPoint.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = calibration$0.MotionAxisConfig.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = calibration$0.SphereTankGateConfig.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = calibration$0.AcquisitionSamplingConfig.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = calibration$0.TotalTemperatureConfig.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = calibration$0.ChannelRef.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
