package interpolation

import (
	"fmt"
	"math"
	"strconv"
	"testing"
)

func TestInnerKaKb(t *testing.T) {
	// p1..p6 = {0,0,0,50,25,75} -> pAvg=25; p7=125 -> denom=100.
	// cpa=0.5, cpb=0.25, cpc=0.75; ka=1/sqrt(3), kb=-0.5/3.
	in := InterpolationInput{P1: 0, P2: 0, P3: 0, P4: 50, P5: 25, P6: 75, P7: 125}
	ka, kb, err := innerKaKb(in)
	if err != nil {
		t.Fatalf("innerKaKb: %v", err)
	}
	if want := 1 / math.Sqrt(3); math.Abs(ka-want) > 1e-15 {
		t.Errorf("ka = %v, want %v", ka, want)
	}
	if want := -0.5 / 3; math.Abs(kb-want) > 1e-15 {
		t.Errorf("kb = %v, want %v", kb, want)
	}
}

func TestInnerKaKbGuard(t *testing.T) {
	// p7 == pAverage triggers the 1e-12 denominator guard (spec section 3.2).
	in := InterpolationInput{P1: 10, P2: 10, P3: 10, P4: 10, P5: 10, P6: 10, P7: 10}
	if _, _, err := innerKaKb(in); err == nil {
		t.Fatal("expected denominator guard error")
	}
}

// linearInnerMap is a strictly linear (a,b) -> (ka,kb) map with sheared
// cells, plus linear cpt/cps fields. Under a linear map every cell is a
// parallelogram, so the edge-equation inversion is exact, and the bilinear
// stage reproduces linear fields exactly.
func linearInnerMap(a, b float64) (ka, kb, cpt, cps float64) {
	ka = 0.05*a + 0.01*b
	kb = -0.02*a + 0.04*b
	cpt = 1.1 + 0.03*a - 0.02*b
	cps = -0.5 - 0.01*a + 0.04*b
	return ka, kb, cpt, cps
}

// buildInnerTestInterpolator loads a synthetic inner grid whose ka/kb/cpt/cps
// are generated by f, via the real loader (geometry precompute included).
// Coefficients are written with shortest round-trip formatting so the stored
// grid values are bit-identical to evaluating f at the grid coordinates.
func buildInnerTestInterpolator(t *testing.T, f func(a, b float64) (ka, kb, cpt, cps float64)) *SevenHolePrbInterpolator {
	t.Helper()
	lines := []string{"ka kb cpt cps a b"}
	for ia := 0; ia < innerGridSide; ia++ {
		for ib := 0; ib < innerGridSide; ib++ {
			a := innerGridMin + gridStep*float64(ia)
			b := innerGridMin + gridStep*float64(ib)
			ka, kb, cpt, cps := f(a, b)
			lines = append(lines, fmt.Sprintf("%s %s %s %s %.6f %.6f",
				strconv.FormatFloat(ka, 'g', -1, 64),
				strconv.FormatFloat(kb, 'g', -1, 64),
				strconv.FormatFloat(cpt, 'g', -1, 64),
				strconv.FormatFloat(cps, 'g', -1, 64),
				a, b))
		}
	}
	p := NewSevenHolePrbInterpolator()
	if err := p.LoadInnerPrbLines(lines, "synthetic-7.prb"); err != nil {
		t.Fatalf("load synthetic inner grid: %v", err)
	}
	return p
}

// TestInnerZoneLinearMap checks stage A (a,b inversion) and stage B (cpt/cps
// bilinear) over interior and near-boundary points of a linear map:
// inversion must be exact to float noise. Points strictly inside the grid
// are used: exact max-edge grid-line hits are float-fragile in the
// edge-equation location in BOTH implementations (identical formulas), so
// boundary routing is pinned separately by TestInnerZoneBoundaryRouting.
func TestInnerZoneLinearMap(t *testing.T) {
	p := buildInnerTestInterpolator(t, linearInnerMap)
	points := []struct{ a, b float64 }{
		{0, 0}, {12.3, -7.8}, {-22.9, 17.6}, {29.9, -29.9},
		{29.9999, 0}, {15, 29.9999}, {29.9999, 29.9999},
	}
	for _, pt := range points {
		ka, kb, _, _ := linearInnerMap(pt.a, pt.b)
		got, inZone, err := p.innerZoneInterpolate(ka, kb)
		if err != nil {
			t.Fatalf("(%v,%v): %v", pt.a, pt.b, err)
		}
		if !inZone {
			t.Fatalf("(%v,%v): expected inner zone", pt.a, pt.b)
		}
		if math.Abs(got.a-pt.a) > 1e-9 || math.Abs(got.b-pt.b) > 1e-9 {
			t.Errorf("(%v,%v): inversion = (%v,%v)", pt.a, pt.b, got.a, got.b)
		}
		_, _, wantCpt, wantCps := linearInnerMap(pt.a, pt.b)
		if math.Abs(got.cpt-wantCpt) > 1e-9 || math.Abs(got.cps-wantCps) > 1e-9 {
			t.Errorf("(%v,%v): cpt/cps = (%v,%v), want (%v,%v)", pt.a, pt.b, got.cpt, got.cps, wantCpt, wantCps)
		}
	}
}

// TestInnerZoneOutside checks the not-inner signal (no error) for a point far
// outside the boundary polygon (Python cal_ab falls through to big angle).
func TestInnerZoneOutside(t *testing.T) {
	p := buildInnerTestInterpolator(t, linearInnerMap)
	if _, inZone, err := p.innerZoneInterpolate(100, 100); err != nil || inZone {
		t.Errorf("outside point: inZone=%v err=%v, want false,nil", inZone, err)
	}
}

// TestInnerCellLo pins the little_cptcps_square cell-location branch logic
// (SKILL.md section 2.4), including truncation toward zero and the |v|=30
// boundaries.
func TestInnerCellLo(t *testing.T) {
	tests := []struct{ v, want float64 }{
		{0, 0}, {2.5, 0}, {-2.5, -5}, {5, 5}, {-5, -10},
		{7.5, 5}, {-7.5, -10}, {12.3, 10}, {-12.3, -15},
		{29.999, 25}, {-29.999, -30}, {30, 25}, {-30, -30},
	}
	for _, tc := range tests {
		if got := innerCellLo(tc.v); got != tc.want {
			t.Errorf("innerCellLo(%v) = %v, want %v", tc.v, got, tc.want)
		}
	}
}

// TestInnerBilinearLinearField checks stage B alone: a linear cpt/cps field
// must be reproduced exactly (0-magnitude error) at arbitrary points.
func TestInnerBilinearLinearField(t *testing.T) {
	p := buildInnerTestInterpolator(t, linearInnerMap)
	for _, pt := range []struct{ a, b float64 }{
		{1.234, -4.321}, {-17.77, 23.45}, {0.001, -0.001}, {29.999, 29.999},
	} {
		cpt, cps := p.innerBilinearCptCps(pt.a, pt.b)
		_, _, wantCpt, wantCps := linearInnerMap(pt.a, pt.b)
		if math.Abs(cpt-wantCpt) > 1e-9 || math.Abs(cps-wantCps) > 1e-9 {
			t.Errorf("(%v,%v): cpt/cps = (%v,%v), want (%v,%v)", pt.a, pt.b, cpt, cps, wantCpt, wantCps)
		}
	}
}

// TestBuildInnerPolygonGeometry checks the boundary polygon construction
// (Python little_create_line): 48 unique vertices after corner dedup, in
// bottom -> right -> top(reversed) -> left(reversed) ring order.
func TestBuildInnerPolygonGeometry(t *testing.T) {
	p := buildInnerTestInterpolator(t, linearInnerMap)
	if len(p.innerPolygon) != 48 {
		t.Fatalf("polygon vertex count = %d, want 48", len(p.innerPolygon))
	}
	ka, kb, _, _ := linearInnerMap(-30, -30)
	if p.innerPolygon[0] != (point2D{ka, kb}) {
		t.Errorf("polygon[0] = %v, want bottom-left (%v,%v)", p.innerPolygon[0], ka, kb)
	}
	ka, kb, _, _ = linearInnerMap(30, -30)
	if p.innerPolygon[12] != (point2D{ka, kb}) {
		t.Errorf("polygon[12] = %v, want bottom-right (%v,%v)", p.innerPolygon[12], ka, kb)
	}
	ka, kb, _, _ = linearInnerMap(30, 30)
	if p.innerPolygon[24] != (point2D{ka, kb}) {
		t.Errorf("polygon[24] = %v, want top-right (%v,%v)", p.innerPolygon[24], ka, kb)
	}
	ka, kb, _, _ = linearInnerMap(-30, 30)
	if p.innerPolygon[36] != (point2D{ka, kb}) {
		t.Errorf("polygon[36] = %v, want top-left (%v,%v)", p.innerPolygon[36], ka, kb)
	}
}

// TestInnerZoneBoundaryRouting pins the routing contract: the pipeline
// enters the inner zone iff the boundary-polygon sign is >= 0 (inner zone
// tried first, Python cal_ab branch order). Strictly interior and exterior
// offsets are used because exact grid-line hits are float-fragile in both
// implementations; exact-edge sign semantics are covered with exact integer
// coordinates in geometry_test.go, and parity on real data is enforced by
// the golden tests.
func TestInnerZoneBoundaryRouting(t *testing.T) {
	p := buildInnerTestInterpolator(t, linearInnerMap)
	inside := []struct{ a, b float64 }{
		{29.9999, 12.5}, {29.9999, -12.5}, {0, 29.9999}, {12.5, 29.9999}, {29.9999, 29.9999},
	}
	for _, tc := range inside {
		ka, kb, _, _ := linearInnerMap(tc.a, tc.b)
		if sign := pointInPolygon(ka, kb, p.innerPolygon); sign < 0 {
			t.Errorf("(%v,%v): polygon sign = %d, want >= 0", tc.a, tc.b, sign)
		}
		got, inZone, err := p.innerZoneInterpolate(ka, kb)
		if err != nil || !inZone {
			t.Errorf("(%v,%v): inZone=%v err=%v, want inner zone", tc.a, tc.b, inZone, err)
			continue
		}
		if math.Abs(got.a-tc.a) > 1e-9 || math.Abs(got.b-tc.b) > 1e-9 {
			t.Errorf("(%v,%v): inversion = (%v,%v)", tc.a, tc.b, got.a, got.b)
		}
	}
	outside := []struct{ a, b float64 }{
		{30.0001, 0}, {0, 30.0001}, {-30.0001, 0}, {0, -30.0001}, {31, 31},
	}
	for _, tc := range outside {
		ka, kb, _, _ := linearInnerMap(tc.a, tc.b)
		if sign := pointInPolygon(ka, kb, p.innerPolygon); sign >= 0 {
			t.Errorf("(%v,%v): polygon sign = %d, want < 0", tc.a, tc.b, sign)
		}
		if _, inZone, err := p.innerZoneInterpolate(ka, kb); err != nil || inZone {
			t.Errorf("(%v,%v): inZone=%v err=%v, want fall-through", tc.a, tc.b, inZone, err)
		}
	}
}

// TestInnerZoneBoundarySignZero verifies the boundary path end to end: a
// point exactly on a horizontal (in ka/kb) polygon edge gets sign 0 and is
// routed into the inner zone (Python treats sign 0 as inside, cal_ab branch
// order). Here kb has no a-term, so the b=-30 polygon edge is horizontal in
// the (ka,kb) plane and the comparisons are exact.
func TestInnerZoneBoundarySignZero(t *testing.T) {
	horizontalEdgeMap := func(a, b float64) (ka, kb, cpt, cps float64) {
		ka = 0.05*a + 0.01*b
		kb = 0.04 * b
		cpt = 1.1 + 0.03*a - 0.02*b
		cps = -0.5 - 0.01*a + 0.04*b
		return ka, kb, cpt, cps
	}
	p := buildInnerTestInterpolator(t, horizontalEdgeMap)
	ka, kb, _, _ := horizontalEdgeMap(0, -30)
	if sign := pointInPolygon(ka, kb, p.innerPolygon); sign != 0 {
		t.Fatalf("polygon sign = %d, want 0 (boundary)", sign)
	}
	got, inZone, err := p.innerZoneInterpolate(ka, kb)
	if err != nil || !inZone {
		t.Fatalf("inZone=%v err=%v, want inner zone", inZone, err)
	}
	if math.Abs(got.a-0) > 1e-9 || math.Abs(got.b-(-30)) > 1e-9 {
		t.Errorf("inversion = (%v,%v), want (0,-30)", got.a, got.b)
	}
}
