package interpolation

import (
	"fmt"
	"math"
	"strconv"
	"testing"
)

func TestMaxPressureHoles(t *testing.T) {
	tests := []struct {
		name          string
		p             [6]float64
		first, second int
	}{
		{"distinct", [6]float64{1, 5, 3, 2, 6, 4}, 5, 2},
		{"first hole max", [6]float64{9, 1, 2, 3, 4, 5}, 1, 6},
		{"last hole max", [6]float64{1, 2, 3, 4, 5, 9}, 6, 5},
		{"negative pressures", [6]float64{-5, -1, -9, -2, -3, -4}, 2, 4},
		// Tie at the top: Python picks the first key for both first and
		// second (sorted values equal), so first==second.
		{"tie at top", [6]float64{7, 7, 1, 2, 3, 4}, 1, 1},
		// Tie below the top: second is the first hole with the 2nd value.
		{"tie at second", [6]float64{9, 5, 5, 1, 2, 3}, 1, 2},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			in := InterpolationInput{
				P1: tc.p[0], P2: tc.p[1], P3: tc.p[2],
				P4: tc.p[3], P5: tc.p[4], P6: tc.p[5],
			}
			first, second := maxPressureHoles(in)
			if first != tc.first || second != tc.second {
				t.Errorf("maxPressureHoles = (%d,%d), want (%d,%d)", first, second, tc.first, tc.second)
			}
		})
	}
}

func TestOuterKaKb(t *testing.T) {
	// Sector 1: pc=P1, pl=P6, pr=P2. pc=100, pl=pr=0, p7=20 ->
	// denom=100, ka=0.8, kb=0.
	in := InterpolationInput{P1: 100, P7: 20}
	ka, kb, err := outerKaKb(in, 1)
	if err != nil {
		t.Fatalf("outerKaKb: %v", err)
	}
	if math.Abs(ka-0.8) > 1e-15 || math.Abs(kb-0) > 1e-15 {
		t.Errorf("sector1 (ka,kb) = (%v,%v), want (0.8,0)", ka, kb)
	}

	// Sector 3: pc=P3=50, pl=P2=10, pr=P4=20, p7=5 ->
	// denom=35, ka=45/35=9/7, kb=-10/35=-2/7.
	in = InterpolationInput{P2: 10, P3: 50, P4: 20, P7: 5}
	ka, kb, err = outerKaKb(in, 3)
	if err != nil {
		t.Fatalf("outerKaKb: %v", err)
	}
	if math.Abs(ka-9.0/7.0) > 1e-15 || math.Abs(kb-(-2.0/7.0)) > 1e-15 {
		t.Errorf("sector3 (ka,kb) = (%v,%v), want (%v,%v)", ka, kb, 9.0/7.0, -2.0/7.0)
	}

	// Sector 6 wrap: pr=P1.
	in = InterpolationInput{P1: 8, P5: 2, P6: 40, P7: 4}
	ka, kb, err = outerKaKb(in, 6)
	if err != nil {
		t.Fatalf("outerKaKb: %v", err)
	}
	// denom = 40 - (2+8)/2 = 35; ka = (40-4)/35 = 36/35; kb = (2-8)/35 = -6/35.
	if math.Abs(ka-36.0/35.0) > 1e-15 || math.Abs(kb-(-6.0/35.0)) > 1e-15 {
		t.Errorf("sector6 (ka,kb) = (%v,%v), want (%v,%v)", ka, kb, 36.0/35.0, -6.0/35.0)
	}
}

func TestOuterKaKbGuard(t *testing.T) {
	// pc == (pl+pr)/2 triggers the 1e-12 denominator guard (spec section 3.2).
	in := InterpolationInput{P1: 10, P2: 10, P6: 10, P7: 99}
	if _, _, err := outerKaKb(in, 1); err == nil {
		t.Fatal("expected denominator guard error")
	}
}

// linearOuterMap is a linear (theta, phiSigned) -> (ka,kb) map with sheared
// cells plus linear cpt/cps fields. phiSigned is the normalized phi mapped
// into the signed range around the sector center, so the map is continuous
// across the 0/360 wrap for sector 1. The kb slope sign matches the real
// calibration orientation: kb decreases as phi increases (Python big_cal_ab
// containment requires the phi-high edge to sit at the low-kb side).
func linearOuterMap(center float64) func(theta, phi float64) (ka, kb, cpt, cps float64) {
	return func(theta, phi float64) (ka, kb, cpt, cps float64) {
		s := phi - center
		if s > 180 {
			s -= 360
		} else if s < -180 {
			s += 360
		}
		ka = 0.03*theta + 0.01*s
		kb = -0.01*theta - 0.02*s
		cpt = 0.8 + 0.01*theta - 0.005*s
		cps = -0.3 + 0.004*theta + 0.002*s
		return ka, kb, cpt, cps
	}
}

// buildOuterTestInterpolator loads a synthetic outer sector grid generated by
// f via the real loader (geometry precompute included). thetaCount=4（默认）
// 以保持与历史黄金样本一致；如需其他维度请用 buildOuterTestInterpolatorTheta。
func buildOuterTestInterpolator(t *testing.T, sector int, f func(theta, phi float64) (ka, kb, cpt, cps float64)) *SevenHolePrbInterpolator {
	t.Helper()
	return buildOuterTestInterpolatorTheta(t, sector, defaultTestThetaCount, f)
}

// buildOuterTestInterpolatorTheta 用指定 thetaCount 构造合成外区网格。
func buildOuterTestInterpolatorTheta(t *testing.T, sector, thetaCount int, f func(theta, phi float64) (ka, kb, cpt, cps float64)) *SevenHolePrbInterpolator {
	t.Helper()
	center := float64(sector-1) * 60
	lines := []string{"ka kb cpt cps a b"}
	for k := 0; k < outerPhiCount; k++ {
		b := normalize360(center + 30 - gridStep*float64(k))
		for it := 0; it < thetaCount; it++ {
			theta := outerThetaMin + gridStep*float64(it)
			ka, kb, cpt, cps := f(theta, b)
			lines = append(lines, fmt.Sprintf("%s %s %s %s %.6f %.6f",
				strconv.FormatFloat(ka, 'g', -1, 64),
				strconv.FormatFloat(kb, 'g', -1, 64),
				strconv.FormatFloat(cpt, 'g', -1, 64),
				strconv.FormatFloat(cps, 'g', -1, 64),
				theta, b))
		}
	}
	p := NewSevenHolePrbInterpolator()
	if err := p.LoadOuterPrbLines(sector, lines, fmt.Sprintf("synthetic-%d.prb", sector)); err != nil {
		t.Fatalf("load synthetic outer grid: %v", err)
	}
	return p
}

// TestOuterZoneLinearMap checks the full outer pipeline (polygon test,
// (theta,phi) inversion, cpt/cps bilinear) over interior points of sector 3
// (no wrap) with a linear map: everything must be exact to float noise.
func TestOuterZoneLinearMap(t *testing.T) {
	const sector = 3
	f := linearOuterMap(120)
	p := buildOuterTestInterpolator(t, sector, f)
	points := []struct{ theta, phi float64 }{
		{37.5, 120}, {32.5, 91.3}, {44.9, 148.7}, {30.1, 119.9},
		{44.99, 90.01}, {40, 135.5},
	}
	for _, pt := range points {
		ka, kb, _, _ := f(pt.theta, pt.phi)
		got, hit, err := p.outerZoneTrySector(sector, ka, kb)
		if err != nil {
			t.Fatalf("(%v,%v): %v", pt.theta, pt.phi, err)
		}
		if !hit {
			t.Fatalf("(%v,%v): expected sector hit", pt.theta, pt.phi)
		}
		if math.Abs(got.a-pt.theta) > 1e-9 || math.Abs(got.b-pt.phi) > 1e-9 {
			t.Errorf("(%v,%v): inversion = (%v,%v)", pt.theta, pt.phi, got.a, got.b)
		}
		_, _, wantCpt, wantCps := f(pt.theta, pt.phi)
		if math.Abs(got.cpt-wantCpt) > 1e-9 || math.Abs(got.cps-wantCps) > 1e-9 {
			t.Errorf("(%v,%v): cpt/cps = (%v,%v), want (%v,%v)", pt.theta, pt.phi, got.cpt, got.cps, wantCpt, wantCps)
		}
	}
}

// TestOuterZoneSector1Wrap checks the wrap-around sector 1: a point with
// signed phi < 0 (stored phi > 330) must invert and interpolate exactly.
// The inverted b for the cell across the 0/360 boundary comes out negative
// (b1=0 minus offset), mirroring Python big_cal_ab.
func TestOuterZoneSector1Wrap(t *testing.T) {
	const sector = 1
	f := linearOuterMap(0)
	p := buildOuterTestInterpolator(t, sector, f)
	// phi=347.7 (signed -12.3): inside the (345,350) cell.
	ka, kb, _, _ := f(37.5, 347.7)
	got, hit, err := p.outerZoneTrySector(sector, ka, kb)
	if err != nil || !hit {
		t.Fatalf("wrap point: hit=%v err=%v", hit, err)
	}
	if math.Abs(got.a-37.5) > 1e-9 || math.Abs(got.b-347.7) > 1e-9 {
		t.Errorf("inversion = (%v,%v), want (37.5,347.7)", got.a, got.b)
	}
	_, _, wantCpt, wantCps := f(37.5, 347.7)
	if math.Abs(got.cpt-wantCpt) > 1e-9 || math.Abs(got.cps-wantCps) > 1e-9 {
		t.Errorf("cpt/cps = (%v,%v), want (%v,%v)", got.cpt, got.cps, wantCpt, wantCps)
	}

	// phi=357.5 (signed -2.5): inside the cell across 0/360; the inverted b
	// is negative (Python behavior) and the (0,5) cell extrapolates the
	// linear field exactly.
	ka, kb, _, _ = f(40, 357.5)
	got, hit, err = p.outerZoneTrySector(sector, ka, kb)
	if err != nil || !hit {
		t.Fatalf("cross-zero point: hit=%v err=%v", hit, err)
	}
	if math.Abs(got.a-40) > 1e-9 || math.Abs(got.b-(-2.5)) > 1e-9 {
		t.Errorf("inversion = (%v,%v), want (40,-2.5)", got.a, got.b)
	}
	_, _, wantCpt, wantCps = f(40, 357.5)
	if math.Abs(got.cpt-wantCpt) > 1e-9 || math.Abs(got.cps-wantCps) > 1e-9 {
		t.Errorf("cpt/cps = (%v,%v), want (%v,%v)", got.cpt, got.cps, wantCpt, wantCps)
	}
}

// TestOuterZonePolygonMiss verifies the not-hit signal (no error) for a point
// outside the sector polygon, which drives the second-candidate fallback in
// Python cal_ab.
func TestOuterZonePolygonMiss(t *testing.T) {
	p := buildOuterTestInterpolator(t, 3, linearOuterMap(120))
	if _, hit, err := p.outerZoneTrySector(3, 100, 100); err != nil || hit {
		t.Errorf("outside point: hit=%v err=%v, want false,nil", hit, err)
	}
}

// TestOuterZoneSectorFallback exercises the Python first/second candidate
// logic at the pipeline level: (ka,kb) computed for sector 2's map must miss
// sector 1's polygon (far shifted) and hit sector 2's.
func TestOuterZoneSectorFallback(t *testing.T) {
	farMap := func(theta, phi float64) (ka, kb, cpt, cps float64) {
		ka, kb, cpt, cps = linearOuterMap(0)(theta, phi)
		return ka + 100, kb + 100, cpt, cps // shift sector-1 cells far away
	}
	p := NewSevenHolePrbInterpolator()
	for sector, f := range map[int]func(float64, float64) (float64, float64, float64, float64){
		1: farMap,
		2: linearOuterMap(60),
	} {
		center := float64(sector-1) * 60
		lines := []string{"ka kb cpt cps a b"}
		for k := 0; k < outerPhiCount; k++ {
			b := normalize360(center + 30 - gridStep*float64(k))
			for it := 0; it < defaultTestThetaCount; it++ {
				theta := outerThetaMin + gridStep*float64(it)
				ka, kb, cpt, cps := f(theta, b)
				lines = append(lines, fmt.Sprintf("%s %s %s %s %.6f %.6f",
					strconv.FormatFloat(ka, 'g', -1, 64),
					strconv.FormatFloat(kb, 'g', -1, 64),
					strconv.FormatFloat(cpt, 'g', -1, 64),
					strconv.FormatFloat(cps, 'g', -1, 64),
					theta, b))
			}
		}
		if err := p.LoadOuterPrbLines(sector, lines, fmt.Sprintf("synthetic-%d.prb", sector)); err != nil {
			t.Fatalf("load sector %d: %v", sector, err)
		}
	}
	// Point from sector-2's map at (theta=38, phi=66).
	ka, kb, _, _ := linearOuterMap(60)(38, 66)
	if _, hit, err := p.outerZoneTrySector(1, ka, kb); err != nil || hit {
		t.Errorf("first candidate: hit=%v err=%v, want miss", hit, err)
	}
	got, hit, err := p.outerZoneTrySector(2, ka, kb)
	if err != nil || !hit {
		t.Fatalf("second candidate: hit=%v err=%v, want hit", hit, err)
	}
	if math.Abs(got.a-38) > 1e-9 || math.Abs(got.b-66) > 1e-9 {
		t.Errorf("inversion = (%v,%v), want (38,66)", got.a, got.b)
	}
}

// TestOuterCellLocation pins the big_cptcps_square cell branches (SKILL.md
// section 3.5), including the a=thetaMax and phi 355->0 wrap special cases.
// thetaCount=4 时 thetaMax=45；动态化后 outerThetaCellLo 接收 thetaCount 参数。
func TestOuterCellLocation(t *testing.T) {
	const thetaCount = 4
	thetaCases := []struct{ v, want float64 }{
		{30, 30}, {37.5, 35}, {44.999, 40}, {45, 40},
	}
	for _, tc := range thetaCases {
		if got := outerThetaCellLo(tc.v, thetaCount); got != tc.want {
			t.Errorf("outerThetaCellLo(%v, %d) = %v, want %v", tc.v, thetaCount, got, tc.want)
		}
	}
	// 动态：thetaCount=7 时 thetaMax=60，a=60 应收缩到 [55,60]
	t.Run("thetaCount=7 dynamic", func(t *testing.T) {
		const tc7 = 7
		cases := []struct{ v, want float64 }{
			{30, 30}, {55, 55}, {59.999, 55}, {60, 55}, // a=60 (thetaMax) → cell [55,60]
		}
		for _, tc := range cases {
			if got := outerThetaCellLo(tc.v, tc7); got != tc.want {
				t.Errorf("outerThetaCellLo(%v, %d) = %v, want %v", tc.v, tc7, got, tc.want)
			}
		}
	})
	phiCases := []struct {
		v      float64
		lo, hi float64
	}{
		{347.7, 345, 350},
		{354.999, 350, 355},
		{355, 355, 0},   // l==71 wrap branch
		{357.5, 355, 0}, // l==71 wrap branch
		{-2.5, 0, 5},    // negative b truncation (sector-1 wrap square)
		{0, 0, 5},
	}
	for _, tc := range phiCases {
		lo, hi := outerPhiCell(tc.v)
		if lo != tc.lo || hi != tc.hi {
			t.Errorf("outerPhiCell(%v) = (%v,%v), want (%v,%v)", tc.v, lo, hi, tc.lo, tc.hi)
		}
	}
}

// TestCoordTransform checks the (theta,phi)->(alpha,beta) transform against
// hand-computed values (SKILL.md section 3.7), including the load-bearing
// minus sign and the degenerate branch.
func TestCoordTransform(t *testing.T) {
	tests := []struct {
		theta, phi  float64
		alpha, beta float64
	}{
		{30, 0, 0, 30},   // phi=0: pure beta
		{30, 90, -30, 0}, // phi=90: pure -alpha
		{45, 90, -45, 0},
		{30, 270, 30, 0}, // phi=270: positive alpha (minus sign!)
		{45, 270, 45, 0},
		{30, 180, 0, -30}, // phi=180: negative beta
		{45, 45, -math.Atan(math.Tan(math.Pi/4)*math.Sin(math.Pi/4)) * 180 / math.Pi,
			math.Atan(math.Tan(math.Pi/4)*math.Cos(math.Pi/4)) * 180 / math.Pi},
		{89.5, 123, -89.5, 123}, // degenerate branch
		{90, 45, -90, 45},       // degenerate branch
	}
	for _, tc := range tests {
		alpha, beta := convertThetaPhiToAlphaBeta(tc.theta, tc.phi)
		if math.Abs(alpha-tc.alpha) > 1e-12 || math.Abs(beta-tc.beta) > 1e-12 {
			t.Errorf("convertThetaPhiToAlphaBeta(%v,%v) = (%v,%v), want (%v,%v)",
				tc.theta, tc.phi, alpha, beta, tc.alpha, tc.beta)
		}
	}
}

// TestOuterGeometryCounts checks polygon vertex counts and the quad-cell
// construction per sector. thetaCount=4 时 polygon=30 顶点（4+13+4+13 去重）、
// quad=36（3×12）；动态化后 quad 数量随 thetaCount 线性变化。
func TestOuterGeometryCounts(t *testing.T) {
	p := buildOuterTestInterpolator(t, 2, linearOuterMap(60))
	if got := len(p.outerPolygons[1]); got != 30 {
		t.Errorf("polygon vertex count = %d, want 30", got)
	}
	if got := len(p.outerQuads[1]); got != 36 {
		t.Errorf("quad count = %d, want 36", got)
	}
}

// TestOuterGeometryCounts_DynamicThetaCount 验证动态 thetaCount 下 quad 数量
// 随之变化：thetaCount=7 → quad=6×12=72；thetaCount=2 → quad=1×12=12。
func TestOuterGeometryCounts_DynamicThetaCount(t *testing.T) {
	for _, tc := range []struct {
		name       string
		thetaCount int
		wantQuads  int
	}{
		{"thetaCount=2 (minimum)", 2, 12},  // (2-1)×(13-1)=12
		{"thetaCount=4 (legacy)", 4, 36},   // (4-1)×12=36
		{"thetaCount=7 (extended)", 7, 72}, // (7-1)×12=72
		{"thetaCount=10 (wide)", 10, 108},  // (10-1)×12=108
	} {
		t.Run(tc.name, func(t *testing.T) {
			p := buildOuterTestInterpolatorTheta(t, 3, tc.thetaCount, linearOuterMap(120))
			if got := len(p.outerQuads[2]); got != tc.wantQuads {
				t.Errorf("quad count = %d, want %d", got, tc.wantQuads)
			}
		})
	}
}
