// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    AcquisitionSamplingConfig,
    CalPoint,
    ChannelRef,
    MotionAxisConfig,
    SphereTankGateConfig,
    State,
    Status,
    TemperatureStabilityConfig,
    TotalTemperatureConfig
} from "./models.js";

import * as $models from "./models.js";

/**
 * DataPoint 通用校准数据点接口
 * @typedef {$models.DataPoint} DataPoint
 */
