// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AcquisitionSamplingConfig 采集采样参数配置
 */
export class AcquisitionSamplingConfig {
    /**
     * Creates a new AcquisitionSamplingConfig instance.
     * @param {Partial<AcquisitionSamplingConfig>} [$$source = {}] - The source object to create the AcquisitionSamplingConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 批量读取超时（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchTimeoutMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 批量读取轮询间隔（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchPollIntervalMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 数据最大年龄（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchMaxAgeMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AcquisitionSamplingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AcquisitionSamplingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AcquisitionSamplingConfig(/** @type {Partial<AcquisitionSamplingConfig>} */($$parsedSource));
    }
}

/**
 * CalPoint 校准测点定义
 */
export class CalPoint {
    /**
     * Creates a new CalPoint instance.
     * @param {Partial<CalPoint>} [$$source = {}] - The source object to create the CalPoint.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("coordinates" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["coordinates"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalPoint}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coordinates" in $$parsedSource) {
            $$parsedSource["coordinates"] = $$createField1_0($$parsedSource["coordinates"]);
        }
        return new CalPoint(/** @type {Partial<CalPoint>} */($$parsedSource));
    }
}

/**
 * ChannelRef 通道引用
 */
export class ChannelRef {
    /**
     * Creates a new ChannelRef instance.
     * @param {Partial<ChannelRef>} [$$source = {}] - The source object to create the ChannelRef.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("channelIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["channelIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelRef(/** @type {Partial<ChannelRef>} */($$parsedSource));
    }
}

/**
 * Config 校准任务通用配置
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("channels" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["channels"] = [];
        }
        if (!("pressurePoints" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["pressurePoints"] = [];
        }
        if (!("averageSamples" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["averageSamples"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProbeChannel[] | undefined}
             */
            this["probeChannels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CalPoint[] | undefined}
             */
            this["points"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["samplesPerPoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["dwellTimeMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stopOnError"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * 校准任务名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 数据保存路径
             * @member
             * @type {string | undefined}
             */
            this["savePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 运动轴配置
             * @member
             * @type {MotionAxisConfig[] | undefined}
             */
            this["motionAxes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 球罐闸门配置
             * @member
             * @type {SphereTankGateConfig | null | undefined}
             */
            this["sphereTankGate"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 采集采样配置
             * @member
             * @type {AcquisitionSamplingConfig | null | undefined}
             */
            this["acquisitionSampling"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 总温校准专用配置
             * @member
             * @type {TotalTemperatureConfig | null | undefined}
             */
            this["totalTemperatureConfig"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        const $$createField13_0 = $$createType8;
        const $$createField14_0 = $$createType10;
        const $$createField15_0 = $$createType12;
        const $$createField16_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField3_0($$parsedSource["channels"]);
        }
        if ("pressurePoints" in $$parsedSource) {
            $$parsedSource["pressurePoints"] = $$createField4_0($$parsedSource["pressurePoints"]);
        }
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField6_0($$parsedSource["probeChannels"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField7_0($$parsedSource["points"]);
        }
        if ("motionAxes" in $$parsedSource) {
            $$parsedSource["motionAxes"] = $$createField13_0($$parsedSource["motionAxes"]);
        }
        if ("sphereTankGate" in $$parsedSource) {
            $$parsedSource["sphereTankGate"] = $$createField14_0($$parsedSource["sphereTankGate"]);
        }
        if ("acquisitionSampling" in $$parsedSource) {
            $$parsedSource["acquisitionSampling"] = $$createField15_0($$parsedSource["acquisitionSampling"]);
        }
        if ("totalTemperatureConfig" in $$parsedSource) {
            $$parsedSource["totalTemperatureConfig"] = $$createField16_0($$parsedSource["totalTemperatureConfig"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * DataPoint 通用校准数据点接口
 * @typedef {any} DataPoint
 */

/**
 * MotionAxisConfig 校准运动轴配置，将逻辑轴名映射到物理运动控制器
 */
export class MotionAxisConfig {
    /**
     * Creates a new MotionAxisConfig instance.
     * @param {Partial<MotionAxisConfig>} [$$source = {}] - The source object to create the MotionAxisConfig.
     */
    constructor($$source = {}) {
        if (!("controllerId" in $$source)) {
            /**
             * 运动控制器ID
             * @member
             * @type {string}
             */
            this["controllerId"] = "";
        }
        if (!("axis" in $$source)) {
            /**
             * 轴名称（如 "x", "y", "z"）
             * @member
             * @type {string}
             */
            this["axis"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 逻辑轴名（如 "α", "β", "θ"）
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionAxisConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionAxisConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotionAxisConfig(/** @type {Partial<MotionAxisConfig>} */($$parsedSource));
    }
}

/**
 * ProbeChannel 探针通道配置，将逻辑角色映射到物理通道
 */
export class ProbeChannel {
    /**
     * Creates a new ProbeChannel instance.
     * @param {Partial<ProbeChannel>} [$$source = {}] - The source object to create the ProbeChannel.
     */
    constructor($$source = {}) {
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("channelIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["channelIndex"] = 0;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeChannel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeChannel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeChannel(/** @type {Partial<ProbeChannel>} */($$parsedSource));
    }
}

/**
 * SphereTankGateConfig 球罐闸门判定配置
 */
export class SphereTankGateConfig {
    /**
     * Creates a new SphereTankGateConfig instance.
     * @param {Partial<SphereTankGateConfig>} [$$source = {}] - The source object to create the SphereTankGateConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * 是否启用球罐判定
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("waitTimeSec" in $$source)) {
            /**
             * 等待稳定时间（秒）
             * @member
             * @type {number}
             */
            this["waitTimeSec"] = 0;
        }
        if (!("stableTimeChannel" in $$source)) {
            /**
             * 稳定时间通道引用
             * @member
             * @type {ChannelRef}
             */
            this["stableTimeChannel"] = (new ChannelRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SphereTankGateConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SphereTankGateConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stableTimeChannel" in $$parsedSource) {
            $$parsedSource["stableTimeChannel"] = $$createField2_0($$parsedSource["stableTimeChannel"]);
        }
        return new SphereTankGateConfig(/** @type {Partial<SphereTankGateConfig>} */($$parsedSource));
    }
}

/**
 * State 表示校准任务的状态
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateIdle: "idle",
    StateRunning: "running",
    StatePaused: "paused",
    StateStopped: "stopped",
    StateError: "error",
    StateCompleted: "completed",
};

/**
 * Status 校准任务状态
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("currentPoint" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentPoint"] = 0;
        }
        if (!("totalPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalPoints"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("completedPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedPoints"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * 百分比 0-100
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["startTime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DataPoint[] | undefined}
             */
            this["dataPoints"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dataPoints" in $$parsedSource) {
            $$parsedSource["dataPoints"] = $$createField9_0($$parsedSource["dataPoints"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * TemperatureStabilityConfig 温度稳定性检测配置
 */
export class TemperatureStabilityConfig {
    /**
     * Creates a new TemperatureStabilityConfig instance.
     * @param {Partial<TemperatureStabilityConfig>} [$$source = {}] - The source object to create the TemperatureStabilityConfig.
     */
    constructor($$source = {}) {
        if (!("sampleCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sampleCount"] = 0;
        }
        if (!("sampleInterval" in $$source)) {
            /**
             * 毫秒
             * @member
             * @type {number}
             */
            this["sampleInterval"] = 0;
        }
        if (!("maxStdDev" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxStdDev"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemperatureStabilityConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemperatureStabilityConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemperatureStabilityConfig(/** @type {Partial<TemperatureStabilityConfig>} */($$parsedSource));
    }
}

/**
 * TotalTemperatureConfig 总温校准专用配置
 */
export class TotalTemperatureConfig {
    /**
     * Creates a new TotalTemperatureConfig instance.
     * @param {Partial<TotalTemperatureConfig>} [$$source = {}] - The source object to create the TotalTemperatureConfig.
     */
    constructor($$source = {}) {
        if (!("probeChannels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ChannelRef }}
             */
            this["probeChannels"] = {};
        }
        if (!("targetMachNumbers" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["targetMachNumbers"] = [];
        }
        if (!("machTolerance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machTolerance"] = 0;
        }
        if (!("stabilityCriteria" in $$source)) {
            /**
             * @member
             * @type {TemperatureStabilityConfig}
             */
            this["stabilityCriteria"] = (new TemperatureStabilityConfig());
        }
        if (!("samplesPerPoint" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["samplesPerPoint"] = 0;
        }
        if (!("sampleInterval" in $$source)) {
            /**
             * 毫秒
             * @member
             * @type {number}
             */
            this["sampleInterval"] = 0;
        }
        if (!("enableFitting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableFitting"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TotalTemperatureConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TotalTemperatureConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType2;
        const $$createField3_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField0_0($$parsedSource["probeChannels"]);
        }
        if ("targetMachNumbers" in $$parsedSource) {
            $$parsedSource["targetMachNumbers"] = $$createField1_0($$parsedSource["targetMachNumbers"]);
        }
        if ("stabilityCriteria" in $$parsedSource) {
            $$parsedSource["stabilityCriteria"] = $$createField3_0($$parsedSource["stabilityCriteria"]);
        }
        return new TotalTemperatureConfig(/** @type {Partial<TotalTemperatureConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ProbeChannel.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = CalPoint.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = MotionAxisConfig.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = SphereTankGateConfig.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = AcquisitionSamplingConfig.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = TotalTemperatureConfig.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = ChannelRef.createFrom;
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = $Create.Map($Create.Any, $$createType15);
const $$createType18 = TemperatureStabilityConfig.createFrom;
