// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as traversal$0 from "../traversal/models.js";

/**
 * AcquisitionSamplingConfig 采集采样参数配置
 */
export class AcquisitionSamplingConfig {
    /**
     * Creates a new AcquisitionSamplingConfig instance.
     * @param {Partial<AcquisitionSamplingConfig>} [$$source = {}] - The source object to create the AcquisitionSamplingConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 批量读取超时（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchTimeoutMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 批量读取轮询间隔（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchPollIntervalMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 数据最大年龄（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchMaxAgeMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AcquisitionSamplingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AcquisitionSamplingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AcquisitionSamplingConfig(/** @type {Partial<AcquisitionSamplingConfig>} */($$parsedSource));
    }
}

/**
 * CalPoint 校准测点定义
 * 
 * 双坐标模型（七孔探针校准引入，spec §3.4）：
 *   - Coordinates（逻辑坐标）：业务语义角度，用于配置生成、CSV 落盘、系数计算、图表绘制。
 *     内区表示为 (α,β)，外区表示为 (θ,φ)。
 *   - MotionCoordinates（运动坐标）：运动控制器实际下发的目标角度，统一为 (α,β) 双轴。
 *     外区点由 (θ,φ) 按 spec §3.3 正向公式换算（α=-arctan(tanθ×sinφ)，负号必须保留）。
 * 
 * 向后兼容：五孔/三孔/总压/总温等已有模块不填 MotionCoordinates/Region/Sector 时，
 * moveToPoint 默认走 Coordinates 路径（已有行为），新字段 omitempty 不影响序列化结果。
 * 仅 TypeSevenHole 在点位生成阶段（GenerateSevenHolePoints）显式填充双坐标。
 */
export class CalPoint {
    /**
     * Creates a new CalPoint instance.
     * @param {Partial<CalPoint>} [$$source = {}] - The source object to create the CalPoint.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("coordinates" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["coordinates"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * MotionCoordinates 运动坐标（运动控制器下发用，统一为 α-β 双轴）。
             * 为 nil 时 moveToPoint 回退到 Coordinates（向后兼容）。
             * 消费方（moveToPoint 七孔分支）在 Task 10 落地。
             * @member
             * @type {{ [_ in string]?: number } | undefined}
             */
            this["motionCoordinates"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Region 流场分区："inner"（内区，7 区）或 "outer"（外区，1~6 区）。
             * 仅七孔校准填充，其他类型留空。
             * @member
             * @type {string | undefined}
             */
            this["region"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Sector 外区扇区编号 1~6；内区固定 7；其他类型留空（零值）。
             * @member
             * @type {number | undefined}
             */
            this["sector"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalPoint}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coordinates" in $$parsedSource) {
            $$parsedSource["coordinates"] = $$createField1_0($$parsedSource["coordinates"]);
        }
        if ("motionCoordinates" in $$parsedSource) {
            $$parsedSource["motionCoordinates"] = $$createField2_0($$parsedSource["motionCoordinates"]);
        }
        return new CalPoint(/** @type {Partial<CalPoint>} */($$parsedSource));
    }
}

/**
 * ChannelRef 通道引用
 */
export class ChannelRef {
    /**
     * Creates a new ChannelRef instance.
     * @param {Partial<ChannelRef>} [$$source = {}] - The source object to create the ChannelRef.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("channelIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["channelIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelRef(/** @type {Partial<ChannelRef>} */($$parsedSource));
    }
}

/**
 * DataPoint 通用校准数据点接口
 * @typedef {any} DataPoint
 */

/**
 * MotionAxisConfig 校准运动轴配置，将逻辑轴名映射到物理运动控制器
 */
export class MotionAxisConfig {
    /**
     * Creates a new MotionAxisConfig instance.
     * @param {Partial<MotionAxisConfig>} [$$source = {}] - The source object to create the MotionAxisConfig.
     */
    constructor($$source = {}) {
        if (!("controllerId" in $$source)) {
            /**
             * 运动控制器ID
             * @member
             * @type {string}
             */
            this["controllerId"] = "";
        }
        if (!("axis" in $$source)) {
            /**
             * 轴名称（如 "x", "y", "z"）
             * @member
             * @type {string}
             */
            this["axis"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 逻辑轴名（如 "α", "β", "θ"）
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionAxisConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionAxisConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotionAxisConfig(/** @type {Partial<MotionAxisConfig>} */($$parsedSource));
    }
}

/**
 * SevenHoleConfig 七孔校准点位生成配置
 * 
 * 字段语义：
 *   - Mode：校准模式（"full"/"dataset"），决定外区 θ 与 φ 的取值策略
 *   - InnerAlphaMin/Max/Step：内区 α 范围与步长（度），完整/数据集模式都使用此配置
 *   - InnerBetaMin/Max/Step：内区 β 范围与步长（度）
 *   - OuterThetaMin/Max/Step：外区 θ 范围与步长（度），仅完整模式生效；数据集模式忽略并使用硬编码 {30°,35°,40°,45°}
 *   - OuterPhiMin/Max/Step：外区 φ 范围与步长（度），仅完整模式生效；数据集模式按扇区独立配置
 *   - Serpentine：是否启用蛇形走位（true 时奇数行 α/θ 反向）
 * 
 * 推荐默认值（spec §6.2）：内区 [-30°,30°] 步长 5°；外区 θ [30°,60°] 步长 5°、φ [0°,355°] 步长 5°
 */
export class SevenHoleConfig {
    /**
     * Creates a new SevenHoleConfig instance.
     * @param {Partial<SevenHoleConfig>} [$$source = {}] - The source object to create the SevenHoleConfig.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {SevenHoleMode}
             */
            this["mode"] = SevenHoleMode.$zero;
        }
        if (!("innerAlphaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerAlphaMin"] = 0;
        }
        if (!("innerAlphaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerAlphaMax"] = 0;
        }
        if (!("innerAlphaStep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerAlphaStep"] = 0;
        }
        if (!("innerBetaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerBetaMin"] = 0;
        }
        if (!("innerBetaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerBetaMax"] = 0;
        }
        if (!("innerBetaStep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["innerBetaStep"] = 0;
        }
        if (!("outerThetaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outerThetaMin"] = 0;
        }
        if (!("outerThetaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outerThetaMax"] = 0;
        }
        if (!("outerThetaStep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outerThetaStep"] = 0;
        }
        if (!("outerPhiMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outerPhiMin"] = 0;
        }
        if (!("outerPhiMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outerPhiMax"] = 0;
        }
        if (!("outerPhiStep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outerPhiStep"] = 0;
        }
        if (!("serpentine" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["serpentine"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SevenHoleConfig(/** @type {Partial<SevenHoleConfig>} */($$parsedSource));
    }
}

/**
 * SevenHoleMode 七孔校准模式枚举
 * @readonly
 * @enum {string}
 */
export const SevenHoleMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * SevenHoleModeFull 完整模式（产品默认，673 点）
     * 内区 α∈[-30°,30°] 步长 5° × β∈[-30°,30°] 步长 5° = 169 点
     * 外区 θ∈[30°,60°] 步长 5° × φ∈[0°,355°] 步长 5° = 504 点
     */
    SevenHoleModeFull: "full",

    /**
     * SevenHoleModeDataset 数据集模式（验证基准，481 点）
     * 内区 169 点同完整模式
     * 外区 θ∈{30°,35°,40°,45°}（4 个值，不可配置）× 每扇区 φ 跨 60° 步长 5° = 13 点/扇区 × 6 扇区 = 312 点
     * 扇区边界不共享，无需去重（spec §6.2 / Task 6 验收标准）
     */
    SevenHoleModeDataset: "dataset",
};

/**
 * SphereTankGateConfig 球罐闸门判定配置
 */
export class SphereTankGateConfig {
    /**
     * Creates a new SphereTankGateConfig instance.
     * @param {Partial<SphereTankGateConfig>} [$$source = {}] - The source object to create the SphereTankGateConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * 是否启用球罐判定
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("waitTimeSec" in $$source)) {
            /**
             * 等待稳定时间（秒）
             * @member
             * @type {number}
             */
            this["waitTimeSec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 球罐判定总超时（秒），<=0 时使用默认 300 秒
             * @member
             * @type {number | undefined}
             */
            this["timeoutSec"] = undefined;
        }
        if (!("stableTimeChannel" in $$source)) {
            /**
             * 稳定时间通道引用
             * @member
             * @type {ChannelRef}
             */
            this["stableTimeChannel"] = (new ChannelRef());
        }
        if (/** @type {any} */(false)) {
            /**
             * PressureChannel 球罐压力通道引用，仅用于前端实时显示当前球罐压力值，不参与闸门判定逻辑
             * 当配置了有效 DeviceID 时，采集协调器会自动订阅该设备，以便前端能收到实时快照
             * 球罐压力通道引用（仅显示，不参与判定）
             * @member
             * @type {ChannelRef | undefined}
             */
            this["pressureChannel"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SphereTankGateConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SphereTankGateConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stableTimeChannel" in $$parsedSource) {
            $$parsedSource["stableTimeChannel"] = $$createField3_0($$parsedSource["stableTimeChannel"]);
        }
        if ("pressureChannel" in $$parsedSource) {
            $$parsedSource["pressureChannel"] = $$createField4_0($$parsedSource["pressureChannel"]);
        }
        return new SphereTankGateConfig(/** @type {Partial<SphereTankGateConfig>} */($$parsedSource));
    }
}

/**
 * State 表示校准任务的状态
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateIdle: "idle",
    StateRunning: "running",
    StatePaused: "paused",
    StateStopped: "stopped",
    StateError: "error",
    StateCompleted: "completed",
};

/**
 * Status 校准任务状态
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("currentPoint" in $$source)) {
            /**
             * CurrentPoint 当前正在处理的点索引（autoEngine.currentPointIdx，processPoint 循环顶部推进，早于 moveToPoint）。
             * 非"已完成点数"——后者见 CompletedPoints。前端 progressInfo 据此索引查 config.points 得到"目标点"，
             * 让目标角度先于实际角度变化。autoEngine 为 nil（未启动/总温手动模式）时为 0。
             * @member
             * @type {number}
             */
            this["currentPoint"] = 0;
        }
        if (!("totalPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalPoints"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastErrorCode 结构化错误码（新增，运动安全故障时写入对应的 traversal.ErrorCode）。
             * 前端根据此字段展示对应级别的告警（急停类红色 / 普通停止类橙色 / 超时类黄色）。
             * 非运动安全错误（采集失败/保存失败等）写入对应业务错误码或空串。
             * @member
             * @type {string | undefined}
             */
            this["lastErrorCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * MotionSafetyFailure 运动安全故障现场快照。
             * 仅在运动安全故障路径写入，其他错误路径（采集失败/保存失败等）保持 nil。
             * 前端轮询拿到后用于展示故障现场（控制器/轴/verdict/目标/实际/点号），
             * 避免 lastError 字符串正则解析的不稳定。
             * @member
             * @type {traversal$0.MotionSafetyFailure | null | undefined}
             */
            this["motionSafetyFailure"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("completedPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedPoints"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * 百分比 0-100
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["startTime"] = undefined;
        }
        if (!("pausedDurationMs" in $$source)) {
            /**
             * PausedDurationMs 是截至本次状态快照时累计的暂停时长，包含当前尚未结束的暂停段。
             * @member
             * @type {number}
             */
            this["pausedDurationMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DataPoint[] | undefined}
             */
            this["dataPoints"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 当前点采样进度：CurrentSample=当前点已采样本数（1..SamplesPerPoint），0 表示未开始/已完成
             * SamplesPerPoint=当前点总采样数。前端据此显示"当前点采样 3/10"子进度。
             * @member
             * @type {number | undefined}
             */
            this["currentSample"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["samplesPerPoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CurrentRegion/CurrentSector 七孔流场分区当前状态（spec Task 11）。
             * 仅 TypeSevenHole 校准期间有值，供前端 5Hz 轮询 status 时展示"当前区域 inner / 扇区 3"。
             * 其他类型保持零值（omitempty 在 Region="" 时省略字段，Sector=0 时省略字段）。
             * @member
             * @type {string | undefined}
             */
            this["currentRegion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["currentSector"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("motionSafetyFailure" in $$parsedSource) {
            $$parsedSource["motionSafetyFailure"] = $$createField6_0($$parsedSource["motionSafetyFailure"]);
        }
        if ("dataPoints" in $$parsedSource) {
            $$parsedSource["dataPoints"] = $$createField12_0($$parsedSource["dataPoints"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * TemperatureStabilityConfig 温度稳定性检测配置
 */
export class TemperatureStabilityConfig {
    /**
     * Creates a new TemperatureStabilityConfig instance.
     * @param {Partial<TemperatureStabilityConfig>} [$$source = {}] - The source object to create the TemperatureStabilityConfig.
     */
    constructor($$source = {}) {
        if (!("sampleCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sampleCount"] = 0;
        }
        if (!("sampleInterval" in $$source)) {
            /**
             * 毫秒
             * @member
             * @type {number}
             */
            this["sampleInterval"] = 0;
        }
        if (!("maxStdDev" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxStdDev"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemperatureStabilityConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemperatureStabilityConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemperatureStabilityConfig(/** @type {Partial<TemperatureStabilityConfig>} */($$parsedSource));
    }
}

/**
 * TotalTemperatureConfig 总温校准专用配置
 */
export class TotalTemperatureConfig {
    /**
     * Creates a new TotalTemperatureConfig instance.
     * @param {Partial<TotalTemperatureConfig>} [$$source = {}] - The source object to create the TotalTemperatureConfig.
     */
    constructor($$source = {}) {
        if (!("probeChannels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ChannelRef }}
             */
            this["probeChannels"] = {};
        }
        if (!("targetMachNumbers" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["targetMachNumbers"] = [];
        }
        if (!("machTolerance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machTolerance"] = 0;
        }
        if (!("stabilityCriteria" in $$source)) {
            /**
             * @member
             * @type {TemperatureStabilityConfig}
             */
            this["stabilityCriteria"] = (new TemperatureStabilityConfig());
        }
        if (!("samplesPerPoint" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["samplesPerPoint"] = 0;
        }
        if (!("sampleInterval" in $$source)) {
            /**
             * 毫秒
             * @member
             * @type {number}
             */
            this["sampleInterval"] = 0;
        }
        if (!("enableFitting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableFitting"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TotalTemperatureConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TotalTemperatureConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField0_0($$parsedSource["probeChannels"]);
        }
        if ("targetMachNumbers" in $$parsedSource) {
            $$parsedSource["targetMachNumbers"] = $$createField1_0($$parsedSource["targetMachNumbers"]);
        }
        if ("stabilityCriteria" in $$parsedSource) {
            $$parsedSource["stabilityCriteria"] = $$createField3_0($$parsedSource["stabilityCriteria"]);
        }
        return new TotalTemperatureConfig(/** @type {Partial<TotalTemperatureConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ChannelRef.createFrom;
const $$createType2 = traversal$0.MotionSafetyFailure.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $$createType1);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = TemperatureStabilityConfig.createFrom;
