// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as traversal$0 from "../traversal/models.js";

/**
 * AcquisitionSamplingConfig 采集采样参数配置
 */
export class AcquisitionSamplingConfig {
    /**
     * Creates a new AcquisitionSamplingConfig instance.
     * @param {Partial<AcquisitionSamplingConfig>} [$$source = {}] - The source object to create the AcquisitionSamplingConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 批量读取超时（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchTimeoutMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 批量读取轮询间隔（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchPollIntervalMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 数据最大年龄（毫秒）
             * @member
             * @type {number | undefined}
             */
            this["batchMaxAgeMs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AcquisitionSamplingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AcquisitionSamplingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AcquisitionSamplingConfig(/** @type {Partial<AcquisitionSamplingConfig>} */($$parsedSource));
    }
}

/**
 * CalPoint 校准测点定义
 */
export class CalPoint {
    /**
     * Creates a new CalPoint instance.
     * @param {Partial<CalPoint>} [$$source = {}] - The source object to create the CalPoint.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("coordinates" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["coordinates"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalPoint}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("coordinates" in $$parsedSource) {
            $$parsedSource["coordinates"] = $$createField1_0($$parsedSource["coordinates"]);
        }
        return new CalPoint(/** @type {Partial<CalPoint>} */($$parsedSource));
    }
}

/**
 * ChannelRef 通道引用
 */
export class ChannelRef {
    /**
     * Creates a new ChannelRef instance.
     * @param {Partial<ChannelRef>} [$$source = {}] - The source object to create the ChannelRef.
     */
    constructor($$source = {}) {
        if (!("deviceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceId"] = "";
        }
        if (!("channelIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["channelIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelRef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChannelRef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelRef(/** @type {Partial<ChannelRef>} */($$parsedSource));
    }
}

/**
 * DataPoint 通用校准数据点接口
 * @typedef {any} DataPoint
 */

/**
 * MotionAxisConfig 校准运动轴配置，将逻辑轴名映射到物理运动控制器
 */
export class MotionAxisConfig {
    /**
     * Creates a new MotionAxisConfig instance.
     * @param {Partial<MotionAxisConfig>} [$$source = {}] - The source object to create the MotionAxisConfig.
     */
    constructor($$source = {}) {
        if (!("controllerId" in $$source)) {
            /**
             * 运动控制器ID
             * @member
             * @type {string}
             */
            this["controllerId"] = "";
        }
        if (!("axis" in $$source)) {
            /**
             * 轴名称（如 "x", "y", "z"）
             * @member
             * @type {string}
             */
            this["axis"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 逻辑轴名（如 "α", "β", "θ"）
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionAxisConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionAxisConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotionAxisConfig(/** @type {Partial<MotionAxisConfig>} */($$parsedSource));
    }
}

/**
 * SphereTankGateConfig 球罐闸门判定配置
 */
export class SphereTankGateConfig {
    /**
     * Creates a new SphereTankGateConfig instance.
     * @param {Partial<SphereTankGateConfig>} [$$source = {}] - The source object to create the SphereTankGateConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * 是否启用球罐判定
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("waitTimeSec" in $$source)) {
            /**
             * 等待稳定时间（秒）
             * @member
             * @type {number}
             */
            this["waitTimeSec"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 球罐判定总超时（秒），<=0 时使用默认 300 秒
             * @member
             * @type {number | undefined}
             */
            this["timeoutSec"] = undefined;
        }
        if (!("stableTimeChannel" in $$source)) {
            /**
             * 稳定时间通道引用
             * @member
             * @type {ChannelRef}
             */
            this["stableTimeChannel"] = (new ChannelRef());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SphereTankGateConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SphereTankGateConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stableTimeChannel" in $$parsedSource) {
            $$parsedSource["stableTimeChannel"] = $$createField3_0($$parsedSource["stableTimeChannel"]);
        }
        return new SphereTankGateConfig(/** @type {Partial<SphereTankGateConfig>} */($$parsedSource));
    }
}

/**
 * State 表示校准任务的状态
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateIdle: "idle",
    StateRunning: "running",
    StatePaused: "paused",
    StateStopped: "stopped",
    StateError: "error",
    StateCompleted: "completed",
};

/**
 * Status 校准任务状态
 */
export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("currentPoint" in $$source)) {
            /**
             * CurrentPoint 当前正在处理的点索引（autoEngine.currentPointIdx，processPoint 循环顶部推进，早于 moveToPoint）。
             * 非"已完成点数"——后者见 CompletedPoints。前端 progressInfo 据此索引查 config.points 得到"目标点"，
             * 让目标角度先于实际角度变化。autoEngine 为 nil（未启动/总温手动模式）时为 0。
             * @member
             * @type {number}
             */
            this["currentPoint"] = 0;
        }
        if (!("totalPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalPoints"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastErrorCode 结构化错误码（新增，运动安全故障时写入对应的 traversal.ErrorCode）。
             * 前端根据此字段展示对应级别的告警（急停类红色 / 普通停止类橙色 / 超时类黄色）。
             * 非运动安全错误（采集失败/保存失败等）写入对应业务错误码或空串。
             * @member
             * @type {string | undefined}
             */
            this["lastErrorCode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * MotionSafetyFailure 运动安全故障现场快照。
             * 仅在运动安全故障路径写入，其他错误路径（采集失败/保存失败等）保持 nil。
             * 前端轮询拿到后用于展示故障现场（控制器/轴/verdict/目标/实际/点号），
             * 避免 lastError 字符串正则解析的不稳定。
             * @member
             * @type {traversal$0.MotionSafetyFailure | null | undefined}
             */
            this["motionSafetyFailure"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("completedPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["completedPoints"] = 0;
        }
        if (!("progress" in $$source)) {
            /**
             * 百分比 0-100
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["startTime"] = undefined;
        }
        if (!("pausedDurationMs" in $$source)) {
            /**
             * PausedDurationMs 是截至本次状态快照时累计的暂停时长，包含当前尚未结束的暂停段。
             * @member
             * @type {number}
             */
            this["pausedDurationMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DataPoint[] | undefined}
             */
            this["dataPoints"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 当前点采样进度：CurrentSample=当前点已采样本数（1..SamplesPerPoint），0 表示未开始/已完成
             * SamplesPerPoint=当前点总采样数。前端据此显示"当前点采样 3/10"子进度。
             * @member
             * @type {number | undefined}
             */
            this["currentSample"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["samplesPerPoint"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        const $$createField12_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("motionSafetyFailure" in $$parsedSource) {
            $$parsedSource["motionSafetyFailure"] = $$createField6_0($$parsedSource["motionSafetyFailure"]);
        }
        if ("dataPoints" in $$parsedSource) {
            $$parsedSource["dataPoints"] = $$createField12_0($$parsedSource["dataPoints"]);
        }
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

/**
 * TemperatureStabilityConfig 温度稳定性检测配置
 */
export class TemperatureStabilityConfig {
    /**
     * Creates a new TemperatureStabilityConfig instance.
     * @param {Partial<TemperatureStabilityConfig>} [$$source = {}] - The source object to create the TemperatureStabilityConfig.
     */
    constructor($$source = {}) {
        if (!("sampleCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sampleCount"] = 0;
        }
        if (!("sampleInterval" in $$source)) {
            /**
             * 毫秒
             * @member
             * @type {number}
             */
            this["sampleInterval"] = 0;
        }
        if (!("maxStdDev" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxStdDev"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemperatureStabilityConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TemperatureStabilityConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemperatureStabilityConfig(/** @type {Partial<TemperatureStabilityConfig>} */($$parsedSource));
    }
}

/**
 * TotalTemperatureConfig 总温校准专用配置
 */
export class TotalTemperatureConfig {
    /**
     * Creates a new TotalTemperatureConfig instance.
     * @param {Partial<TotalTemperatureConfig>} [$$source = {}] - The source object to create the TotalTemperatureConfig.
     */
    constructor($$source = {}) {
        if (!("probeChannels" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: ChannelRef }}
             */
            this["probeChannels"] = {};
        }
        if (!("targetMachNumbers" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["targetMachNumbers"] = [];
        }
        if (!("machTolerance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machTolerance"] = 0;
        }
        if (!("stabilityCriteria" in $$source)) {
            /**
             * @member
             * @type {TemperatureStabilityConfig}
             */
            this["stabilityCriteria"] = (new TemperatureStabilityConfig());
        }
        if (!("samplesPerPoint" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["samplesPerPoint"] = 0;
        }
        if (!("sampleInterval" in $$source)) {
            /**
             * 毫秒
             * @member
             * @type {number}
             */
            this["sampleInterval"] = 0;
        }
        if (!("enableFitting" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableFitting"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TotalTemperatureConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TotalTemperatureConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType6;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField0_0($$parsedSource["probeChannels"]);
        }
        if ("targetMachNumbers" in $$parsedSource) {
            $$parsedSource["targetMachNumbers"] = $$createField1_0($$parsedSource["targetMachNumbers"]);
        }
        if ("stabilityCriteria" in $$parsedSource) {
            $$parsedSource["stabilityCriteria"] = $$createField3_0($$parsedSource["stabilityCriteria"]);
        }
        return new TotalTemperatureConfig(/** @type {Partial<TotalTemperatureConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = ChannelRef.createFrom;
const $$createType2 = traversal$0.MotionSafetyFailure.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $$createType1);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = TemperatureStabilityConfig.createFrom;
