// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendFrontendLog(arg1:string):Promise<void>;

export function GetAPIPort():Promise<number>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function ShowSaveFilePath(arg1:string,arg2:string,arg3:string):Promise<string>;
