// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendFrontendLog(arg1) {
  return window['go']['main']['App']['AppendFrontendLog'](arg1);
}

export function GetAPIPort() {
  return window['go']['main']['App']['GetAPIPort']();
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}

export function ShowSaveFilePath(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowSaveFilePath'](arg1, arg2, arg3);
}
