// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AxisConfig 单轴配置，包含机械、电气及运动限制参数。
 */
export class AxisConfig {
    /**
     * Creates a new AxisConfig instance.
     * @param {Partial<AxisConfig>} [$$source = {}] - The source object to create the AxisConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {AxisName}
             */
            this["name"] = AxisName.$zero;
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {AxisKind}
             */
            this["kind"] = AxisKind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maxSpeed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["minLimit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maxLimit"] = undefined;
        }
        if (!("inverted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inverted"] = false;
        }
        if (!("encoderInverted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["encoderInverted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["stepsPerRev"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["microSteps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["lead"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["gearRatio"] = undefined;
        }
        if (!("positionSource" in $$source)) {
            /**
             * @member
             * @type {PositionSource}
             */
            this["positionSource"] = PositionSource.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["encoderScale"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AxisEncoderCompensationConfig | null | undefined}
             */
            this["encoderCompensation"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AxisConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AxisConfig}
     */
    static createFrom($$source = {}) {
        const $$createField14_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("encoderCompensation" in $$parsedSource) {
            $$parsedSource["encoderCompensation"] = $$createField14_0($$parsedSource["encoderCompensation"]);
        }
        return new AxisConfig(/** @type {Partial<AxisConfig>} */($$parsedSource));
    }
}

/**
 * AxisEncoderCompensationConfig 编码器补偿参数。
 * 字段类型与 shared.local/device-sdk/go/motion/core 对齐，
 * 避免 wrapper.go 中冗余的类型转换函数。
 */
export class AxisEncoderCompensationConfig {
    /**
     * Creates a new AxisEncoderCompensationConfig instance.
     * @param {Partial<AxisEncoderCompensationConfig>} [$$source = {}] - The source object to create the AxisEncoderCompensationConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("tolerance" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tolerance"] = 0;
        }
        if (!("maxCycles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxCycles"] = 0;
        }
        if (!("settleMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settleMs"] = 0;
        }
        if (!("minStep" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minStep"] = 0;
        }
        if (!("timeoutMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AxisEncoderCompensationConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AxisEncoderCompensationConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AxisEncoderCompensationConfig(/** @type {Partial<AxisEncoderCompensationConfig>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const AxisKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AxisKindLinear: "LINEAR",
    AxisKindRotary: "ROTARY",
};

/**
 * @readonly
 * @enum {string}
 */
export const AxisName = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    AxisX: "X",
    AxisY: "Y",
    AxisZ: "Z",
    AxisU: "U",
};

/**
 * @readonly
 * @enum {string}
 */
export const ControllerType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ControllerTypeSimulated: "SIMULATED-MC",
    ControllerTypeB140: "B140-MC",
    ControllerTypeWTNMC4A: "WTNMC4A-MC",
};

export class MotionControllerProfile {
    /**
     * Creates a new MotionControllerProfile instance.
     * @param {Partial<MotionControllerProfile>} [$$source = {}] - The source object to create the MotionControllerProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ControllerType}
             */
            this["type"] = ControllerType.$zero;
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("autoConnect" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoConnect"] = false;
        }
        if (!("axes" in $$source)) {
            /**
             * @member
             * @type {AxisConfig[]}
             */
            this["axes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionControllerProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionControllerProfile}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("axes" in $$parsedSource) {
            $$parsedSource["axes"] = $$createField6_0($$parsedSource["axes"]);
        }
        return new MotionControllerProfile(/** @type {Partial<MotionControllerProfile>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const PositionSource = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PositionSourceRegister: "register",
    PositionSourceEncoder: "encoder",
};

// Private type creation functions
const $$createType0 = AxisEncoderCompensationConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = AxisConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
