; Git-tracked copy of Wails NSIS helpers for Wind-DAQ installer.
; Originally auto-generated by `wails build`, now maintained manually.

!include "x64.nsh"
!include "WinVer.nsh"
!include "FileFunc.nsh"

!ifndef INFO_PROJECTNAME
    !define INFO_PROJECTNAME "wind-daq"
!endif
!ifndef INFO_COMPANYNAME
    !define INFO_COMPANYNAME "wind-daq"
!endif
!ifndef INFO_PRODUCTNAME
    !define INFO_PRODUCTNAME "wind-daq"
!endif
!ifndef INFO_PRODUCTVERSION
    !define INFO_PRODUCTVERSION "0.2.0"
!endif
!ifndef INFO_COPYRIGHT
    !define INFO_COPYRIGHT "Copyright........."
!endif
!ifndef PRODUCT_EXECUTABLE
    !define PRODUCT_EXECUTABLE "${INFO_PROJECTNAME}.exe"
!endif
!ifndef UNINST_KEY_NAME
    !define UNINST_KEY_NAME "${INFO_COMPANYNAME}${INFO_PRODUCTNAME}"
!endif
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${UNINST_KEY_NAME}"

!ifndef PRODUCT_UNINST_ROOT_KEY
    !define PRODUCT_UNINST_ROOT_KEY "HKLM"
!endif

!ifndef REQUEST_EXECUTION_LEVEL
    !define REQUEST_EXECUTION_LEVEL "admin"
!endif

RequestExecutionLevel "${REQUEST_EXECUTION_LEVEL}"

!ifdef ARG_WAILS_AMD64_BINARY
    !define SUPPORTS_AMD64
!endif

!ifdef ARG_WAILS_ARM64_BINARY
    !define SUPPORTS_ARM64
!endif

!ifdef SUPPORTS_AMD64
    !ifdef SUPPORTS_ARM64
        !define ARCH "amd64_arm64"
    !else
        !define ARCH "amd64"
    !endif
!else
    !ifdef SUPPORTS_ARM64
        !define ARCH "arm64"
    !else
        !error "Wails: Undefined ARCH, please provide at least one of ARG_WAILS_AMD64_BINARY or ARG_WAILS_ARM64_BINARY"
    !endif
!endif

!macro wails.checkArchitecture
    !ifndef WAILS_WIN10_REQUIRED
        !define WAILS_WIN10_REQUIRED "This product is only supported on Windows 10 (Server 2016) and later."
    !endif

    !ifndef WAILS_ARCHITECTURE_NOT_SUPPORTED
        !define WAILS_ARCHITECTURE_NOT_SUPPORTED "This product can't be installed on the current Windows architecture. Supports: ${ARCH}"
    !endif

    ${If} ${AtLeastWin10}
        !ifdef SUPPORTS_AMD64
            ${if} ${IsNativeAMD64}
                Goto ok
            ${EndIf}
        !endif

        !ifdef SUPPORTS_ARM64
            ${if} ${IsNativeARM64}
                Goto ok
            ${EndIf}
        !endif

        IfSilent silentArch notSilentArch
        silentArch:
            SetErrorLevel 64
            Abort
        notSilentArch:
            MessageBox MB_OK "${WAILS_ARCHITECTURE_NOT_SUPPORTED}"
            Quit
    ${else}
        IfSilent silentWin notSilentWin
        silentWin:
            SetErrorLevel 64
            Abort
        notSilentWin:
            MessageBox MB_OK "${WAILS_WIN10_REQUIRED}"
            Quit
    ${EndIf}

    ok:
!macroend

!macro wails.setShellContext
    SetRegView 64
!macroend

!macro wails.webview2runtime
    !ifndef WAILS_WEBVIEW2_METHOD
        !define WAILS_WEBVIEW2_METHOD "download"
    !endif

    !if "${WAILS_WEBVIEW2_METHOD}" == "download"
        AddSize 114688
        ${If} ${IsNativeAMD64}
            DetailPrint "Downloading WebView2 Runtime..."
            NSISdl::download "https://go.microsoft.com/fwlink/p/?LinkId=2124703" "$TEMP\MicrosoftEdgeWebview2Setup.exe"
            Pop $0
            ${If} $0 == "success"
                ExecWait '"$TEMP\MicrosoftEdgeWebview2Setup.exe" /silent /install'
            ${EndIf}
        ${EndIf}
    !endif
!macroend

!macro wails.files
    !ifdef ARG_WAILS_AMD64_BINARY
        ${if} ${IsNativeAMD64}
            File "/oname=${PRODUCT_EXECUTABLE}" "${ARG_WAILS_AMD64_BINARY}"
        ${EndIf}
    !endif

    !ifdef ARG_WAILS_ARM64_BINARY
        ${if} ${IsNativeARM64}
            File "/oname=${PRODUCT_EXECUTABLE}" "${ARG_WAILS_ARM64_BINARY}"
        ${EndIf}
    !endif
!macroend

!macro wails.writeUninstaller
    WriteUninstaller "$INSTDIR\uninstall.exe"

    WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}" "DisplayName" "$(^Name)"
    WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}" "UninstallString" "$INSTDIR\uninstall.exe"
    WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}" "DisplayVersion" "${INFO_PRODUCTVERSION}"
    WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}" "Publisher" "${INFO_COMPANYNAME}"
!macroend

!macro wails.associateFiles
    !ifdef WAILS_FILE_ASSOCIATION
        !define _WAILS_UNINST_KEY "${UNINST_KEY}\Capabilities"
        WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${_WAILS_UNINST_KEY}" "ApplicationDescription" "${INFO_PRODUCTNAME}"
        !include "${WAILS_FILE_ASSOCIATION}"
        WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}\Capabilities" "ApplicationName" "${INFO_PRODUCTNAME}"
        WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "Software\RegisteredApplications" "${INFO_PRODUCTNAME}" "${_WAILS_UNINST_KEY}"
    !endif
!macroend

!macro wails.unassociateFiles
    !ifdef WAILS_FILE_ASSOCIATION
        DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}\Capabilities"
        DeleteRegValue ${PRODUCT_UNINST_ROOT_KEY} "Software\RegisteredApplications" "${INFO_PRODUCTNAME}"
    !endif
!macroend

!macro wails.associateCustomProtocols
    !ifdef WAILS_CUSTOM_PROTOCOL
        !include "${WAILS_CUSTOM_PROTOCOL}"
    !endif
!macroend

!macro wails.unassociateCustomProtocols
    !ifdef WAILS_CUSTOM_PROTOCOL
    !endif
!macroend

!macro wails.deleteUninstaller
    DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${UNINST_KEY}"
!macroend
