// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 暴露设备相关能力给前端：
 *   - 扫描 / 配置 CRUD
 *   - 连接 / 断开 / 应用配置
 *   - 启动 / 停止采集（带后台中继协程，按 100ms 频率推送温度快照、按 1s 频率推送录制状态）
 * 
 * 设计要点：
 *   - 录制相关的热路径调用通过 hub.RecordingService 引用直接走，
 *     避免在 RecordingService 中再绕一层 Wails Bind 调用；
 *   - 中继协程的生命周期由 hub 集中管理（RegisterRelay/ClearRelay/WaitRelay/StopAllRelays）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * ApplyConfig 下发设备配置。
 */
export function ApplyConfig(id: string, cfg: core$0.T1603Config): $CancellablePromise<void> {
    return $Call.ByID(235024810, id, cfg);
}

/**
 * Connect 连接设备。
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(724450446, id);
}

/**
 * DeleteProfile 删除设备配置。
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(786381196, id);
}

/**
 * Disconnect 断开设备。
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2646115826, id);
}

/**
 * GetProfiles 获取所有设备配置。
 */
export function GetProfiles(): $CancellablePromise<core$0.TemperatureProfile[]> {
    return $Call.ByID(1209733158).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStatus 返回指定设备的当前状态。
 * 
 * 返回签名 (DeviceState, error)：
 *   - 成功（设备存在）: 返回 state, nil
 *   - 未找到（设备不存在 / 未连接过）: 返回 zero, ErrDeviceNotFound
 * 
 * 前端 ts 已用 `as any + .catch(()=>false)` 兼容这个签名变更。
 */
export function GetStatus(id: string): $CancellablePromise<core$0.DeviceState> {
    return $Call.ByID(1140259278, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ScanDevices 触发设备扫描。
 */
export function ScanDevices(): $CancellablePromise<core$0.ScanResult[]> {
    return $Call.ByID(3253070356).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * StartAcquisition 启动采集。
 */
export function StartAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(3707360075, id);
}

/**
 * StopAcquisition 停止采集。
 */
export function StopAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(2315056847, id);
}

/**
 * UpsertProfile 新增 / 更新设备配置。
 */
export function UpsertProfile(profile: core$0.TemperatureProfile): $CancellablePromise<void> {
    return $Call.ByID(4029723420, profile);
}

// Private type creation functions
const $$createType0 = core$0.TemperatureProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = core$0.DeviceState.createFrom;
const $$createType3 = core$0.ScanResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
