// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 暴露设备相关能力给前端：
 *   - 扫描 / 配置 CRUD
 *   - 连接 / 断开 / 应用配置
 *   - 启动 / 停止采集（带后台中继协程，按用户设置的刷新率推送温度快照、按 1s 频率推送录制状态）
 *   - 设置 UI 刷新率（SetUIRefreshRateHz，动态调整推送节奏，无需重启采集）
 *
 * 设计要点：
 *   - 录制相关的热路径调用通过 hub.RecordingService 引用直接走，
 *     避免在 RecordingService 中再绕一层 Wails Bind 调用；
 *   - 中继协程的生命周期由 hub 集中管理（RegisterRelay/ClearRelay/WaitRelay/StopAllRelays）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * ApplyConfig 下发设备配置。
 */
export function ApplyConfig(id: string, cfg: core$0.T1603Config): $CancellablePromise<void> {
    return $Call.ByID(235024810, id, cfg);
}

/**
 * Connect 连接设备。
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(724450446, id);
}

/**
 * DeleteProfile 删除设备配置。
 */
export function DeleteProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(786381196, id);
}

/**
 * Disconnect 断开设备。
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2646115826, id);
}

/**
 * EmitDeviceState 实现 core.StateEmitter 接口（ACQ-010/STB-003）。
 *
 * 由 adapter 在 OnReadLoopExit 等异步状态变化时通过 hub.EmitDeviceState 触发，
 * 本方法将状态通过 Wails Event 总线广播为 daq:device-state 事件，
 * 前端 App.vue 中 onDeviceState 订阅器接收后调用 syncStatusFromBackend，
 * 让 statusMap 实时同步（如物理断网后从「采集中」直接变为「未连接」）。
 * 
 * 实现轻量：仅持 s.mu 读取 app 字段后立即释放，无 I/O 阻塞，
 * 可在 adapter 持锁回调中安全调用（s.mu 与 adapter 的 a.mu 是不同锁，无嵌套死锁风险）。
 * 加 recover 保护：应用退出阶段 app 可能已关闭，Event.Emit 在已关闭的 app 上可能 panic，
 * recover 避免 panic 终止 adapter readLoop 的清理流程；
 * recover 内记录 slog.Debug 保留可观测性，避免静默吞掉真实 bug（如 state 字段 nil）。
 */
export function EmitDeviceState(deviceID: string, state: core$0.DeviceState): $CancellablePromise<void> {
    return $Call.ByID(2016103354, deviceID, state);
}

/**
 * ExitApplication 主动退出应用。
 * 
 * 设计意图：Wails v3 alpha.95 在 Windows 平台未暴露 ShouldClose 拦截钩子，
 * 原生窗口的 X 按钮点击后默认监听器会直接关闭窗口，前端无法在原生路径上拦截。
 * 因此提供一个"带确认的应用内退出"路径：前端 MainTopBar 的"退出应用"按钮
 * 弹出 Naive UI 确认框，用户确认后调用本方法触发 application.Quit()，
 * 走与原生关闭等价的 ServiceShutdown 清理流程（停止采集 / 录制 / 日志 / relay）。
 * 
 * 与 Window.Close() 的差异：application.Quit() 会触发所有窗口的关闭流程
 * 并终止应用主循环，确保单窗口场景下应用真正退出。
 */
export function ExitApplication(): $CancellablePromise<void> {
    return $Call.ByID(2366630710);
}

/**
 * GetProfiles 获取所有设备配置。
 */
export function GetProfiles(): $CancellablePromise<core$0.TemperatureProfile[]> {
    return $Call.ByID(1209733158).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStatus 返回指定设备的当前状态。
 * 
 * 返回签名 (DeviceState, error)：
 *   - 成功（设备存在）: 返回 state, nil
 *   - 未找到（设备不存在 / 未连接过）: 返回 zero, ErrDeviceNotFound
 * 
 * 前端 ts 已用 `as any + .catch(()=>false)` 兼容这个签名变更。
 */
export function GetStatus(id: string): $CancellablePromise<core$0.DeviceState> {
    return $Call.ByID(1140259278, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ScanDevices 触发设备扫描。
 */
export function ScanDevices(): $CancellablePromise<core$0.ScanResult[]> {
    return $Call.ByID(3253070356).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetUIRefreshRateHz 设置 UI 快照推送频率（Hz）。
 * 
 * 设计意图：
 *   - 前端 MainTopBar 提供 2/5/10/15/20/30 Hz 档位，让用户平衡"画面流畅度"与"CPU 占用"；
 *   - 后端 relayStream 按此频率通过 daq:payload 事件推送最新快照；
 *   - relayStream 在下次 uiTicker.C 触发时检测 atomic 变化并 Reset ticker，
 *     最长等一个旧间隔生效（如 10Hz→2Hz 最长 100ms+500ms=600ms），无需重启采集。
 * 
 * 范围校验：[1, 60] Hz。
 *   - 下限 1Hz：低于 1Hz 会让图表长时间不更新，误导用户以为采集卡死；
 *   - 上限 60Hz：超过 60Hz 会拖慢 WebView2 GUI 线程，与前端 displayStore 限制一致。
 * 
 * 该方法只更新 atomic 值，不持任何锁，可安全在 Wails Bind 调用栈中使用。
 */
export function SetUIRefreshRateHz(hz: number): $CancellablePromise<void> {
    return $Call.ByID(1825276241, hz);
}

/**
 * StartAcquisition 启动采集。
 */
export function StartAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(3707360075, id);
}

/**
 * StopAcquisition 停止采集。
 */
export function StopAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(2315056847, id);
}

/**
 * UpsertProfile 新增 / 更新设备配置。
 */
export function UpsertProfile(profile: core$0.TemperatureProfile): $CancellablePromise<void> {
    return $Call.ByID(4029723420, profile);
}

// Private type creation functions
const $$createType0 = core$0.TemperatureProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = core$0.DeviceState.createFrom;
const $$createType3 = core$0.ScanResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
