// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService 暴露日志相关能力给前端，同时实现 core.LogEmitter 接口，
 * 由 Hub 统一调度日志事件分发。
 * 
 * 注意：在 Wails v3 下，所有 frontend 可调用的方法都必须挂在以指针接收器导出的方法上，
 * 且通过 application.NewService(&LogService{...}) 注册。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EmitLog 是 core.LogEmitter 的实现：
 *   1. 补全时间戳与来源；
 *   2. 同步写入日志文件（若已开启）；
 *   3. 通过 Wails v3 Event 总线推送给前端。
 */
export function EmitLog(entry: core$0.LogEvent): $CancellablePromise<void> {
    return $Call.ByID(2107957577, entry);
}

/**
 * GetLogFileState 返回日志文件当前状态。
 */
export function GetLogFileState(): $CancellablePromise<$models.LogFileState> {
    return $Call.ByID(2014087071).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PickDirectory 打开系统目录选择对话框。
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(4211100394);
}

/**
 * StartLogFile 开始将日志写入文件。
 */
export function StartLogFile(outputDir: string, prefix: string): $CancellablePromise<void> {
    return $Call.ByID(3301204382, outputDir, prefix);
}

/**
 * StopLogFile 停止日志文件写入。
 */
export function StopLogFile(): $CancellablePromise<void> {
    return $Call.ByID(3286228126);
}

// Private type creation functions
const $$createType0 = $models.LogFileState.createFrom;
