// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogFileState 日志文件写入状态，用于前端展示。
 * 由 LogService.GetLogFileState 返回，前端通过 v3 binding 读取。
 */
export class LogFileState {
    "active": boolean;
    "outputDir"?: string;

    /** Creates a new LogFileState instance. */
    constructor($$source: Partial<LogFileState> = {}) {
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFileState instance from a string or object.
     */
    static createFrom($$source: any = {}): LogFileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFileState($$parsedSource as Partial<LogFileState>);
    }
}
