// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecordingService 暴露录制相关能力给前端，并对外提供事件发布。
 * 
 * 与 DeviceService 解耦：DeviceService 中的 relay 协程通过 Hub 获取本 Service，
 * 借助 IsActive/Write/EmitStatus 完成录制热路径调用，无需直接依赖 RecordingService 类型。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as core$0 from "../core/models.js";

/**
 * EmitStatus 通过 Wails Event 总线广播当前录制状态。
 * 在 DeviceService 中继协程内被高频调用，因此实现需轻量。
 */
export function EmitStatus(): $CancellablePromise<void> {
    return $Call.ByID(3316133274);
}

/**
 * GetRecordingStatus 返回当前录制状态。
 */
export function GetRecordingStatus(): $CancellablePromise<core$0.RecordingSession> {
    return $Call.ByID(3498070414).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsActive 暴露给 DeviceService 中继协程的无锁热路径查询。
 */
export function IsActive(): $CancellablePromise<boolean> {
    return $Call.ByID(2111457753);
}

/**
 * PickDirectory 打开系统目录选择对话框。
 */
export function PickDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1324924685);
}

/**
 * SetDeviceProfile 注入设备通道配置到 recorder（REC-006）。
 * 由 DeviceService 在设备 Connect / StartAcquisition / ApplyConfig 时调用，
 * 让 recorder 在 CSV 写入时将禁用通道的列写空值，便于操作员区分
 * "通道禁用"与"通道无数据"。
 */
export function SetDeviceProfile(deviceID: string, channels: core$0.ChannelConfig[]): $CancellablePromise<void> {
    return $Call.ByID(871651248, deviceID, channels);
}

/**
 * StartRecording 开始录制；启动后立刻广播一次状态。
 */
export function StartRecording(outputDir: string, filePrefix: string): $CancellablePromise<void> {
    return $Call.ByID(1292621864, outputDir, filePrefix);
}

/**
 * StopRecording 停止录制；停止后立刻广播一次状态。
 */
export function StopRecording(): $CancellablePromise<void> {
    return $Call.ByID(2262564134);
}

/**
 * Write 暴露给 DeviceService 中继协程的写入入口。
 */
export function Write(snapshot: core$0.TemperatureSnapshot): $CancellablePromise<void> {
    return $Call.ByID(292472710, snapshot);
}

// Private type creation functions
const $$createType0 = core$0.RecordingSession.createFrom;
