// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ports} from '../models';
import {usecase} from '../models';

export function GetDevices():Promise<Array<ports.DeviceInfo>>;

export function GetRuntimeStats():Promise<usecase.RuntimeStats>;

export function GetStatus():Promise<usecase.Status>;

export function StartAcquisition():Promise<void>;

export function StopAcquisition():Promise<void>;
