// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetRuntimeStats() {
  return window['go']['main']['App']['GetRuntimeStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function StartAcquisition() {
  return window['go']['main']['App']['StartAcquisition']();
}

export function StopAcquisition() {
  return window['go']['main']['App']['StopAcquisition']();
}
