// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function BatchCalculate(arg1:Array<backend.InterpolationInput>):Promise<backend.BatchCalculateResponse>;

export function Calculate(arg1:backend.InterpolationInput):Promise<backend.CalculateResponse>;

export function GetMachRange():Promise<backend.MachRangeResponse>;

export function GetPrbFiles():Promise<Array<backend.PrbFileInfo>>;

export function ImportCsvData():Promise<backend.ImportCsvDataResponse>;

export function IsPrbLoaded():Promise<boolean>;

export function LoadPrbFiles():Promise<backend.LoadPrbResponse>;

export function OpenHelpDoc():Promise<void>;
