// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ChannelConfig {
    "index": number;
    "name": string;
    "enabled": boolean;
    "unit": string;
    "color": string;
    "precision": number;
    "rangeMin"?: number;
    "rangeMax"?: number;
    "thermocoupleType"?: string;

    /** Creates a new ChannelConfig instance. */
    constructor($$source: Partial<ChannelConfig> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("precision" in $$source)) {
            this["precision"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelConfig($$parsedSource as Partial<ChannelConfig>);
    }
}

export class DeviceState {
    "profile": TemperatureProfile;
    "status": DeviceStatus;
    "statusText": string;
    "error": string;
    "connectedAt": number;
    "acquiringAt": number;
    "samplingRate": number;

    /** Creates a new DeviceState instance. */
    constructor($$source: Partial<DeviceState> = {}) {
        if (!("profile" in $$source)) {
            this["profile"] = (new TemperatureProfile());
        }
        if (!("status" in $$source)) {
            this["status"] = DeviceStatus.$zero;
        }
        if (!("statusText" in $$source)) {
            this["statusText"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("connectedAt" in $$source)) {
            this["connectedAt"] = 0;
        }
        if (!("acquiringAt" in $$source)) {
            this["acquiringAt"] = 0;
        }
        if (!("samplingRate" in $$source)) {
            this["samplingRate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceState {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        return new DeviceState($$parsedSource as Partial<DeviceState>);
    }
}

export enum DeviceStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    StatusDisconnected = 0,
    StatusConnected = 1,
    StatusAcquiring = 2,
    StatusError = 3,
};

/**
 * LogEvent 是前后端共享的日志事件结构。
 * 放到 core 层方便 DeviceService / RecordingService / LogService 共同发布。
 */
export class LogEvent {
    "level": string;
    "category": string;
    "deviceId"?: string;
    "source": string;
    "message": string;
    "detail"?: string;
    "timestamp": number;

    /** Creates a new LogEvent instance. */
    constructor($$source: Partial<LogEvent> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEvent($$parsedSource as Partial<LogEvent>);
    }
}

export class RecordingSession {
    "id": string;
    "outputDir": string;
    "filePrefix": string;
    "startTimeMs": number;
    "snapshotCount": number;
    "status": RecordingStatus;

    /**
     * DroppedCount 是录制队列背压丢弃的总帧数（跨设备聚合）。
     * 前端可据此显示数据完整性指标。
     */
    "droppedCount": number;

    /** Creates a new RecordingSession instance. */
    constructor($$source: Partial<RecordingSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("filePrefix" in $$source)) {
            this["filePrefix"] = "";
        }
        if (!("startTimeMs" in $$source)) {
            this["startTimeMs"] = 0;
        }
        if (!("snapshotCount" in $$source)) {
            this["snapshotCount"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = RecordingStatus.$zero;
        }
        if (!("droppedCount" in $$source)) {
            this["droppedCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingSession instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingSession($$parsedSource as Partial<RecordingSession>);
    }
}

export enum RecordingStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    RecordingIdle = 0,
    RecordingActive = 1,
};

export class ScanResult {
    "id": string;
    "name": string;
    "address": string;
    "port": number;
    "macAddress"?: string;
    "serialNumber"?: string;
    "firmwareVersion"?: string;

    /** Creates a new ScanResult instance. */
    constructor($$source: Partial<ScanResult> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ScanResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanResult($$parsedSource as Partial<ScanResult>);
    }
}

export class T1603Config {
    /**
     * 16 chars, one per channel
     */
    "thermocoupleTypes": string;

    /**
     * hex 0000-FFFF
     */
    "channelMask": string;

    /**
     * Hz
     */
    "samplingRate": number;

    /**
     * 1-100
     */
    "averageCount": number;

    /**
     * 启用设备硬件时间戳（@fe TIME）
     */
    "showTimestamp": boolean;
    "showSequence": boolean;

    /**
     * 启动时自动连接
     */
    "autoConnect": boolean;

    /** Creates a new T1603Config instance. */
    constructor($$source: Partial<T1603Config> = {}) {
        if (!("thermocoupleTypes" in $$source)) {
            this["thermocoupleTypes"] = "";
        }
        if (!("channelMask" in $$source)) {
            this["channelMask"] = "";
        }
        if (!("samplingRate" in $$source)) {
            this["samplingRate"] = 0;
        }
        if (!("averageCount" in $$source)) {
            this["averageCount"] = 0;
        }
        if (!("showTimestamp" in $$source)) {
            this["showTimestamp"] = false;
        }
        if (!("showSequence" in $$source)) {
            this["showSequence"] = false;
        }
        if (!("autoConnect" in $$source)) {
            this["autoConnect"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new T1603Config instance from a string or object.
     */
    static createFrom($$source: any = {}): T1603Config {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new T1603Config($$parsedSource as Partial<T1603Config>);
    }
}

export class TemperatureProfile {
    "id": string;
    "name": string;
    "address": string;
    "port": number;
    "samplingRate": number;
    "channels": ChannelConfig[];
    "t1603Config": T1603Config;
    "createdAt"?: number;

    /** Creates a new TemperatureProfile instance. */
    constructor($$source: Partial<TemperatureProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("samplingRate" in $$source)) {
            this["samplingRate"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("t1603Config" in $$source)) {
            this["t1603Config"] = (new T1603Config());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemperatureProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): TemperatureProfile {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField5_0($$parsedSource["channels"]);
        }
        if ("t1603Config" in $$parsedSource) {
            $$parsedSource["t1603Config"] = $$createField6_0($$parsedSource["t1603Config"]);
        }
        return new TemperatureProfile($$parsedSource as Partial<TemperatureProfile>);
    }
}

export class TemperatureSnapshot {
    "deviceId": string;
    "timestamp": number;

    /**
     * 设备硬件时间戳（秒.纳秒），0 表示无时间戳
     */
    "hardwareTimestamp"?: number;
    "values": number[];
    "unit": string;

    /** Creates a new TemperatureSnapshot instance. */
    constructor($$source: Partial<TemperatureSnapshot> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("values" in $$source)) {
            this["values"] = [];
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemperatureSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): TemperatureSnapshot {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField3_0($$parsedSource["values"]);
        }
        return new TemperatureSnapshot($$parsedSource as Partial<TemperatureSnapshot>);
    }
}

// Private type creation functions
const $$createType0 = TemperatureProfile.createFrom;
const $$createType1 = ChannelConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = T1603Config.createFrom;
const $$createType4 = $Create.Array($Create.Any);
