// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails 后端服务根对象，绑定到前端。
 * 所有前端可调用的方法都挂在 App 上（Wails v3 的 binding 机制要求）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchCalculate 批量计算，遇到错误不中断，标记失败行继续。
 * 这样 CSV 中个别坏行不会让整个批次作废。
 * @param {$models.FiveHoleInterpolationInput[]} datas
 * @returns {$CancellablePromise<$models.BatchCalculateResponse>}
 */
export function BatchCalculate(datas) {
    return $Call.ByID(3705912462, datas).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BatchCalculateSevenHole 批量计算，遇到错误不中断，标记失败行继续。
 * 这样 CSV 中个别坏行不会让整个批次作废。
 * @param {$models.SevenHoleInterpolationInput[]} inputs
 * @returns {$CancellablePromise<$models.SevenHoleBatchCalculateResponse>}
 */
export function BatchCalculateSevenHole(inputs) {
    return $Call.ByID(3929830805, inputs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BatchCalculateThreeHole 批量计算，遇到错误不中断，标记失败行继续。
 * 这样 CSV 中个别坏行不会让整个批次作废。
 * @param {$models.ThreeHoleInterpolationInput[]} datas
 * @returns {$CancellablePromise<$models.ThreeHoleBatchCalculateResponse>}
 */
export function BatchCalculateThreeHole(datas) {
    return $Call.ByID(4099194300, datas).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Calculate 执行 5 孔单点插值计算。
 * @param {$models.FiveHoleInterpolationInput} input
 * @returns {$CancellablePromise<$models.CalculateResponse>}
 */
export function Calculate(input) {
    return $Call.ByID(2146979954, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CalculateSevenHole 执行 7 孔单点插值计算。
 * 输入的所有 P1..P7 必须为表压（gauge），spec §1.1 强制要求。
 * @param {$models.SevenHoleInterpolationInput} input
 * @returns {$CancellablePromise<$models.SevenHoleCalculateResponse>}
 */
export function CalculateSevenHole(input) {
    return $Call.ByID(2900858185, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CalculateThreeHole 执行 3 孔单点插值计算。
 * @param {$models.ThreeHoleInterpolationInput} input
 * @returns {$CancellablePromise<$models.ThreeHoleCalculateResponse>}
 */
export function CalculateThreeHole(input) {
    return $Call.ByID(1917844376, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearActiveProbe 清空当前会话的探针类型选择。
 * 配合前端"返回欢迎页"按钮：用户从工作区回到选择页后，GetActiveProbe 返回空字符串。
 * 注意：本方法不清理各探针 service 的 .prb / 输入状态，用户再次进入同一探针时可恢复。
 * @returns {$CancellablePromise<void>}
 */
export function ClearActiveProbe() {
    return $Call.ByID(2487889769);
}

/**
 * GetActiveProbe 返回当前会话已选择的探针类型。
 * 若用户尚未选择（仍在欢迎页），返回空字符串 + nil error，前端按空字符串判定留在选择页。
 * @returns {$CancellablePromise<$models.ProbeKind>}
 */
export function GetActiveProbe() {
    return $Call.ByID(2342081050);
}

/**
 * GetAvailableProbes 返回启动选择页要展示的探针列表（3/5/7 孔）。
 * 返回切片的副本，前端修改不影响后端状态。
 * @returns {$CancellablePromise<$models.ProbeInfo[]>}
 */
export function GetAvailableProbes() {
    return $Call.ByID(3321602286).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetMachRange 返回已加载 .prb 的马赫数覆盖范围 [min, max]。
 * @returns {$CancellablePromise<$models.MachRangeResponse>}
 */
export function GetMachRange() {
    return $Call.ByID(612579304).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetPrbFiles 返回已加载的 5 孔 .prb 文件列表。
 * @returns {$CancellablePromise<$models.PrbFileInfo[]>}
 */
export function GetPrbFiles() {
    return $Call.ByID(1844642521).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetSevenHoleDataSource 返回当前已加载的 7 孔数据源类型。
 * 取值："prb"（PRB 文件集）/ "calibration-csv"（校准 CSV）/ ""（未加载）。
 * 前端在初始化或切回 7 孔工作区时调用，用于决定槽位过滤器与展示文案。
 * @returns {$CancellablePromise<$models.SevenHoleDataSourceResponse>}
 */
export function GetSevenHoleDataSource() {
    return $Call.ByID(1955924992).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetSevenHolePrbFiles 返回已加载的 7 孔 .prb / CSV 文件列表。
 * @returns {$CancellablePromise<$models.SevenHolePrbFileInfo[]>}
 */
export function GetSevenHolePrbFiles() {
    return $Call.ByID(397896414).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetSevenHoleValidRange 返回内区网格的角度覆盖范围（±30°）。
 * 注意：算法包明确要求此范围仅供 UI 展示，不得用于事后有效性拒绝（spec §2.2）。
 * @returns {$CancellablePromise<$models.SevenHoleValidRangeResponse>}
 */
export function GetSevenHoleValidRange() {
    return $Call.ByID(2107756326).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetThreeHoleMachRange 返回已加载 .prb 的马赫数覆盖范围 [min, max]。
 * @returns {$CancellablePromise<$models.ThreeHoleMachRangeResponse>}
 */
export function GetThreeHoleMachRange() {
    return $Call.ByID(814220490).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetThreeHolePrbFiles 返回已加载的 3 孔 .prb 文件列表。
 * @returns {$CancellablePromise<$models.ThreeHolePrbFileInfo[]>}
 */
export function GetThreeHolePrbFiles() {
    return $Call.ByID(1531895847).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ImportCsvData 弹出文件选择对话框让用户选 5 孔数据 CSV，
 * 解析 P1-P5 + Patm + Tatm + PressureMode 列。
 * 必须包含 P1-P5 列，Patm/Tatm/PressureMode 可选（缺失时用零值）。
 * @returns {$CancellablePromise<$models.ImportCsvDataResponse>}
 */
export function ImportCsvData() {
    return $Call.ByID(843116193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ImportSevenHoleCsvData 弹出文件选择对话框让用户选 7 孔数据 CSV，
 * 解析 P1-P7 + Patm + Tatm 列（共 9 列，全部必需）。
 * 
 * 与 5 孔 CSV 的区别：
 *   - 5 孔：P1-P5 必需，Patm/Tatm/PressureMode 可选
 *   - 7 孔：P1-P7 + Patm + Tatm 全部必需（spec §1.1 强制表压，无 PressureMode 列）
 * 
 * 支持 .csv/.txt/.dat 三种扩展名（与 3 孔一致），分隔符自动检测 tab vs 逗号。
 * 注意：此方法导入的是"数据 CSV"（待计算的压力数据），与 LoadSevenHoleCalibrationCsvFiles
 * 导入的"校准 CSV"（标定网格点系数）完全不同——后者是 7 份 GBK 编码的标定文件。
 * @returns {$CancellablePromise<$models.SevenHoleImportCsvDataResponse>}
 */
export function ImportSevenHoleCsvData() {
    return $Call.ByID(2368340882).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * ImportThreeHoleCsvData 弹出文件选择对话框让用户选 3 孔数据 CSV/TXT/DAT，
 * 自动检测分隔符（Tab 或逗号），解析 P1 + P2 + P3 + Patm + Tatm 列。
 * 与 5 孔不同：3 孔的 Patm/Tatm 列为必填（与旧 3 孔程序一致，保证向后兼容）。
 * @returns {$CancellablePromise<$models.ThreeHoleImportCsvDataResponse>}
 */
export function ImportThreeHoleCsvData() {
    return $Call.ByID(2643417749).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * IsPrbLoaded 返回 5 孔 .prb 是否已加载。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPrbLoaded() {
    return $Call.ByID(148155519);
}

/**
 * IsSevenHolePrbLoaded 返回 7 孔 .prb 文件集是否已全部加载。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSevenHolePrbLoaded() {
    return $Call.ByID(2552265974);
}

/**
 * IsThreeHolePrbLoaded 返回 3 孔 .prb 是否已加载。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsThreeHolePrbLoaded() {
    return $Call.ByID(1068877981);
}

/**
 * LoadPrbFiles 弹出文件选择对话框让用户选择多个 5 孔 .prb 校准文件，
 * 加载后构建 MultiPrbInterpolator 并缓存到 fiveHoleState。
 * 返回加载结果（文件列表 + 马赫数范围 + 警告）供前端展示。
 * @returns {$CancellablePromise<$models.LoadPrbResponse>}
 */
export function LoadPrbFiles() {
    return $Call.ByID(1484034861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * LoadSevenHoleCalibrationCsvFiles 加载已分配好的 7 个校准 CSV 文件路径
 * （1 份内区 CSV + 6 份外区 CSV，文件名约定：含"小角度区"→内区，含"大角度N区"→扇区 N）。
 * 
 * 与 LoadSevenHolePrbFiles 同结构，区别仅在内/外区文件解析走 CSV 路径
 * （GBK 解码 + 列位置契约 + 退化边抖动，详见 seven_hole_csv.go）。
 * 解析失败的错误信息含文件路径，便于前端定位是哪个 CSV 出问题。
 * @param {string} innerPath
 * @param {string[]} outerPaths
 * @returns {$CancellablePromise<$models.SevenHoleLoadPrbResponse>}
 */
export function LoadSevenHoleCalibrationCsvFiles(innerPath, outerPaths) {
    return $Call.ByID(1952451816, innerPath, outerPaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * LoadSevenHolePrbFiles 加载已分配好的 7 个 .prb 文件路径（1 个内区 + 6 个扇区）。
 * 
 * 与旧实现的差异（对齐 wind-daq 遍历测试 §5.6）：
 *   - 旧实现：后端弹多选对话框 + 后端按 basename 路由 sector
 *   - 新实现：前端弹对话框 + 前端按 basename 分配 sector + 后端只接收已分配的 inner+outer[6]
 * 
 * 设计要点：
 *   - 内区必须最先加载：外区插值在边界场景会回查内区网格（spec §5）
 *   - sector 编号 1..6 对应 outerPaths[0..5]，与 7 孔探针外围孔位物理编号一致
 *   - 外区路径数必须为 6，否则返回错误（避免静默用零值导致后续解析失败）
 *   - 文件路径由前端按 basename 分配（"7.prb"→内区，"1.prb"~"6.prb"→扇区 n），
 *     后端不再做 basename 路由，便于前端在 UI 上同步展示每个槽位的文件名
 * @param {string} innerPath
 * @param {string[]} outerPaths
 * @returns {$CancellablePromise<$models.SevenHoleLoadPrbResponse>}
 */
export function LoadSevenHolePrbFiles(innerPath, outerPaths) {
    return $Call.ByID(1460511666, innerPath, outerPaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * LoadThreeHolePrbFiles 弹出文件选择对话框让用户选择 3 孔 .prb 校准文件（通常单文件），
 * 加载后构建 ThreeHoleInterpolator 并缓存到 threeHoleState。
 * 返回加载结果（文件列表 + 马赫数范围 + 警告）供前端展示。
 * @returns {$CancellablePromise<$models.ThreeHoleLoadPrbResponse>}
 */
export function LoadThreeHolePrbFiles() {
    return $Call.ByID(2882600435).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * OpenHelpDoc 用系统默认程序打开 5 孔用户说明书 HTML 文件。
 * 路径解析与跨平台打开逻辑抽到共享工具 GetHelpDocPath / OpenHelpDocByPath。
 * @returns {$CancellablePromise<void>}
 */
export function OpenHelpDoc() {
    return $Call.ByID(378848421);
}

/**
 * OpenSevenHoleHelpDoc 用系统默认程序打开 7 孔用户说明书 HTML 文件。
 * 路径解析与跨平台打开逻辑抽到共享工具 GetHelpDocPath / OpenHelpDocByPath。
 * @returns {$CancellablePromise<void>}
 */
export function OpenSevenHoleHelpDoc() {
    return $Call.ByID(3462261920);
}

/**
 * OpenThreeHoleHelpDoc 用系统默认程序打开 3 孔用户说明书 HTML 文件。
 * 路径解析与跨平台打开逻辑抽到共享工具 GetHelpDocPath / OpenHelpDocByPath。
 * @returns {$CancellablePromise<void>}
 */
export function OpenThreeHoleHelpDoc() {
    return $Call.ByID(2030674927);
}

/**
 * PickSevenHoleFiles 弹出多选文件对话框，让用户选择 7 孔 PRB 或校准 CSV 文件。
 * 
 * 仅返回用户选中的文件路径列表，不解析、不分配槽位——分配逻辑由前端按 basename 完成
 * （assignSevenHoleFilesByName / assignSevenHoleCsvFilesByName）。
 * 这样后端无需关心文件名约定，前端可在 UI 上展示"哪些文件未被识别"。
 * 
 * 取消选择时返回 Success=true + 空 Paths（与 Wails 对话框"OK 但无选择"语义一致）。
 * 
 * 实现说明：直接调用 application.Get() 取全局单例，与 openFileDialog 一致
 * （参见 dialog.go 注释解释了为何移除 a.app 双源回退）。
 * @returns {$CancellablePromise<$models.SevenHolePickFilesResponse>}
 */
export function PickSevenHoleFiles() {
    return $Call.ByID(3076596409).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * SetActiveProbe 设置当前会话的探针类型。
 * 允许覆盖式更新：用户从工作区返回欢迎页后可再次选择其他探针类型。
 * 各探针 service 的 .prb / 输入状态由各 service 自行保留，切换不会丢失。
 * @param {$models.ProbeKind} kind
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveProbe(kind) {
    return $Call.ByID(2503957150, kind);
}

// Private type creation functions
const $$createType0 = $models.BatchCalculateResponse.createFrom;
const $$createType1 = $models.SevenHoleBatchCalculateResponse.createFrom;
const $$createType2 = $models.ThreeHoleBatchCalculateResponse.createFrom;
const $$createType3 = $models.CalculateResponse.createFrom;
const $$createType4 = $models.SevenHoleCalculateResponse.createFrom;
const $$createType5 = $models.ThreeHoleCalculateResponse.createFrom;
const $$createType6 = $models.ProbeInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.MachRangeResponse.createFrom;
const $$createType9 = $models.PrbFileInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.SevenHoleDataSourceResponse.createFrom;
const $$createType12 = $models.SevenHolePrbFileInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.SevenHoleValidRangeResponse.createFrom;
const $$createType15 = $models.ThreeHoleMachRangeResponse.createFrom;
const $$createType16 = $models.ThreeHolePrbFileInfo.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $models.ImportCsvDataResponse.createFrom;
const $$createType19 = $models.SevenHoleImportCsvDataResponse.createFrom;
const $$createType20 = $models.ThreeHoleImportCsvDataResponse.createFrom;
const $$createType21 = $models.LoadPrbResponse.createFrom;
const $$createType22 = $models.SevenHoleLoadPrbResponse.createFrom;
const $$createType23 = $models.ThreeHoleLoadPrbResponse.createFrom;
const $$createType24 = $models.SevenHolePickFilesResponse.createFrom;
