// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 是 Wails 后端服务根对象，绑定到前端。
 * 所有前端可调用的方法都挂在 App 上（Wails v3 的 binding 机制要求）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchCalculate 批量计算，遇到错误不中断，标记失败行继续。
 * 这样 CSV 中个别坏行不会让整个批次作废。
 * @param {$models.FiveHoleInterpolationInput[]} datas
 * @returns {$CancellablePromise<$models.BatchCalculateResponse>}
 */
export function BatchCalculate(datas) {
    return $Call.ByID(3705912462, datas).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * BatchCalculateSevenHole 批量计算，遇到错误不中断，标记失败行继续。
 * 这样 CSV 中个别坏行不会让整个批次作废。
 * @param {$models.SevenHoleInterpolationInput[]} inputs
 * @returns {$CancellablePromise<$models.SevenHoleBatchCalculateResponse>}
 */
export function BatchCalculateSevenHole(inputs) {
    return $Call.ByID(3929830805, inputs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BatchCalculateThreeHole 批量计算，遇到错误不中断，标记失败行继续。
 * 这样 CSV 中个别坏行不会让整个批次作废。
 * @param {$models.ThreeHoleInterpolationInput[]} datas
 * @returns {$CancellablePromise<$models.ThreeHoleBatchCalculateResponse>}
 */
export function BatchCalculateThreeHole(datas) {
    return $Call.ByID(4099194300, datas).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Calculate 执行 5 孔单点插值计算。
 * @param {$models.FiveHoleInterpolationInput} input
 * @returns {$CancellablePromise<$models.CalculateResponse>}
 */
export function Calculate(input) {
    return $Call.ByID(2146979954, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CalculateSevenHole 执行 7 孔单点插值计算。
 * 输入的所有 P1..P7 必须为表压（gauge），spec §1.1 强制要求。
 * @param {$models.SevenHoleInterpolationInput} input
 * @returns {$CancellablePromise<$models.SevenHoleCalculateResponse>}
 */
export function CalculateSevenHole(input) {
    return $Call.ByID(2900858185, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CalculateThreeHole 执行 3 孔单点插值计算。
 * @param {$models.ThreeHoleInterpolationInput} input
 * @returns {$CancellablePromise<$models.ThreeHoleCalculateResponse>}
 */
export function CalculateThreeHole(input) {
    return $Call.ByID(1917844376, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ClearActiveProbe 清空当前会话的探针类型选择。
 * 配合前端"返回欢迎页"按钮：用户从工作区回到选择页后，GetActiveProbe 返回空字符串。
 * 注意：本方法不清理各探针 service 的 .prb / 输入状态，用户再次进入同一探针时可恢复。
 * @returns {$CancellablePromise<void>}
 */
export function ClearActiveProbe() {
    return $Call.ByID(2487889769);
}

/**
 * GetActiveProbe 返回当前会话已选择的探针类型。
 * 若用户尚未选择（仍在欢迎页），返回空字符串 + nil error，前端按空字符串判定留在选择页。
 * @returns {$CancellablePromise<$models.ProbeKind>}
 */
export function GetActiveProbe() {
    return $Call.ByID(2342081050);
}

/**
 * GetAvailableProbes 返回启动选择页要展示的探针列表（3/5/7 孔）。
 * 返回切片的副本，前端修改不影响后端状态。
 * @returns {$CancellablePromise<$models.ProbeInfo[]>}
 */
export function GetAvailableProbes() {
    return $Call.ByID(3321602286).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetMachRange 返回已加载 .prb 的马赫数覆盖范围 [min, max]。
 * @returns {$CancellablePromise<$models.MachRangeResponse>}
 */
export function GetMachRange() {
    return $Call.ByID(612579304).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetPrbFiles 返回已加载的 5 孔 .prb 文件列表。
 * @returns {$CancellablePromise<$models.PrbFileInfo[]>}
 */
export function GetPrbFiles() {
    return $Call.ByID(1844642521).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetSevenHolePrbFiles 返回已加载的 7 孔 .prb 文件列表。
 * @returns {$CancellablePromise<$models.SevenHolePrbFileInfo[]>}
 */
export function GetSevenHolePrbFiles() {
    return $Call.ByID(397896414).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetSevenHoleValidRange 返回内区网格的角度覆盖范围（±30°）。
 * 注意：算法包明确要求此范围仅供 UI 展示，不得用于事后有效性拒绝（spec §2.2）。
 * @returns {$CancellablePromise<$models.SevenHoleValidRangeResponse>}
 */
export function GetSevenHoleValidRange() {
    return $Call.ByID(2107756326).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetThreeHoleMachRange 返回已加载 .prb 的马赫数覆盖范围 [min, max]。
 * @returns {$CancellablePromise<$models.ThreeHoleMachRangeResponse>}
 */
export function GetThreeHoleMachRange() {
    return $Call.ByID(814220490).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetThreeHolePrbFiles 返回已加载的 3 孔 .prb 文件列表。
 * @returns {$CancellablePromise<$models.ThreeHolePrbFileInfo[]>}
 */
export function GetThreeHolePrbFiles() {
    return $Call.ByID(1531895847).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ImportCsvData 弹出文件选择对话框让用户选 5 孔数据 CSV，
 * 解析 P1-P5 + Patm + Tatm + PressureMode 列。
 * 必须包含 P1-P5 列，Patm/Tatm/PressureMode 可选（缺失时用零值）。
 * @returns {$CancellablePromise<$models.ImportCsvDataResponse>}
 */
export function ImportCsvData() {
    return $Call.ByID(843116193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * ImportSevenHoleCsvData 弹出文件选择对话框让用户选 7 孔数据 CSV，
 * 解析 P1-P7 + Patm + Tatm 列（共 9 列，全部必需）。
 * 
 * 与 5 孔 CSV 的区别：
 *   - 5 孔：P1-P5 必需，Patm/Tatm/PressureMode 可选
 *   - 7 孔：P1-P7 + Patm + Tatm 全部必需（spec §1.1 强制表压，无 PressureMode 列）
 * 
 * 支持 .csv/.txt/.dat 三种扩展名（与 3 孔一致），分隔符自动检测 tab vs 逗号。
 * @returns {$CancellablePromise<$models.SevenHoleImportCsvDataResponse>}
 */
export function ImportSevenHoleCsvData() {
    return $Call.ByID(2368340882).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ImportThreeHoleCsvData 弹出文件选择对话框让用户选 3 孔数据 CSV/TXT/DAT，
 * 自动检测分隔符（Tab 或逗号），解析 P1 + P2 + P3 + Patm + Tatm 列。
 * 与 5 孔不同：3 孔的 Patm/Tatm 列为必填（与旧 3 孔程序一致，保证向后兼容）。
 * @returns {$CancellablePromise<$models.ThreeHoleImportCsvDataResponse>}
 */
export function ImportThreeHoleCsvData() {
    return $Call.ByID(2643417749).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType19($result);
    }));
}

/**
 * IsPrbLoaded 返回 5 孔 .prb 是否已加载。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPrbLoaded() {
    return $Call.ByID(148155519);
}

/**
 * IsSevenHolePrbLoaded 返回 7 孔 .prb 文件集是否已全部加载。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSevenHolePrbLoaded() {
    return $Call.ByID(2552265974);
}

/**
 * IsThreeHolePrbLoaded 返回 3 孔 .prb 是否已加载。
 * @returns {$CancellablePromise<boolean>}
 */
export function IsThreeHolePrbLoaded() {
    return $Call.ByID(1068877981);
}

/**
 * LoadPrbFiles 弹出文件选择对话框让用户选择多个 5 孔 .prb 校准文件，
 * 加载后构建 MultiPrbInterpolator 并缓存到 fiveHoleState。
 * 返回加载结果（文件列表 + 马赫数范围 + 警告）供前端展示。
 * @returns {$CancellablePromise<$models.LoadPrbResponse>}
 */
export function LoadPrbFiles() {
    return $Call.ByID(1484034861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * LoadSevenHolePrbFiles 弹出多选文件对话框，让用户选择 7 个 .prb 校准文件
 * （1.prb..7.prb），加载后构建 SevenHolePrbInterpolator 并缓存到 sevenHoleState。
 * 
 * 文件名约定（与 shared/algorithms/go/sevenhole/interpolation/testdata/prb/ 一致）：
 *   - "7.prb" → 内区网格（13×13=169 点，a/b ∈ [-30,30] 步长 5）
 *   - "1.prb".."6.prb" → 外区扇区 1..6（每个 4×13=52 点，θ ∈ [30,45] 步长 5）
 * 
 * 文件名 basename（不含扩展名）必须为 "1".."7" 之一的纯数字字符串；
 * 不满足约定时返回错误，提示用户按规范命名。
 * @returns {$CancellablePromise<$models.SevenHoleLoadPrbResponse>}
 */
export function LoadSevenHolePrbFiles() {
    return $Call.ByID(1460511666).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * LoadThreeHolePrbFiles 弹出文件选择对话框让用户选择 3 孔 .prb 校准文件（通常单文件），
 * 加载后构建 ThreeHoleInterpolator 并缓存到 threeHoleState。
 * 返回加载结果（文件列表 + 马赫数范围 + 警告）供前端展示。
 * @returns {$CancellablePromise<$models.ThreeHoleLoadPrbResponse>}
 */
export function LoadThreeHolePrbFiles() {
    return $Call.ByID(2882600435).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * OpenHelpDoc 用系统默认程序打开 5 孔用户说明书 HTML 文件。
 * 路径解析与跨平台打开逻辑抽到共享工具 GetHelpDocPath / OpenHelpDocByPath。
 * @returns {$CancellablePromise<void>}
 */
export function OpenHelpDoc() {
    return $Call.ByID(378848421);
}

/**
 * OpenSevenHoleHelpDoc 用系统默认程序打开 7 孔用户说明书 HTML 文件。
 * 路径解析与跨平台打开逻辑抽到共享工具 GetHelpDocPath / OpenHelpDocByPath。
 * @returns {$CancellablePromise<void>}
 */
export function OpenSevenHoleHelpDoc() {
    return $Call.ByID(3462261920);
}

/**
 * OpenThreeHoleHelpDoc 用系统默认程序打开 3 孔用户说明书 HTML 文件。
 * 路径解析与跨平台打开逻辑抽到共享工具 GetHelpDocPath / OpenHelpDocByPath。
 * @returns {$CancellablePromise<void>}
 */
export function OpenThreeHoleHelpDoc() {
    return $Call.ByID(2030674927);
}

/**
 * SetActiveProbe 设置当前会话的探针类型。
 * 允许覆盖式更新：用户从工作区返回欢迎页后可再次选择其他探针类型。
 * 各探针 service 的 .prb / 输入状态由各 service 自行保留，切换不会丢失。
 * @param {$models.ProbeKind} kind
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveProbe(kind) {
    return $Call.ByID(2503957150, kind);
}

// Private type creation functions
const $$createType0 = $models.BatchCalculateResponse.createFrom;
const $$createType1 = $models.SevenHoleBatchCalculateResponse.createFrom;
const $$createType2 = $models.ThreeHoleBatchCalculateResponse.createFrom;
const $$createType3 = $models.CalculateResponse.createFrom;
const $$createType4 = $models.SevenHoleCalculateResponse.createFrom;
const $$createType5 = $models.ThreeHoleCalculateResponse.createFrom;
const $$createType6 = $models.ProbeInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.MachRangeResponse.createFrom;
const $$createType9 = $models.PrbFileInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.SevenHolePrbFileInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.SevenHoleValidRangeResponse.createFrom;
const $$createType14 = $models.ThreeHoleMachRangeResponse.createFrom;
const $$createType15 = $models.ThreeHolePrbFileInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.ImportCsvDataResponse.createFrom;
const $$createType18 = $models.SevenHoleImportCsvDataResponse.createFrom;
const $$createType19 = $models.ThreeHoleImportCsvDataResponse.createFrom;
const $$createType20 = $models.LoadPrbResponse.createFrom;
const $$createType21 = $models.SevenHoleLoadPrbResponse.createFrom;
const $$createType22 = $models.ThreeHoleLoadPrbResponse.createFrom;
