// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BatchCalculateResponse {
    /**
     * Creates a new BatchCalculateResponse instance.
     * @param {Partial<BatchCalculateResponse>} [$$source = {}] - The source object to create the BatchCalculateResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(FiveHoleInterpolationResult | null)[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchCalculateResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchCalculateResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new BatchCalculateResponse(/** @type {Partial<BatchCalculateResponse>} */($$parsedSource));
    }
}

export class CalculateResponse {
    /**
     * Creates a new CalculateResponse instance.
     * @param {Partial<CalculateResponse>} [$$source = {}] - The source object to create the CalculateResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FiveHoleInterpolationResult | null | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalculateResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalculateResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new CalculateResponse(/** @type {Partial<CalculateResponse>} */($$parsedSource));
    }
}

/**
 * FiveHoleInterpolationInput 是 5 孔单点计算的输入。
 * PressureMode 取值 "gauge"（表压，默认）或 "absolute"（绝压），
 * 绝压模式下后端会自动减去 Patm 转为表压再传给算法包。
 */
export class FiveHoleInterpolationInput {
    /**
     * Creates a new FiveHoleInterpolationInput instance.
     * @param {Partial<FiveHoleInterpolationInput>} [$$source = {}] - The source object to create the FiveHoleInterpolationInput.
     */
    constructor($$source = {}) {
        if (!("P1" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P1"] = 0;
        }
        if (!("P2" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P2"] = 0;
        }
        if (!("P3" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P3"] = 0;
        }
        if (!("P4" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P4"] = 0;
        }
        if (!("P5" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P5"] = 0;
        }
        if (!("Patm" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Patm"] = 0;
        }
        if (!("Tatm" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Tatm"] = 0;
        }
        if (!("pressureMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pressureMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleInterpolationInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FiveHoleInterpolationInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleInterpolationInput(/** @type {Partial<FiveHoleInterpolationInput>} */($$parsedSource));
    }
}

/**
 * FiveHoleInterpolationResult 是 5 孔单点计算的输出。
 * 字段语义：Alpha=迎角、Beta=侧滑角（注意 7 孔语义反转）。
 */
export class FiveHoleInterpolationResult {
    /**
     * Creates a new FiveHoleInterpolationResult instance.
     * @param {Partial<FiveHoleInterpolationResult>} [$$source = {}] - The source object to create the FiveHoleInterpolationResult.
     */
    constructor($$source = {}) {
        if (!("alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alpha"] = 0;
        }
        if (!("beta" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["beta"] = 0;
        }
        if (!("machNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machNumber"] = 0;
        }
        if (!("V" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["V"] = 0;
        }
        if (!("Vx" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Vx"] = 0;
        }
        if (!("Vy" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Vy"] = 0;
        }
        if (!("Vz" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Vz"] = 0;
        }
        if (!("velocity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["velocity"] = 0;
        }
        if (!("cas" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cas"] = 0;
        }
        if (!("sat" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sat"] = 0;
        }
        if (!("dynamicPressure" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dynamicPressure"] = 0;
        }
        if (!("density" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["density"] = 0;
        }
        if (!("P0" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P0"] = 0;
        }
        if (!("Ps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Ps"] = 0;
        }
        if (!("isValid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isValid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["warning"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleInterpolationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FiveHoleInterpolationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleInterpolationResult(/** @type {Partial<FiveHoleInterpolationResult>} */($$parsedSource));
    }
}

export class ImportCsvDataResponse {
    /**
     * Creates a new ImportCsvDataResponse instance.
     * @param {Partial<ImportCsvDataResponse>} [$$source = {}] - The source object to create the ImportCsvDataResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FiveHoleInterpolationInput[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportCsvDataResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportCsvDataResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ImportCsvDataResponse(/** @type {Partial<ImportCsvDataResponse>} */($$parsedSource));
    }
}

export class LoadPrbResponse {
    /**
     * Creates a new LoadPrbResponse instance.
     * @param {Partial<LoadPrbResponse>} [$$source = {}] - The source object to create the LoadPrbResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {LoadPrbResult | null | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadPrbResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadPrbResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new LoadPrbResponse(/** @type {Partial<LoadPrbResponse>} */($$parsedSource));
    }
}

export class LoadPrbResult {
    /**
     * Creates a new LoadPrbResult instance.
     * @param {Partial<LoadPrbResult>} [$$source = {}] - The source object to create the LoadPrbResult.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {PrbFileInfo[]}
             */
            this["files"] = [];
        }
        if (!("machRange" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["machRange"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadPrbResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoadPrbResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        if ("machRange" in $$parsedSource) {
            $$parsedSource["machRange"] = $$createField1_0($$parsedSource["machRange"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new LoadPrbResult(/** @type {Partial<LoadPrbResult>} */($$parsedSource));
    }
}

export class MachRangeResponse {
    /**
     * Creates a new MachRangeResponse instance.
     * @param {Partial<MachRangeResponse>} [$$source = {}] - The source object to create the MachRangeResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MachRangeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MachRangeResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new MachRangeResponse(/** @type {Partial<MachRangeResponse>} */($$parsedSource));
    }
}

/**
 * PrbFileInfo 是单个 .prb 校准文件的元信息，前端用于展示已加载文件列表。
 */
export class PrbFileInfo {
    /**
     * Creates a new PrbFileInfo instance.
     * @param {Partial<PrbFileInfo>} [$$source = {}] - The source object to create the PrbFileInfo.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("machNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machNumber"] = 0;
        }
        if (!("validRange" in $$source)) {
            /**
             * @member
             * @type {PrbValidRange}
             */
            this["validRange"] = (new PrbValidRange());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrbFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrbFileInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("validRange" in $$parsedSource) {
            $$parsedSource["validRange"] = $$createField3_0($$parsedSource["validRange"]);
        }
        return new PrbFileInfo(/** @type {Partial<PrbFileInfo>} */($$parsedSource));
    }
}

/**
 * PrbValidRange 描述 .prb 校准网格的角度与马赫数覆盖范围。
 * 前端据此提示用户输入是否在校准区间内。
 */
export class PrbValidRange {
    /**
     * Creates a new PrbValidRange instance.
     * @param {Partial<PrbValidRange>} [$$source = {}] - The source object to create the PrbValidRange.
     */
    constructor($$source = {}) {
        if (!("alphaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alphaMin"] = 0;
        }
        if (!("alphaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alphaMax"] = 0;
        }
        if (!("betaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["betaMin"] = 0;
        }
        if (!("betaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["betaMax"] = 0;
        }
        if (!("machMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machMin"] = 0;
        }
        if (!("machMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrbValidRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PrbValidRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrbValidRange(/** @type {Partial<PrbValidRange>} */($$parsedSource));
    }
}

/**
 * ProbeInfo 是启动选择页每个探针按钮的元信息，前端按此渲染卡片。
 */
export class ProbeInfo {
    /**
     * Creates a new ProbeInfo instance.
     * @param {Partial<ProbeInfo>} [$$source = {}] - The source object to create the ProbeInfo.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ProbeKind}
             */
            this["kind"] = ProbeKind.$zero;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("holes" in $$source)) {
            /**
             * Holes 是探针测压孔数量，仅用于卡片角标显示
             * @member
             * @type {number}
             */
            this["holes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProbeInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeInfo(/** @type {Partial<ProbeInfo>} */($$parsedSource));
    }
}

/**
 * ProbeKind 标识探针类型，作为 SetActiveProbe / GetActiveProbe 的参数与返回值。
 * 取值固定为 three / five / seven 三选一，前端按此字符串路由工作区。
 * @readonly
 * @enum {string}
 */
export const ProbeKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ProbeKindThree 三孔探针
     */
    ProbeKindThree: "three",

    /**
     * ProbeKindFive 五孔探针
     */
    ProbeKindFive: "five",

    /**
     * ProbeKindSeven 七孔探针
     */
    ProbeKindSeven: "seven",
};

export class SevenHoleBatchCalculateResponse {
    /**
     * Creates a new SevenHoleBatchCalculateResponse instance.
     * @param {Partial<SevenHoleBatchCalculateResponse>} [$$source = {}] - The source object to create the SevenHoleBatchCalculateResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(SevenHoleInterpolationResult | null)[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleBatchCalculateResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleBatchCalculateResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new SevenHoleBatchCalculateResponse(/** @type {Partial<SevenHoleBatchCalculateResponse>} */($$parsedSource));
    }
}

export class SevenHoleCalculateResponse {
    /**
     * Creates a new SevenHoleCalculateResponse instance.
     * @param {Partial<SevenHoleCalculateResponse>} [$$source = {}] - The source object to create the SevenHoleCalculateResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SevenHoleInterpolationResult | null | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleCalculateResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleCalculateResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new SevenHoleCalculateResponse(/** @type {Partial<SevenHoleCalculateResponse>} */($$parsedSource));
    }
}

/**
 * SevenHoleDataSourceResponse 返回当前已加载的 7 孔数据源类型。
 * DataSource 取值："prb"（PRB 文件集）/ "calibration-csv"（校准 CSV）/ ""（未加载）。
 */
export class SevenHoleDataSourceResponse {
    /**
     * Creates a new SevenHoleDataSourceResponse instance.
     * @param {Partial<SevenHoleDataSourceResponse>} [$$source = {}] - The source object to create the SevenHoleDataSourceResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("data" in $$source)) {
            /**
             * "prb" | "calibration-csv" | ""
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleDataSourceResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleDataSourceResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SevenHoleDataSourceResponse(/** @type {Partial<SevenHoleDataSourceResponse>} */($$parsedSource));
    }
}

export class SevenHoleImportCsvDataResponse {
    /**
     * Creates a new SevenHoleImportCsvDataResponse instance.
     * @param {Partial<SevenHoleImportCsvDataResponse>} [$$source = {}] - The source object to create the SevenHoleImportCsvDataResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SevenHoleInterpolationInput[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleImportCsvDataResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleImportCsvDataResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new SevenHoleImportCsvDataResponse(/** @type {Partial<SevenHoleImportCsvDataResponse>} */($$parsedSource));
    }
}

/**
 * SevenHoleInterpolationInput 是 7 孔单点计算的输入。
 * 所有 P1..P7 必须是表压（gauge，Pa），Patm 为绝对压力（Pa），Tatm 为摄氏温度。
 * 不提供 PressureMode 字段：7 孔 spec §1.1 强制表压输入，绝压数据需在导入前由调用方转换。
 */
export class SevenHoleInterpolationInput {
    /**
     * Creates a new SevenHoleInterpolationInput instance.
     * @param {Partial<SevenHoleInterpolationInput>} [$$source = {}] - The source object to create the SevenHoleInterpolationInput.
     */
    constructor($$source = {}) {
        if (!("P1" in $$source)) {
            /**
             * 外围孔 1 表压（Pa）
             * @member
             * @type {number}
             */
            this["P1"] = 0;
        }
        if (!("P2" in $$source)) {
            /**
             * 外围孔 2 表压（Pa）
             * @member
             * @type {number}
             */
            this["P2"] = 0;
        }
        if (!("P3" in $$source)) {
            /**
             * 外围孔 3 表压（Pa）
             * @member
             * @type {number}
             */
            this["P3"] = 0;
        }
        if (!("P4" in $$source)) {
            /**
             * 外围孔 4 表压（Pa）
             * @member
             * @type {number}
             */
            this["P4"] = 0;
        }
        if (!("P5" in $$source)) {
            /**
             * 外围孔 5 表压（Pa）
             * @member
             * @type {number}
             */
            this["P5"] = 0;
        }
        if (!("P6" in $$source)) {
            /**
             * 外围孔 6 表压（Pa）
             * @member
             * @type {number}
             */
            this["P6"] = 0;
        }
        if (!("P7" in $$source)) {
            /**
             * 中心孔表压（Pa）
             * @member
             * @type {number}
             */
            this["P7"] = 0;
        }
        if (!("Patm" in $$source)) {
            /**
             * 大气绝对压力（Pa）
             * @member
             * @type {number}
             */
            this["Patm"] = 0;
        }
        if (!("Tatm" in $$source)) {
            /**
             * 大气温度（℃）
             * @member
             * @type {number}
             */
            this["Tatm"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleInterpolationInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleInterpolationInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SevenHoleInterpolationInput(/** @type {Partial<SevenHoleInterpolationInput>} */($$parsedSource));
    }
}

/**
 * SevenHoleInterpolationResult 是 7 孔单点计算的输出。
 *
 * 字段语义注意（与 5 孔反转，spec §2.2 / 附录 A）：
 *   - Alpha = 侧滑角（sideslip），5 孔里 Alpha 是迎角
 *   - Beta  = 迎角（angle of attack），5 孔里 Beta 是侧滑角
 *
 * Theta/Phi 是 PRB 网格原始角度坐标（deg），供前端展示与诊断：
 *   - 内区（小角度）模式：Theta=Alpha、Phi=Beta（两套坐标系重合）
 *   - 外区（大角度）模式：Theta 是探头坐标系俯仰角、Phi 是方位角；
 *     Alpha/Beta 是经 convertThetaPhiToAlphaBeta 投影后的风洞坐标系角度
 *
 * JSON tag 与 5 孔结果一致（P0/Ps/alpha/beta/velocity/dynamicPressure），
 * 便于前端结果表格组件复用同样的列定义。
 */
export class SevenHoleInterpolationResult {
    /**
     * Creates a new SevenHoleInterpolationResult instance.
     * @param {Partial<SevenHoleInterpolationResult>} [$$source = {}] - The source object to create the SevenHoleInterpolationResult.
     */
    constructor($$source = {}) {
        if (!("alpha" in $$source)) {
            /**
             * 侧滑角（deg），7 孔语义
             * @member
             * @type {number}
             */
            this["alpha"] = 0;
        }
        if (!("beta" in $$source)) {
            /**
             * 迎角（deg），7 孔语义
             * @member
             * @type {number}
             */
            this["beta"] = 0;
        }
        if (!("theta" in $$source)) {
            /**
             * PRB 网格俯仰角（deg）：内区=Alpha，外区=原始 theta
             * @member
             * @type {number}
             */
            this["theta"] = 0;
        }
        if (!("phi" in $$source)) {
            /**
             * PRB 网格方位角（deg）：内区=Beta，外区=原始 phi
             * @member
             * @type {number}
             */
            this["phi"] = 0;
        }
        if (!("machNumber" in $$source)) {
            /**
             * 马赫数
             * @member
             * @type {number}
             */
            this["machNumber"] = 0;
        }
        if (!("velocity" in $$source)) {
            /**
             * 流速（m/s）
             * @member
             * @type {number}
             */
            this["velocity"] = 0;
        }
        if (!("dynamicPressure" in $$source)) {
            /**
             * 动压 Pt-Ps（Pa）
             * @member
             * @type {number}
             */
            this["dynamicPressure"] = 0;
        }
        if (!("P0" in $$source)) {
            /**
             * 总压（表压，Pa）
             * @member
             * @type {number}
             */
            this["P0"] = 0;
        }
        if (!("Ps" in $$source)) {
            /**
             * 静压（表压，Pa）
             * @member
             * @type {number}
             */
            this["Ps"] = 0;
        }
        if (!("isValid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isValid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["warning"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleInterpolationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleInterpolationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SevenHoleInterpolationResult(/** @type {Partial<SevenHoleInterpolationResult>} */($$parsedSource));
    }
}

export class SevenHoleLoadPrbResponse {
    /**
     * Creates a new SevenHoleLoadPrbResponse instance.
     * @param {Partial<SevenHoleLoadPrbResponse>} [$$source = {}] - The source object to create the SevenHoleLoadPrbResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SevenHoleLoadPrbResult | null | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleLoadPrbResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleLoadPrbResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new SevenHoleLoadPrbResponse(/** @type {Partial<SevenHoleLoadPrbResponse>} */($$parsedSource));
    }
}

/**
 * SevenHoleLoadPrbResult 是加载 .prb / 校准 CSV 文件集后返回给前端的结果。
 * Files 按内区（7.prb）→ 外区 1..6 顺序排列；ValidRange 来自内区网格角点。
 * InnerPointCount 固定 169（13×13，物理设计）；OuterPointCounts 为各扇区 thetaCount×13 动态值。
 */
export class SevenHoleLoadPrbResult {
    /**
     * Creates a new SevenHoleLoadPrbResult instance.
     * @param {Partial<SevenHoleLoadPrbResult>} [$$source = {}] - The source object to create the SevenHoleLoadPrbResult.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {SevenHolePrbFileInfo[]}
             */
            this["files"] = [];
        }
        if (!("validRange" in $$source)) {
            /**
             * @member
             * @type {SevenHolePrbValidRange}
             */
            this["validRange"] = (new SevenHolePrbValidRange());
        }
        if (!("innerPointCount" in $$source)) {
            /**
             * 内区实际点数（固定 169）
             * @member
             * @type {number}
             */
            this["innerPointCount"] = 0;
        }
        if (!("outerPointCounts" in $$source)) {
            /**
             * 各扇区外区实际点数（动态）
             * @member
             * @type {number[]}
             */
            this["outerPointCounts"] = Array.from({ length: 6 }, () => 0);
        }
        if (!("dataSource" in $$source)) {
            /**
             * "prb" | "calibration-csv"
             * @member
             * @type {string}
             */
            this["dataSource"] = "";
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleLoadPrbResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleLoadPrbResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType20;
        const $$createField1_0 = $$createType21;
        const $$createField5_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        if ("validRange" in $$parsedSource) {
            $$parsedSource["validRange"] = $$createField1_0($$parsedSource["validRange"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new SevenHoleLoadPrbResult(/** @type {Partial<SevenHoleLoadPrbResult>} */($$parsedSource));
    }
}

/**
 * SevenHolePickFilesResponse 是 PickSevenHoleFiles 多选文件对话框的返回结果。
 * 仅返回用户选中的文件路径列表，不解析、不分配槽位——分配逻辑由前端按 basename 完成。
 * 取消选择时 Paths 为空数组 + Success=true（与 Wails 对话框"OK 但无选择"语义一致）。
 *
 * Paths 字段不用 omitempty：后端已显式把 nil 转为 []string{}，保持空数组语义
 * （取消时前端能拿到 []，而非 undefined），让前端 ?? [] 兜底与显式 [] 等价。
 */
export class SevenHolePickFilesResponse {
    /**
     * Creates a new SevenHolePickFilesResponse instance.
     * @param {Partial<SevenHolePickFilesResponse>} [$$source = {}] - The source object to create the SevenHolePickFilesResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("paths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHolePickFilesResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHolePickFilesResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField2_0($$parsedSource["paths"]);
        }
        return new SevenHolePickFilesResponse(/** @type {Partial<SevenHolePickFilesResponse>} */($$parsedSource));
    }
}

/**
 * SevenHolePrbFileInfo 是单个 7 孔 .prb / 校准 CSV 文件的元信息。
 * Sector 字段标识文件角色：7=内区（7.prb 或小角度区 CSV），1..6=外区扇区 n（n.prb 或大角度N区 CSV）。
 *
 * 注意：曾经存在的 Loaded 字段已移除——后端只在全部 7 个文件成功加载后才写入 sevenHoleState，
 * 因此返回列表中的每一项都隐含 Loaded=true。前端若需要"是否已加载"判断应调用 IsSevenHolePrbLoaded。
 *
 * PointCount 字段：内区固定 169（13×13），扇区动态 = thetaCount×13（如 4×13=52、7×13=91）。
 * 由算法包 GetInnerPointCount / GetOuterPointCount 运行时读取，不再使用 169/52 兼容约定值。
 */
export class SevenHolePrbFileInfo {
    /**
     * Creates a new SevenHolePrbFileInfo instance.
     * @param {Partial<SevenHolePrbFileInfo>} [$$source = {}] - The source object to create the SevenHolePrbFileInfo.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("sector" in $$source)) {
            /**
             * 7=内区 (7.prb/小角度区 CSV)，1..6=外区扇区 n
             * @member
             * @type {number}
             */
            this["sector"] = 0;
        }
        if (!("pointCount" in $$source)) {
            /**
             * 内区固定 169；扇区动态 = thetaCount×13
             * @member
             * @type {number}
             */
            this["pointCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHolePrbFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHolePrbFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SevenHolePrbFileInfo(/** @type {Partial<SevenHolePrbFileInfo>} */($$parsedSource));
    }
}

/**
 * SevenHolePrbValidRange 描述 7 孔内区网格的角度覆盖范围（±30°）。
 * 注意：MachMin/MachMax 恒为 0，仅 Alpha/Beta 范围有意义；
 * 算法包明确要求不得用此范围做事后有效性拒绝（spec §2.2）。
 */
export class SevenHolePrbValidRange {
    /**
     * Creates a new SevenHolePrbValidRange instance.
     * @param {Partial<SevenHolePrbValidRange>} [$$source = {}] - The source object to create the SevenHolePrbValidRange.
     */
    constructor($$source = {}) {
        if (!("alphaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alphaMin"] = 0;
        }
        if (!("alphaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alphaMax"] = 0;
        }
        if (!("betaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["betaMin"] = 0;
        }
        if (!("betaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["betaMax"] = 0;
        }
        if (!("machMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machMin"] = 0;
        }
        if (!("machMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHolePrbValidRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHolePrbValidRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SevenHolePrbValidRange(/** @type {Partial<SevenHolePrbValidRange>} */($$parsedSource));
    }
}

export class SevenHoleValidRangeResponse {
    /**
     * Creates a new SevenHoleValidRangeResponse instance.
     * @param {Partial<SevenHoleValidRangeResponse>} [$$source = {}] - The source object to create the SevenHoleValidRangeResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SevenHolePrbValidRange | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SevenHoleValidRangeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SevenHoleValidRangeResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new SevenHoleValidRangeResponse(/** @type {Partial<SevenHoleValidRangeResponse>} */($$parsedSource));
    }
}

export class ThreeHoleBatchCalculateResponse {
    /**
     * Creates a new ThreeHoleBatchCalculateResponse instance.
     * @param {Partial<ThreeHoleBatchCalculateResponse>} [$$source = {}] - The source object to create the ThreeHoleBatchCalculateResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(ThreeHoleInterpolationResult | null)[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleBatchCalculateResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleBatchCalculateResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ThreeHoleBatchCalculateResponse(/** @type {Partial<ThreeHoleBatchCalculateResponse>} */($$parsedSource));
    }
}

export class ThreeHoleCalculateResponse {
    /**
     * Creates a new ThreeHoleCalculateResponse instance.
     * @param {Partial<ThreeHoleCalculateResponse>} [$$source = {}] - The source object to create the ThreeHoleCalculateResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ThreeHoleInterpolationResult | null | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleCalculateResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleCalculateResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ThreeHoleCalculateResponse(/** @type {Partial<ThreeHoleCalculateResponse>} */($$parsedSource));
    }
}

export class ThreeHoleImportCsvDataResponse {
    /**
     * Creates a new ThreeHoleImportCsvDataResponse instance.
     * @param {Partial<ThreeHoleImportCsvDataResponse>} [$$source = {}] - The source object to create the ThreeHoleImportCsvDataResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ThreeHoleInterpolationInput[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleImportCsvDataResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleImportCsvDataResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ThreeHoleImportCsvDataResponse(/** @type {Partial<ThreeHoleImportCsvDataResponse>} */($$parsedSource));
    }
}

/**
 * ThreeHoleInterpolationInput 是 3 孔单点计算的输入。
 * PressureMode 取值 "gauge"（表压，默认）或 "absolute"（绝压），
 * 绝压模式下后端会自动减去 Patm 转为表压再传给算法包。
 */
export class ThreeHoleInterpolationInput {
    /**
     * Creates a new ThreeHoleInterpolationInput instance.
     * @param {Partial<ThreeHoleInterpolationInput>} [$$source = {}] - The source object to create the ThreeHoleInterpolationInput.
     */
    constructor($$source = {}) {
        if (!("P1" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P1"] = 0;
        }
        if (!("P2" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P2"] = 0;
        }
        if (!("P3" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P3"] = 0;
        }
        if (!("Patm" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Patm"] = 0;
        }
        if (!("Tatm" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Tatm"] = 0;
        }
        if (!("pressureMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pressureMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleInterpolationInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleInterpolationInput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHoleInterpolationInput(/** @type {Partial<ThreeHoleInterpolationInput>} */($$parsedSource));
    }
}

/**
 * ThreeHoleInterpolationResult 是 3 孔单点计算的输出。
 * 3 孔只测一维角度（Alpha=迎角），无 Beta/速度分量字段（与 5 孔结果区别在此）。
 */
export class ThreeHoleInterpolationResult {
    /**
     * Creates a new ThreeHoleInterpolationResult instance.
     * @param {Partial<ThreeHoleInterpolationResult>} [$$source = {}] - The source object to create the ThreeHoleInterpolationResult.
     */
    constructor($$source = {}) {
        if (!("alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alpha"] = 0;
        }
        if (!("machNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machNumber"] = 0;
        }
        if (!("P0" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["P0"] = 0;
        }
        if (!("Ps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Ps"] = 0;
        }
        if (!("iterationCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iterationCount"] = 0;
        }
        if (!("calculated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["calculated"] = false;
        }
        if (!("isValid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isValid"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["warning"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleInterpolationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleInterpolationResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHoleInterpolationResult(/** @type {Partial<ThreeHoleInterpolationResult>} */($$parsedSource));
    }
}

export class ThreeHoleLoadPrbResponse {
    /**
     * Creates a new ThreeHoleLoadPrbResponse instance.
     * @param {Partial<ThreeHoleLoadPrbResponse>} [$$source = {}] - The source object to create the ThreeHoleLoadPrbResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ThreeHoleLoadPrbResult | null | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleLoadPrbResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleLoadPrbResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ThreeHoleLoadPrbResponse(/** @type {Partial<ThreeHoleLoadPrbResponse>} */($$parsedSource));
    }
}

export class ThreeHoleLoadPrbResult {
    /**
     * Creates a new ThreeHoleLoadPrbResult instance.
     * @param {Partial<ThreeHoleLoadPrbResult>} [$$source = {}] - The source object to create the ThreeHoleLoadPrbResult.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {ThreeHolePrbFileInfo[]}
             */
            this["files"] = [];
        }
        if (!("machRange" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["machRange"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleLoadPrbResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleLoadPrbResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType30;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField0_0($$parsedSource["files"]);
        }
        if ("machRange" in $$parsedSource) {
            $$parsedSource["machRange"] = $$createField1_0($$parsedSource["machRange"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new ThreeHoleLoadPrbResult(/** @type {Partial<ThreeHoleLoadPrbResult>} */($$parsedSource));
    }
}

export class ThreeHoleMachRangeResponse {
    /**
     * Creates a new ThreeHoleMachRangeResponse instance.
     * @param {Partial<ThreeHoleMachRangeResponse>} [$$source = {}] - The source object to create the ThreeHoleMachRangeResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleMachRangeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHoleMachRangeResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new ThreeHoleMachRangeResponse(/** @type {Partial<ThreeHoleMachRangeResponse>} */($$parsedSource));
    }
}

/**
 * ThreeHolePrbFileInfo 是单个 3 孔 .prb 校准文件的元信息，前端用于展示已加载文件列表。
 */
export class ThreeHolePrbFileInfo {
    /**
     * Creates a new ThreeHolePrbFileInfo instance.
     * @param {Partial<ThreeHolePrbFileInfo>} [$$source = {}] - The source object to create the ThreeHolePrbFileInfo.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("machNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machNumber"] = 0;
        }
        if (!("validRange" in $$source)) {
            /**
             * @member
             * @type {ThreeHolePrbValidRange}
             */
            this["validRange"] = (new ThreeHolePrbValidRange());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHolePrbFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHolePrbFileInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("validRange" in $$parsedSource) {
            $$parsedSource["validRange"] = $$createField3_0($$parsedSource["validRange"]);
        }
        return new ThreeHolePrbFileInfo(/** @type {Partial<ThreeHolePrbFileInfo>} */($$parsedSource));
    }
}

/**
 * ThreeHolePrbValidRange 描述 3 孔 .prb 校准网格的角度与马赫数覆盖范围。
 * 3 孔只有一维角度（Alpha），无 Beta 字段（与 5 孔的 PrbValidRange 区别在此）。
 */
export class ThreeHolePrbValidRange {
    /**
     * Creates a new ThreeHolePrbValidRange instance.
     * @param {Partial<ThreeHolePrbValidRange>} [$$source = {}] - The source object to create the ThreeHolePrbValidRange.
     */
    constructor($$source = {}) {
        if (!("alphaMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alphaMin"] = 0;
        }
        if (!("alphaMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["alphaMax"] = 0;
        }
        if (!("machMin" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machMin"] = 0;
        }
        if (!("machMax" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["machMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHolePrbValidRange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreeHolePrbValidRange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHolePrbValidRange(/** @type {Partial<ThreeHolePrbValidRange>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FiveHoleInterpolationResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FiveHoleInterpolationInput.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = LoadPrbResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = PrbFileInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = PrbValidRange.createFrom;
const $$createType12 = SevenHoleInterpolationResult.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = SevenHoleInterpolationInput.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = SevenHoleLoadPrbResult.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = SevenHolePrbFileInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = SevenHolePrbValidRange.createFrom;
const $$createType22 = ThreeHoleInterpolationResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = ThreeHoleInterpolationInput.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ThreeHoleLoadPrbResult.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = ThreeHolePrbFileInfo.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = ThreeHolePrbValidRange.createFrom;
