// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {backend} from '../models';

export function ApplyConfig(arg1:string,arg2:core.P1604Config):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function EmitDeviceState(arg1:string,arg2:core.DeviceState):Promise<void>;

export function EmitLog(arg1:backend.LogEvent):Promise<void>;

export function GetLogFileState():Promise<backend.LogFileState>;

export function GetProfiles():Promise<Array<core.PressureProfile>>;

export function GetRecordingStatus():Promise<core.RecordingSession>;

export function GetStatus(arg1:string):Promise<core.DeviceState|boolean>;

export function PickDirectory():Promise<string>;

export function ScanDevices():Promise<Array<core.ScanResult>>;

export function StartAcquisition(arg1:string):Promise<void>;

export function StartLogFile(arg1:string,arg2:string):Promise<void>;

export function StartRecording(arg1:string,arg2:string):Promise<void>;

export function StopAcquisition(arg1:string):Promise<void>;

export function StopLogFile():Promise<void>;

export function StopRecording():Promise<void>;

export function UpsertProfile(arg1:core.PressureProfile):Promise<void>;
