// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * #3 修复：添加读写互斥锁保护并发访问
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * #8 修复：批量计算不再遇到第一个错误即中断，而是标记失败行继续计算
 */
export function BatchCalculate(datas: $models.InterpolationInput[]): $CancellablePromise<$models.BatchCalculateResponse> {
    return $Call.ByID(3746435099, datas).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Calculate(input: $models.InterpolationInput): $CancellablePromise<$models.CalculateResponse> {
    return $Call.ByID(99396949, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetMachRange(): $CancellablePromise<$models.MachRangeResponse> {
    return $Call.ByID(1042101889).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetPrbFiles(): $CancellablePromise<$models.PrbFileInfo[]> {
    return $Call.ByID(2563241122).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * #1 修复：CSV 解析不再静默吞掉错误，收集解析失败信息
 */
export function ImportCsvData(): $CancellablePromise<$models.ImportCsvDataResponse> {
    return $Call.ByID(269022782).then(($result: any) => {
        return $$createType5($result);
    });
}

export function IsPrbLoaded(): $CancellablePromise<boolean> {
    return $Call.ByID(2258535788);
}

export function LoadPrbFiles(): $CancellablePromise<$models.LoadPrbResponse> {
    return $Call.ByID(1903068944).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * #2 修复：检查 cmd.Start() 的返回错误
 */
export function OpenHelpDoc(): $CancellablePromise<void> {
    return $Call.ByID(1710273118);
}

// Private type creation functions
const $$createType0 = $models.BatchCalculateResponse.createFrom;
const $$createType1 = $models.CalculateResponse.createFrom;
const $$createType2 = $models.MachRangeResponse.createFrom;
const $$createType3 = $models.PrbFileInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ImportCsvDataResponse.createFrom;
const $$createType6 = $models.LoadPrbResponse.createFrom;
