// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MotionSafetyConfig 运动安全配置
 * 
 * 设计目标：在遍历运动阶段对"目标位置 vs 实际位置"偏差、运动卡死、
 * 越过目标、撞限位等异常进行快速失败，避免空跑 120s 兜底超时或撞机。
 * 
 * 字段全部使用指针，零值表示"未配置"——下游通过 Resolve() 合并默认值与
 * 按轴覆盖后得到有效配置。这样旧配置 JSON 反序列化时不会因缺字段报错，
 * 新配置也只需覆盖关心项。
 * 
 * 单位约定：
 *   - 线性轴（X/Y/Z）：mm
 *   - 旋转轴（U）：度（°）
 *   - 通过 AxisOverrides 按轴覆盖可对不同轴使用不同阈值
 */
export class MotionSafetyConfig {
    /**
     * Creates a new MotionSafetyConfig instance.
     * @param {Partial<MotionSafetyConfig>} [$$source = {}] - The source object to create the MotionSafetyConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * ArrivalTolerance 到位容差。控制器报告轴停止后，|实际位置-目标| ≤ 此值才视为到位。
             * 超过此值但 < CriticalDeviationLimit 视为"超差"（普通停止 + 终止遍历）。
             * 用户必须根据设备实际精度设置：B140+编码器约 0.005mm，无编码器/WTNMC4A 约 0.05-0.1mm。
             * @member
             * @type {number | null | undefined}
             */
            this["arrivalTolerance"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CriticalDeviationLimit 严重偏离阈值。超过此值触发急停（EmergencyStop）。
             * 用于识别"轴已停但偏差离谱"的严重异常（如失步、编码器故障、机械松动）。
             * @member
             * @type {number | null | undefined}
             */
            this["criticalDeviationLimit"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * NoProgressTimeoutMs 运动中无有效进展的最长时间（毫秒）。
             * 轴报告 Moving=true 但位置长时间无变化时，判定为卡死并普通停止。
             * 必须显著小于 waitForMotionComplete 的 120s 兜底超时。
             * @member
             * @type {number | null | undefined}
             */
            this["noProgressTimeoutMs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProgressEpsilon 构成"有效进展"的最小位置变化量。
             * 相邻轮询间位置变化 ≥ 此值视为有进展，重置 NoProgressTimeoutMs 计时。
             * 设太小会被传感器噪声误判为有进展，设太大会漏判微动卡死。
             * @member
             * @type {number | null | undefined}
             */
            this["progressEpsilon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AxisOverrides 按轴覆盖阈值。键为轴名（与 MotionAxisBinding.Axis 一致）。
             * 覆盖项内不允许再嵌套 AxisOverrides（递归无意义且增加解析复杂度）。
             * @member
             * @type {{ [_ in string]?: MotionSafetyConfig | null } | undefined}
             */
            this["axisOverrides"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionSafetyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionSafetyConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("axisOverrides" in $$parsedSource) {
            $$parsedSource["axisOverrides"] = $$createField4_0($$parsedSource["axisOverrides"]);
        }
        return new MotionSafetyConfig(/** @type {Partial<MotionSafetyConfig>} */($$parsedSource));
    }
}

/**
 * MotionSafetyFailure 运动安全故障快照
 * 
 * 判定失败时立即捕获事故现场，错误处理阶段不再读硬件状态——
 * 因为从判定失败到调用 Stop/EmergencyStop 之间，硬件状态可能已经变化，
 * 重新读取会丢失关键证据。
 */
export class MotionSafetyFailure {
    /**
     * Creates a new MotionSafetyFailure instance.
     * @param {Partial<MotionSafetyFailure>} [$$source = {}] - The source object to create the MotionSafetyFailure.
     */
    constructor($$source = {}) {
        if (!("controllerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["controllerId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["controllerName"] = undefined;
        }
        if (!("axis" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["axis"] = "";
        }
        if (!("verdict" in $$source)) {
            /**
             * @member
             * @type {MotionSafetyVerdict}
             */
            this["verdict"] = MotionSafetyVerdict.$zero;
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target"] = 0;
        }
        if (!("actual" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["actual"] = 0;
        }
        if (!("pointIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pointIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionSafetyFailure instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionSafetyFailure}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotionSafetyFailure(/** @type {Partial<MotionSafetyFailure>} */($$parsedSource));
    }
}

/**
 * MotionSafetyVerdict 运动安全判定结果
 * 
 * 用于 EvaluateMotionSafety 纯函数和跨样本看门狗的返回值，
 * 描述单次快照或跨样本观察到的运动状态分类。判定优先级：
 *  1. 撞限位（LimitTriggered）— 立即急停
 *  2. 运动中（OK）— 不判偏差，交给看门狗检测卡死/越过
 *  3. 轴已停 → 检查偏差：到位 / 严重偏离 / 超差
 * 
 * NoProgress 和 Overshoot 由跨样本看门狗判定，不来自单次快照。
 * @readonly
 * @enum {string}
 */
export const MotionSafetyVerdict = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * MotionSafetyOK 正常运动中，继续等待
     */
    MotionSafetyOK: "ok",

    /**
     * MotionSafetyArrived 已到位（轴停且偏差 ≤ ArrivalTolerance）
     */
    MotionSafetyArrived: "arrived",

    /**
     * MotionSafetyDeviation 超差：轴已停但偏差 > ArrivalTolerance 且 < CriticalDeviationLimit
     * 普通停止 + 终止遍历
     */
    MotionSafetyDeviation: "deviation",

    /**
     * MotionSafetyCriticalDeviation 严重偏离：轴已停且偏差 ≥ CriticalDeviationLimit
     * 急停 + 终止遍历
     */
    MotionSafetyCriticalDeviation: "critical_deviation",

    /**
     * MotionSafetyLimitTriggered 撞限位：PosLimit 或 NegLimit 触发
     * 急停 + 终止遍历
     */
    MotionSafetyLimitTriggered: "limit_triggered",

    /**
     * MotionSafetyNoProgress 运动中无进展：Moving=true 但位置长时间无变化
     * 普通停止 + 终止遍历
     */
    MotionSafetyNoProgress: "no_progress",

    /**
     * MotionSafetyOvershoot 越过目标：Moving=true 且位置已穿越目标位置
     * 普通停止 + 终止遍历
     */
    MotionSafetyOvershoot: "overshoot",

    /**
     * MotionSafetyStatusUnavailable 状态不可用：控制器掉线/已急停/目标轴连续缺失
     * 急停 + 终止遍历
     * 与 CriticalDeviation 区分：此类异常下 target/actual 可能无法读取（填 0），
     * 错误码映射到 ErrMotionStatusUnavailable 而非 ErrCriticalPositionDeviation，
     * 避免操作员误以为是位置偏离问题。
     */
    MotionSafetyStatusUnavailable: "status_unavailable",
};

// Private type creation functions
const $$createType0 = MotionSafetyConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
