// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * MotionSafetyFailure 运动安全故障快照
 * 
 * 判定失败时立即捕获事故现场，错误处理阶段不再读硬件状态——
 * 因为从判定失败到调用 Stop/EmergencyStop 之间，硬件状态可能已经变化，
 * 重新读取会丢失关键证据。
 */
export class MotionSafetyFailure {
    /**
     * Creates a new MotionSafetyFailure instance.
     * @param {Partial<MotionSafetyFailure>} [$$source = {}] - The source object to create the MotionSafetyFailure.
     */
    constructor($$source = {}) {
        if (!("controllerId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["controllerId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["controllerName"] = undefined;
        }
        if (!("axis" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["axis"] = "";
        }
        if (!("verdict" in $$source)) {
            /**
             * @member
             * @type {MotionSafetyVerdict}
             */
            this["verdict"] = MotionSafetyVerdict.$zero;
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target"] = 0;
        }
        if (!("actual" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["actual"] = 0;
        }
        if (!("pointIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pointIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionSafetyFailure instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MotionSafetyFailure}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotionSafetyFailure(/** @type {Partial<MotionSafetyFailure>} */($$parsedSource));
    }
}

/**
 * MotionSafetyVerdict 运动安全判定结果
 * 
 * 用于 EvaluateMotionSafety 纯函数和跨样本看门狗的返回值，
 * 描述单次快照或跨样本观察到的运动状态分类。判定优先级：
 *  1. 撞限位（LimitTriggered）— 立即急停
 *  2. 运动中（OK）— 不判偏差，交给看门狗检测卡死/越过
 *  3. 轴已停 → 检查偏差：到位 / 严重偏离 / 超差
 * 
 * NoProgress 和 Overshoot 由跨样本看门狗判定，不来自单次快照。
 * @readonly
 * @enum {string}
 */
export const MotionSafetyVerdict = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * MotionSafetyOK 正常运动中，继续等待
     */
    MotionSafetyOK: "ok",

    /**
     * MotionSafetyArrived 已到位（轴停且偏差 ≤ ArrivalTolerance）
     */
    MotionSafetyArrived: "arrived",

    /**
     * MotionSafetyDeviation 超差：轴已停但偏差 > ArrivalTolerance 且 < CriticalDeviationLimit
     * 普通停止 + 终止遍历
     */
    MotionSafetyDeviation: "deviation",

    /**
     * MotionSafetyCriticalDeviation 严重偏离：轴已停且偏差 ≥ CriticalDeviationLimit
     * 急停 + 终止遍历
     */
    MotionSafetyCriticalDeviation: "critical_deviation",

    /**
     * MotionSafetyLimitTriggered 撞限位：PosLimit 或 NegLimit 触发
     * 急停 + 终止遍历
     */
    MotionSafetyLimitTriggered: "limit_triggered",

    /**
     * MotionSafetyNoProgress 运动中无进展：Moving=true 但位置长时间无变化
     * 普通停止 + 终止遍历
     */
    MotionSafetyNoProgress: "no_progress",

    /**
     * MotionSafetyOvershoot 越过目标：Moving=true 且位置已穿越目标位置
     * 普通停止 + 终止遍历
     */
    MotionSafetyOvershoot: "overshoot",

    /**
     * MotionSafetyStatusUnavailable 状态不可用：控制器掉线/已急停/目标轴连续缺失
     * 急停 + 终止遍历
     * 与 CriticalDeviation 区分：此类异常下 target/actual 可能无法读取（填 0），
     * 错误码映射到 ErrMotionStatusUnavailable 而非 ErrCriticalPositionDeviation，
     * 避免操作员误以为是位置偏离问题。
     */
    MotionSafetyStatusUnavailable: "status_unavailable",
};
