// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../internal/adapters/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as calibration$0 from "../../internal/core/calibration/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as device$0 from "../../internal/core/device/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as motion$0 from "../../internal/core/motion/models.js";

/**
 * ==================== Calibration Types ====================
 *
 * 以下 DTO 别名把 adapters/config 层的传输对象对外暴露，供 desktop-wails backend
 * 等独立模块通过公共包访问。backend 是独立 Go module，无法直接 import
 * internal/adapters/config（Go internal 规则），因此沿用 pkg/types 的 facade 模式。
 */
export const CalibrationConfigDTO = config$0.CalibrationConfigDTO;

/**
 * ==================== Calibration Types ====================
 *
 * 以下 DTO 别名把 adapters/config 层的传输对象对外暴露，供 desktop-wails backend
 * 等独立模块通过公共包访问。backend 是独立 Go module，无法直接 import
 * internal/adapters/config（Go internal 规则），因此沿用 pkg/types 的 facade 模式。
 * @typedef {config$0.CalibrationConfigDTO} CalibrationConfigDTO
 */

/**
 * ==================== Calibration Types ====================
 */
export const CalibrationStatus = calibration$0.Status;

/**
 * ==================== Calibration Types ====================
 * @typedef {calibration$0.Status} CalibrationStatus
 */

/**
 * ==================== Device Types ====================
 */
export const DeviceDataPayload = device$0.DataPayload;

/**
 * ==================== Device Types ====================
 * @typedef {device$0.DataPayload} DeviceDataPayload
 */

/**
 * ==================== Device Types ====================
 */
export const DeviceProfile = device$0.Profile;

/**
 * ==================== Device Types ====================
 * @typedef {device$0.Profile} DeviceProfile
 */

/**
 * ==================== Device Types ====================
 */
export const DeviceScanResult = device$0.ScanResult;

/**
 * ==================== Device Types ====================
 * @typedef {device$0.ScanResult} DeviceScanResult
 */

/**
 * ==================== Device Types ====================
 */
export const DeviceStatus = device$0.Status;

/**
 * ==================== Device Types ====================
 * @typedef {device$0.Status} DeviceStatus
 */

/**
 * ==================== Motion Types ====================
 */
export const MotionControllerProfile = motion$0.MotionControllerProfile;

/**
 * ==================== Motion Types ====================
 * @typedef {motion$0.MotionControllerProfile} MotionControllerProfile
 */
