// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {calibration} from '../models';
import {device} from '../models';
import {motion} from '../models';
import {frontend} from '../models';
import {report} from '../models';
import {storage} from '../models';

export function CalibrationCollect():Promise<backend.GenericResponse>;

export function CalibrationGetResult(arg1:string):Promise<calibration.Status|boolean>;

export function CalibrationPause():Promise<backend.GenericResponse>;

export function CalibrationResume():Promise<backend.GenericResponse>;

export function CalibrationStart(arg1:calibration.Config):Promise<backend.GenericResponse>;

export function CalibrationStatus():Promise<calibration.Status>;

export function CalibrationStop():Promise<backend.GenericResponse>;

export function DeviceConnect(arg1:string):Promise<backend.GenericResponse>;

export function DeviceDeleteProfile(arg1:string):Promise<backend.GenericResponse>;

export function DeviceDisconnect(arg1:string):Promise<backend.GenericResponse>;

export function DeviceGetLatestData(arg1:string):Promise<device.DataPayload|boolean>;

export function DeviceGetProfiles():Promise<Array<device.Profile>>;

export function DeviceGetPublishRate():Promise<number>;

export function DeviceGetStatus(arg1:string):Promise<device.Status|boolean>;

export function DeviceScanDevices():Promise<Array<device.ScanResult>>;

export function DeviceSetPublishRate(arg1:number):Promise<backend.GenericResponse>;

export function DeviceStartAcquisition(arg1:string):Promise<backend.GenericResponse>;

export function DeviceStopAcquisition(arg1:string):Promise<backend.GenericResponse>;

export function DeviceSubscribeStream(arg1:string,arg2:boolean):Promise<backend.GenericResponse>;

export function DeviceUpsertProfile(arg1:device.Profile):Promise<backend.GenericResponse>;

export function GetVersion():Promise<backend.VersionInfo>;

export function MotionConnect(arg1:string):Promise<backend.GenericResponse>;

export function MotionDefinePosition(arg1:string,arg2:string,arg3:number):Promise<backend.GenericResponse>;

export function MotionDeleteProfile(arg1:string):Promise<backend.GenericResponse>;

export function MotionDisconnect(arg1:string):Promise<backend.GenericResponse>;

export function MotionEmergencyStop(arg1:string):Promise<backend.GenericResponse>;

export function MotionGetProfiles():Promise<Array<motion.MotionControllerProfile>>;

export function MotionGetStatus():Promise<Array<motion.ControllerStatus>>;

export function MotionHome(arg1:string,arg2:string):Promise<backend.GenericResponse>;

export function MotionJog(arg1:string,arg2:string,arg3:number):Promise<backend.GenericResponse>;

export function MotionMoveBy(arg1:string,arg2:string,arg3:number):Promise<backend.GenericResponse>;

export function MotionMoveTo(arg1:string,arg2:string,arg3:number):Promise<backend.GenericResponse>;

export function MotionStop(arg1:string,arg2:string):Promise<backend.GenericResponse>;

export function MotionUpsertProfile(arg1:motion.MotionControllerProfile):Promise<backend.GenericResponse>;

export function PickDirectory():Promise<string>;

export function PickFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function PickFiles(arg1:string,arg2:Array<frontend.FileFilter>):Promise<Array<string>>;

export function ReportGetStatus():Promise<report.ReportStatus>;

export function StorageGetStatus():Promise<storage.RecordingStatus>;

export function StorageStartRecording(arg1:string,arg2:string):Promise<backend.GenericResponse>;

export function StorageStopRecording():Promise<backend.GenericResponse>;
