// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ReportStatus {
    /**
     * Creates a new ReportStatus instance.
     * @param {Partial<ReportStatus>} [$$source = {}] - The source object to create the ReportStatus.
     */
    constructor($$source = {}) {
        if (!("generating" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["generating"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastResult"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportStatus(/** @type {Partial<ReportStatus>} */($$parsedSource));
    }
}
